-- Faust OS production persistence schema. Apply in the Supabase SQL editor before enabling production mode.
-- Every business record is tenant-scoped. Local JSON remains development fallback only.
create extension if not exists pgcrypto;

create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists businesses (id uuid primary key default gen_random_uuid(), name text not null, currency text not null default 'USD', timezone text not null default 'America/New_York', owner_id uuid not null references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists business_members (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, user_id uuid not null references profiles(id) on delete cascade, role text not null check (role in ('owner','admin','operations','finance','fulfillment','viewer')), created_at timestamptz not null default now(), unique(business_id,user_id));
create table if not exists business_settings (id uuid primary key default gen_random_uuid(), business_id uuid not null unique references businesses(id) on delete cascade, tax_reserve_percent numeric not null default 0, operating_buffer numeric not null default 0, reservation_timing text not null default 'paid', deduction_timing text not null default 'shipped', low_stock_default integer not null default 2, appearance jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

-- Catalog and inventory
create table if not exists products (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, title text not null, description text, brand text, category text, subcategory text, tags text[] not null default '{}', supplier_id uuid, source_url text, source_platform text, status text not null default 'draft', created_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);
create table if not exists product_variants (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, product_id uuid not null references products(id) on delete cascade, sku text not null, barcode text, size text, color text, material text, condition text, attributes jsonb not null default '{}'::jsonb, landed_unit_cost numeric not null default 0, default_selling_price numeric not null default 0, weight_oz numeric, dimensions jsonb not null default '{}'::jsonb, reorder_point integer not null default 0, reorder_quantity integer not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,sku));
create table if not exists product_images (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, product_id uuid not null references products(id) on delete cascade, url text not null, alt_text text, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inventory_locations (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, warehouse text not null, room text, zone text, aisle text, shelf text, bin text, scannable_code text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,scannable_code));
create table if not exists inventory_balances (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, variant_id uuid not null references product_variants(id) on delete cascade, location_id uuid references inventory_locations(id), on_hand integer not null default 0, reserved integer not null default 0, committed integer not null default 0, incoming integer not null default 0, damaged integer not null default 0, returned integer not null default 0, lost integer not null default 0, quarantined integer not null default 0, updated_at timestamptz not null default now(), unique(variant_id,location_id));
create table if not exists stock_movements (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, variant_id uuid not null references product_variants(id), quantity integer not null, movement_type text not null check (movement_type in ('purchase_received','manual_adjustment','order_reservation','order_cancellation','sale','return','damage','loss','transfer','cycle_count')), source_location_id uuid references inventory_locations(id), destination_location_id uuid references inventory_locations(id), reference_type text, reference_id uuid, reason text, actor_id uuid references profiles(id), created_at timestamptz not null default now());
create table if not exists inventory_counts (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, location_id uuid references inventory_locations(id), status text not null default 'draft', started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inventory_count_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, inventory_count_id uuid not null references inventory_counts(id) on delete cascade, variant_id uuid not null references product_variants(id), expected_quantity integer not null default 0, counted_quantity integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

-- Suppliers, purchasing, and inbound freight
create table if not exists suppliers (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, source_platform text, store_url text, status text not null default 'active', lead_days integer, rating numeric, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);
alter table products add constraint products_supplier_fk foreign key (supplier_id) references suppliers(id) on delete set null;
create table if not exists supplier_contacts (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, supplier_id uuid not null references suppliers(id) on delete cascade, name text not null, channel text, value text, is_primary boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists supplier_products (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, supplier_id uuid not null references suppliers(id) on delete cascade, variant_id uuid references product_variants(id), supplier_sku text, unit_cost numeric not null default 0, minimum_order_quantity integer not null default 1, source_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists purchase_orders (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, supplier_id uuid not null references suppliers(id), reference text not null, status text not null default 'draft', currency text not null default 'USD', ordered_at timestamptz, expected_at timestamptz, total_cost numeric not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,reference));
create table if not exists purchase_order_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, purchase_order_id uuid not null references purchase_orders(id) on delete cascade, variant_id uuid not null references product_variants(id), ordered_quantity integer not null, received_quantity integer not null default 0, unit_cost numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists purchase_order_payments (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, purchase_order_id uuid not null references purchase_orders(id) on delete cascade, amount numeric not null, paid_at timestamptz, method text, reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inbound_parcels (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, purchase_order_id uuid references purchase_orders(id), tracking_number text not null, carrier text, status text not null default 'awaiting_dispatch', origin text, destination text, latitude numeric, longitude numeric, estimated_arrival timestamptz, raw_tracking jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inbound_parcel_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, inbound_parcel_id uuid not null references inbound_parcels(id) on delete cascade, purchase_order_item_id uuid references purchase_order_items(id), variant_id uuid references product_variants(id), expected_quantity integer not null default 0, received_quantity integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists receiving_sessions (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, inbound_parcel_id uuid references inbound_parcels(id), status text not null default 'open', started_by uuid references profiles(id), started_at timestamptz not null default now(), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists receiving_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, receiving_session_id uuid not null references receiving_sessions(id) on delete cascade, variant_id uuid not null references product_variants(id), expected_quantity integer not null default 0, received_quantity integer not null default 0, damaged_quantity integer not null default 0, missing_quantity integer not null default 0, location_id uuid references inventory_locations(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists supplier_issues (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, supplier_id uuid references suppliers(id), purchase_order_id uuid references purchase_orders(id), status text not null default 'open', severity text not null default 'warning', detail text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

-- Commerce and customer records
create table if not exists marketplaces (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, code text not null, name text not null, capabilities jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,code));
create table if not exists marketplace_accounts (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, marketplace_id uuid not null references marketplaces(id) on delete cascade, display_name text not null, connection_state text not null default 'manual', credentials_encrypted text, last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists listings (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, variant_id uuid not null references product_variants(id), marketplace_account_id uuid references marketplace_accounts(id), marketplace_listing_id text, title text not null, description text, price numeric not null default 0, quantity integer not null default 0, status text not null default 'draft', marketplace_url text, views integer, likes integer, watchers integer, sync_state text not null default 'manual', last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists listing_images (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, listing_id uuid not null references listings(id) on delete cascade, product_image_id uuid references product_images(id), url text not null, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists listing_sync_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, listing_id uuid not null references listings(id) on delete cascade, operation text not null, status text not null, detail text, created_at timestamptz not null default now());
create table if not exists listing_errors (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, listing_id uuid not null references listings(id) on delete cascade, code text, message text not null, resolved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists customers (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, email text, phone text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists customer_addresses (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, customer_id uuid not null references customers(id) on delete cascade, recipient text, line1 text, line2 text, city text, state text, postal_code text, country text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, marketplace_account_id uuid references marketplace_accounts(id), customer_id uuid references customers(id), marketplace_order_id text, status text not null default 'draft', ordered_at timestamptz not null default now(), paid_at timestamptz, shipping_address_id uuid references customer_addresses(id), subtotal numeric not null default 0, discounts numeric not null default 0, taxes numeric not null default 0, shipping_charged numeric not null default 0, marketplace_fees numeric not null default 0, payment_fees numeric not null default 0, shipping_cost numeric not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists order_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, order_id uuid not null references orders(id) on delete cascade, listing_id uuid references listings(id), variant_id uuid references product_variants(id), title text not null, quantity integer not null, unit_price numeric not null, unit_cost numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists order_status_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, order_id uuid not null references orders(id) on delete cascade, status text not null, actor_id uuid references profiles(id), detail text, created_at timestamptz not null default now());
create table if not exists refunds (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, order_id uuid not null references orders(id), amount numeric not null, status text not null default 'requested', reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists returns (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, order_id uuid not null references orders(id), status text not null default 'requested', reason text, tracking_number text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists return_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, return_id uuid not null references returns(id) on delete cascade, order_item_id uuid references order_items(id), disposition text, quantity integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

-- Outbound shipping, finance, and operations
create table if not exists packages (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, order_id uuid references orders(id), weight_oz numeric, dimensions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists shipments (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, order_id uuid references orders(id), package_id uuid references packages(id), carrier text, service text, tracking_number text, status text not null default 'draft', shipped_at timestamptz, delivered_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists shipment_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, shipment_id uuid not null references shipments(id) on delete cascade, status text not null, location text, occurred_at timestamptz not null default now(), raw_event jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists shipping_labels (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, shipment_id uuid not null references shipments(id), label_url text, cost numeric, purchased_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists shipping_presets (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, carrier text, service text, package jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists financial_accounts (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, account_type text not null, current_balance numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists transaction_categories (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, kind text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,name));
create table if not exists transactions (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, financial_account_id uuid references financial_accounts(id), category_id uuid references transaction_categories(id), order_id uuid references orders(id), purchase_order_id uuid references purchase_orders(id), amount numeric not null, status text not null default 'pending', occurred_at timestamptz not null default now(), description text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists payouts (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, marketplace_account_id uuid references marketplace_accounts(id), amount numeric not null, status text not null default 'pending', expected_at timestamptz, paid_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists expenses (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, transaction_id uuid references transactions(id), vendor text, amount numeric not null, expense_date date not null default current_date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists budgets (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, period_start date not null, period_end date not null, amount numeric not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists tax_reserves (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, period_start date not null, period_end date not null, reserved_amount numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists financial_periods (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, starts_on date not null, ends_on date not null, status text not null default 'open', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists tasks (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, title text not null, status text not null default 'open', priority text not null default 'normal', due_at timestamptz, entity_type text, entity_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, user_id uuid references profiles(id), severity text not null default 'info', title text not null, detail text, href text, read_at timestamptz, resolved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists automation_rules (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, enabled boolean not null default false, trigger jsonb not null, actions jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists automation_runs (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, automation_rule_id uuid references automation_rules(id), status text not null, evidence jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists activity_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, actor_id uuid references profiles(id), action text not null, entity_type text not null, entity_id uuid, before_value jsonb, after_value jsonb, detail text, created_at timestamptz not null default now());
create table if not exists attachments (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, entity_type text not null, entity_id uuid not null, storage_path text not null, filename text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists tags (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, color text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,name));
create table if not exists entity_tags (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, tag_id uuid not null references tags(id) on delete cascade, entity_type text not null, entity_id uuid not null, created_at timestamptz not null default now(), unique(tag_id,entity_type,entity_id));
create table if not exists comments (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, entity_type text not null, entity_id uuid not null, body text not null, author_id uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

-- Sourcing, insights, and reporting
create table if not exists imported_source_products (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, source_platform text not null, source_url text not null, payload jsonb not null, imported_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists opportunities (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, imported_source_product_id uuid references imported_source_products(id), product_id uuid references products(id), status text not null default 'draft', sale_price numeric not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists opportunity_cost_inputs (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, opportunity_id uuid not null references opportunities(id) on delete cascade, key text not null, amount numeric not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists comparable_listings (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, opportunity_id uuid references opportunities(id), marketplace text, title text, price numeric, url text, evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists opportunity_analyses (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, opportunity_id uuid not null references opportunities(id) on delete cascade, score numeric, margin numeric, roi numeric, recommendation text, evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists insights (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, type text not null, title text not null, summary text not null, evidence text not null, action_href text, resolved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists insight_evidence (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, insight_id uuid not null references insights(id) on delete cascade, entity_type text, entity_id uuid, snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists forecasts (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, type text not null, period_start date, period_end date, value numeric, assumptions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists analytics_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, event_name text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists saved_reports (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, definition jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index if not exists orders_business_status_idx on orders(business_id,status,ordered_at desc);
create index if not exists listings_business_status_idx on listings(business_id,status);
create index if not exists stock_movements_business_variant_idx on stock_movements(business_id,variant_id,created_at desc);
create index if not exists transactions_business_date_idx on transactions(business_id,occurred_at desc);
create index if not exists notifications_business_unresolved_idx on notifications(business_id,resolved_at) where resolved_at is null;

create or replace function public.is_business_member(target_business_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from business_members where business_id = target_business_id and user_id = auth.uid()) $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

-- Business ownership policies. Service-role-only jobs bypass RLS; browser clients use these policies.
alter table profiles enable row level security; alter table businesses enable row level security; alter table business_members enable row level security;
create policy "profiles own profile" on profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy "members read businesses" on businesses for select using (public.is_business_member(id));
create policy "owners create businesses" on businesses for insert with check (owner_id = auth.uid());
create policy "members read memberships" on business_members for select using (public.is_business_member(business_id));
do $$ declare table_name text; begin foreach table_name in array array['business_settings','products','product_variants','product_images','inventory_locations','inventory_balances','stock_movements','inventory_counts','inventory_count_items','suppliers','supplier_contacts','supplier_products','purchase_orders','purchase_order_items','purchase_order_payments','inbound_parcels','inbound_parcel_items','receiving_sessions','receiving_items','supplier_issues','marketplaces','marketplace_accounts','listings','listing_images','listing_sync_events','listing_errors','customers','customer_addresses','orders','order_items','order_status_events','refunds','returns','return_items','packages','shipments','shipment_events','shipping_labels','shipping_presets','financial_accounts','transaction_categories','transactions','payouts','expenses','budgets','tax_reserves','financial_periods','tasks','notifications','automation_rules','automation_runs','activity_events','attachments','tags','entity_tags','comments','imported_source_products','opportunities','opportunity_cost_inputs','comparable_listings','opportunity_analyses','insights','insight_evidence','forecasts','analytics_events','saved_reports'] loop execute format('alter table %I enable row level security', table_name); execute format('create policy "tenant access" on %I for all using (public.is_business_member(business_id)) with check (public.is_business_member(business_id))', table_name); end loop; end $$;
