import "server-only";
import fs from "fs/promises";
import path from "path";
import type { Budget, Expense, Forecast, FulfillmentException, FulfillmentLabel, FulfillmentManifest, FulfillmentPackage, FulfillmentPickList, FulfillmentRate, FulfillmentShipment, FulfillmentStatus, Marketplace, OperatingData, Order, OrderAddress, OrderImportBatch, OrderImportReview, OrderStatus, Payout, ReinvestmentAllocation, SavedOrderView, StockBalance, TaxReserveMovement } from "@/domain/business";
import { availableCash, availableUnits, inventoryValue, orderProfit, reorderSuggestion } from "@/lib/business-calculations";
import type { Opportunity as LegacyOpportunity } from "@/types/opportunity";
import { isProductionAuthEnabled } from "@/lib/env";
import { applyFinanceMutationRpc, applyFulfillmentMutationRpc, applyInventoryMutationRpc, applyInventoryTransferRpc, applyOrderTransition, applyParcelReceipt, readNormalizedOperatingData, writeNormalizedOperatingData } from "@/services/operating-system/supabase-repository";
import { advanceOrder, cancelOrderItems, createOrderRefund, receiveOrderReturn, receiveParcelItems } from "@/lib/operational-workflows";
import { adjustStock, assignLocation, markDamaged, markLost, moveToQuarantine, recordFound, reconcileCycleCount, releaseFromQuarantine, transferStock } from "@/lib/inventory-actions";
import type { ImportedOrderLine } from "@/lib/order-import";
import { applyCreateOrderRpc } from "@/services/operating-system/supabase-repository";
import { applyOrderRefundRpc, applyReturnReceiptRpc } from "@/services/operating-system/supabase-repository";
import { getShippingProvider, type ShippingProviderKey } from "@/services/adapters/shipping";

const file = path.join(process.cwd(), ".faust", "operating-system.json");
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const empty = (): OperatingData => ({ version: 1, mode: "empty", products: [], variants: [], locations: [], balances: [], stockMovements: [], suppliers: [], purchaseOrders: [], parcels: [], listings: [], customers: [], orders: [], transactions: [], tasks: [], notices: [], insights: [], activity: [], orderImportReviews: [], orderImportBatches: [], savedOrderViews: defaultOrderViews(), fulfillmentShipments: [], fulfillmentPickLists: [], fulfillmentExceptions: [], fulfillmentManifests: [], updatedAt: now() });
async function readLocal(): Promise<OperatingData> { try { return JSON.parse(await fs.readFile(file, "utf8")) as OperatingData; } catch (error: unknown) { if (typeof error === "object" && error && "code" in error && error.code === "ENOENT") return empty(); throw error; } }
async function read(): Promise<OperatingData> { return isProductionAuthEnabled() ? readNormalizedOperatingData() : readLocal(); }
async function write(data: OperatingData) { data.updatedAt = now(); if (isProductionAuthEnabled()) return writeNormalizedOperatingData(data); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, JSON.stringify(data, null, 2)); return data; }
function activity(data: OperatingData, action: string, entityType: string, entityId: string, detail: string) { data.activity.unshift({ id: id(), action, entityType, entityId, detail, createdAt: now() }); }
function defaultOrderViews(): SavedOrderView[] { const time = now(); return ["All Orders", "Needs Action", "Ship Today", "Unpaid", "Reservation Failed", "Negative Margin", "Returns Open", "Refund Review", "Import Review"].map((name, position) => ({ id: id(), name, filters: {}, isDefault: position === 0, position, createdAt: time })); }
function ensureOrderCollections(data: OperatingData) { data.orderImportReviews ||= []; data.orderImportBatches ||= []; data.savedOrderViews ||= defaultOrderViews(); }
function orderNotice(data: OperatingData, title: string, detail: string, href: string, entityType: string, entityId: string, severity: "critical" | "warning" | "info" = "warning") { const existing = data.notices.find((notice) => !notice.resolved && !notice.archived && notice.category === "orders" && notice.entityType === entityType && notice.entityId === entityId && notice.title === title); if (existing) return existing; const notice = { id: id(), severity, title, detail, actionLabel: "Review", href, createdAt: now(), category: "orders" as const, entityType, entityId, read: false }; data.notices.unshift(notice); return notice; }
function summarizeBatch(batch: OrderImportBatch) { batch.acceptedRows = batch.rows.filter((row) => ["accepted", "resolved", "imported"].includes(row.status)).length; batch.rejectedRows = batch.rows.filter((row) => row.status === "rejected").length; batch.unresolvedRows = batch.rows.filter((row) => row.status === "review_required").length; batch.failedRows = batch.rows.filter((row) => row.status === "failed").length; batch.importedOrders = batch.createdOrderIds.length; batch.status = batch.archivedAt ? "archived" : batch.failedRows ? "partially_failed" : batch.importedOrders ? "completed" : batch.unresolvedRows ? "review_required" : "ready"; batch.updatedAt = now(); }
function ensureFulfillmentCollections(data: OperatingData) { data.fulfillmentShipments ||= []; data.fulfillmentPickLists ||= []; data.fulfillmentExceptions ||= []; data.fulfillmentManifests ||= []; }
function ensureFinanceCollections(data: OperatingData) { data.expenses ||= []; data.payouts ||= []; data.payoutReconciliations ||= []; data.budgets ||= []; data.taxReserveMovements ||= []; data.reinvestmentAllocations ||= []; data.forecasts ||= []; data.financialAccounts ||= []; data.financeCategories ||= []; }
function shipmentEvent(status: FulfillmentStatus, label: string) { return { id: id(), status, label, timestamp: now() }; }
function shippingNotice(data: OperatingData, title: string, detail: string, entityType: string, entityId: string, severity: "critical" | "warning" | "info" = "warning") { const existing = data.notices.find((notice) => !notice.resolved && !notice.archived && notice.category === "shipping" && notice.entityType === entityType && notice.entityId === entityId && notice.title === title); if (existing) return existing; data.notices.unshift({ id: id(), severity, title, detail, actionLabel: "Open shipping", href: "/shipping", createdAt: now(), category: "shipping", entityType, entityId, read: false }); }
function setShipmentStatus(shipment: FulfillmentShipment, status: FulfillmentStatus, label: string) { shipment.status = status; shipment.timestamps[status] = now(); shipment.events.unshift(shipmentEvent(status, label)); shipment.updatedAt = now(); }
function getShipment(data: OperatingData, shipmentId: string) { ensureFulfillmentCollections(data); const shipment = data.fulfillmentShipments!.find((entry) => entry.id === shipmentId); if (!shipment) throw new Error("Shipment not found."); return shipment; }
function getShipmentOrder(data: OperatingData, shipment: FulfillmentShipment) { const order = data.orders.find((entry) => entry.id === shipment.orderId); if (!order) throw new Error("Order not found for shipment."); return order; }
function shipmentAddress(order: Order): OrderAddress { return order.shippingAddress || { name: dataCustomerNameFallback(order.customerId), line1: "1200 Demo Warehouse Way", city: "Richmond", region: "VA", postalCode: "23220", country: "US" }; }
function dataCustomerNameFallback(customerId: string) { void customerId; return "Demo customer"; }
function selectedPackage(shipment: FulfillmentShipment): FulfillmentPackage[] { if (!shipment.packages.length) throw new Error("Complete packing before shopping rates or buying labels."); return shipment.packages; }
function activeLabel(shipment: FulfillmentShipment): FulfillmentLabel | undefined { return shipment.labelHistory?.find((label) => label.status === "active" || label.status === "regenerated"); }

export function developmentDemo(): OperatingData {
 const time = now(); const supplierId = id(), productId = id(), variantId = id(), locationId = id(), customerId = id(), listingId = id(), orderId = id(), poId = id(), parcelId = id(), poItemId = id();
 const order: Order = { id: orderId, number: "FO-1042", marketplace: "Depop", customerId, items: [{ id: id(), productId, variantId, listingId, title: "Vintage wash heavyweight hoodie - charcoal L", quantity: 1, unitSellingPrice: 86, discountAllocation: 0, taxAllocation: 0, feeAllocation: 0, unitCost: 31.7 }], shippingCharged: 8, shippingCost: 7.45, marketplaceFee: 9.4, paymentFee: 2.82, taxCollected: 0, status: "ready_to_ship", orderedAt: time, shipBy: new Date(Date.now() + 86400000).toISOString() };
 return { version: 1, mode: "development_demo", updatedAt: time,
  suppliers: [{ id: supplierId, name: "North Star Trading", contact: "Li Wei", email: "orders@example.test", sourcePlatform: "Superbuy", leadDays: 12, rating: 4.6, status: "active" }],
  products: [{ id: productId, title: "Vintage wash heavyweight hoodie", brand: "Unbranded", category: "Streetwear", tags: ["hoodie", "vintage"], supplierId, sourceUrl: "https://example.test/product", status: "active", createdAt: time, updatedAt: time }],
  variants: [{ id: variantId, productId, sku: "FST-HOOD-001", title: "Charcoal / L", condition: "New with tags", landedUnitCost: 31.7, defaultSalePrice: 86, weightOz: 22, reorderPoint: 2, reorderQuantity: 8, active: true }],
  locations: [{ id: locationId, label: "VA-01 / A / 04 / 03", warehouse: "Virginia", zone: "A", aisle: "04", bin: "03" }],
  balances: [{ id: id(), variantId, locationId, onHand: 3, reserved: 1, incoming: 6, damaged: 0, returned: 0, lost: 0, quarantined: 0 }],
  stockMovements: [{ id: id(), variantId, quantity: 4, type: "purchase_received", referenceType: "purchase_order", referenceId: poId, note: "Received at VA-01", createdAt: time }, { id: id(), variantId, quantity: -1, type: "order_reservation", referenceType: "order", referenceId: orderId, note: "Reserved for FO-1042", createdAt: time }],
  purchaseOrders: [{ id: poId, supplierId, reference: "PO-2008", status: "ordered", orderedAt: time, expectedAt: new Date(Date.now() + 5 * 86400000).toISOString(), totalCost: 190.2, itemCount: 6, items: [{ id: poItemId, variantId, expectedQuantity: 6, receivedQuantity: 0, unitCost: 31.7 }], parcelId }],
  parcels: [{ id: parcelId, trackingNumber: "DEMO-17TRACK-1042", carrier: "17TRACK manual", status: "in_transit", origin: "Guangzhou, CN", destination: "Virginia, US", estimatedArrival: new Date(Date.now() + 5 * 86400000).toISOString(), purchaseOrderId: poId, items: [{ id: id(), variantId, purchaseOrderItemId: poItemId, expectedQuantity: 6, receivedQuantity: 0 }], events: [{ label: "Departed origin facility", timestamp: time, location: "Guangzhou, CN" }] }],
  listings: [{ id: listingId, variantId, marketplace: "Depop", title: "Vintage wash heavyweight hoodie - charcoal L", price: 86, quantity: 2, status: "active", syncState: "manual", views: 43, likes: 7, createdAt: time }],
  customers: [{ id: customerId, name: "Jordan Williams", email: "jordan@example.test", city: "Richmond", state: "VA", orderCount: 1, lifetimeValue: 94, issueCount: 0 }], orders: [order],
  transactions: [{ id: id(), type: "payout", amount: 81.18, status: "pending", occurredAt: time, orderId, description: "Depop payout for FO-1042", category: "Marketplace payout" }, { id: id(), type: "inventory", amount: -190.2, status: "cleared", occurredAt: time, purchaseOrderId: poId, description: "PO-2008 supplier payment", category: "Inventory" }],
  tasks: [{ id: id(), title: "Pack FO-1042 before shipping deadline", status: "open", priority: "critical", dueAt: order.shipBy, entityType: "order", entityId: orderId, createdAt: time }],
  notices: [{ id: id(), severity: "critical", title: "1 order needs shipment", detail: "FO-1042 has a ship-by deadline tomorrow.", actionLabel: "Open fulfillment", href: "/shipping", createdAt: time }, { id: id(), severity: "warning", title: "Reorder point reached", detail: "FST-HOOD-001 has two available units.", actionLabel: "Create purchase order", href: "/purchasing", createdAt: time }],
  insights: [{ id: id(), type: "profit", title: "Healthy margin on active order", summary: "FO-1042 is expected to remain profitable after known fees and shipping.", evidence: "Based on $94.00 collected, $31.70 landed cost, $19.67 known fees.", actionLabel: "Review order", href: "/orders", createdAt: time }, { id: id(), type: "inventory", title: "Inventory is approaching reorder point", summary: "Order six more units only after reviewing inbound stock.", evidence: "2 available, 6 incoming, reorder point is 2.", actionLabel: "Review purchasing", href: "/purchasing", createdAt: time }],
  activity: [{ id: id(), action: "Order reserved inventory", entityType: "order", entityId: orderId, detail: "FO-1042 reserved 1 × FST-HOOD-001.", createdAt: time }]
 };
}

export async function getOperatingData() { return read(); }
export async function resetOperatingData(mode: "empty" | "development_demo") { return write(mode === "development_demo" ? developmentDemo() : empty()); }
/** Converts a reviewed sourcing opportunity into connected catalog, stock, and listing-draft records. */
export async function convertOpportunity(opportunity: LegacyOpportunity) {
 const data = await read(); const sourceUrl = opportunity.product.sourcing.superbuyUrl; let product = data.products.find((entry) => entry.sourceUrl === sourceUrl);
 if (product) return write(data);
 if (data.mode === "empty") data.mode = "local";
 const supplierName = opportunity.product.supplier.storeName || opportunity.product.supplier.name || "Unassigned supplier";
 let supplier = data.suppliers.find((entry) => entry.name.toLowerCase() === supplierName.toLowerCase());
 if (!supplier) { supplier = { id: id(), name: supplierName, sourcePlatform: "Superbuy", status: "active", notes: "Created from saved opportunity." }; data.suppliers.push(supplier); }
 const createdAt = now(); product = { id: id(), title: opportunity.product.name, category: opportunity.product.category || "Uncategorized", tags: opportunity.listing.tags || [], supplierId: supplier.id, sourceUrl, image: opportunity.product.media.images[0], status: "draft", createdAt, updatedAt: createdAt }; data.products.push(product);
 const unitCost = Object.values(opportunity.costs).reduce((sum, line) => sum + (line.amount || 0), 0); const variant = { id: id(), productId: product.id, sku: `FST-${product.id.slice(0, 6).toUpperCase()}`, title: opportunity.product.variants[0]?.name || "Default variant", condition: "New", landedUnitCost: unitCost, defaultSalePrice: opportunity.salePrice, weightOz: Number.parseFloat(opportunity.product.shippingWeight || opportunity.product.weight || "") || undefined, reorderPoint: 1, reorderQuantity: 5, active: true }; data.variants.push(variant);
 const balance: StockBalance = { id: id(), variantId: variant.id, onHand: 0, reserved: 0, incoming: 0, damaged: 0, returned: 0, lost: 0, quarantined: 0 }; data.balances.push(balance);
 const marketplace = opportunity.listing.marketplaceId === "depop" ? "Depop" : opportunity.listing.marketplaceId === "ebay" ? "eBay" : opportunity.listing.marketplaceId === "etsy" ? "Etsy" : opportunity.listing.marketplaceId === "mercari" ? "Mercari" : opportunity.listing.marketplaceId === "poshmark" ? "Poshmark" : "Manual";
 data.listings.push({ id: id(), variantId: variant.id, marketplace, title: opportunity.listing.title || product.title, price: opportunity.salePrice, quantity: 0, status: "draft", syncState: "manual", createdAt });
 activity(data, "Opportunity converted to product", "product", product.id, `${product.title} is now a catalog product with a listing draft. Create a purchase order before receiving stock.`); return write(data);
}
export async function transitionOrder(idValue: string, status: OrderStatus) { if (isProductionAuthEnabled()) return applyOrderTransition(idValue, status); const data = await read(); const order = data.orders.find((entry) => entry.id === idValue); if (!order) throw new Error("Order not found."); const result = advanceOrder(order, data.balances, status); Object.assign(order, result.order); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, `Order marked ${status.replaceAll("_", " ")}`, "order", order.id, `${order.number} status updated.`); return write(data); }
export type ManualOrderInput = { number?: string; marketplace: Marketplace; customer: { name: string; email?: string; city?: string; state?: string }; items: { productId?: string; variantId: string; listingId?: string; title?: string; quantity: number; unitSellingPrice: number; discountAllocation?: number; taxAllocation?: number; marketplaceFeeAllocation?: number; paymentFeeAllocation?: number; unitCost?: number }[]; shippingCharged?: number; shippingCost?: number; marketplaceFee?: number; paymentFee?: number; taxCollected?: number; shipBy?: string; notes?: string; idempotencyKey?: string };
export async function createOrder(input: ManualOrderInput) { if (isProductionAuthEnabled()) throw new Error("Production order RPC setup is required before creating orders."); const data = await read(); if (!input.items.length) throw new Error("An order must contain at least one line item."); if (input.idempotencyKey && data.orders.some((order) => order.idempotencyKey === input.idempotencyKey)) return data; let customer = input.customer.email ? data.customers.find((entry) => entry.email?.toLowerCase() === input.customer.email?.toLowerCase()) : undefined; if (!customer) { customer = { id: id(), name: input.customer.name, email: input.customer.email, city: input.customer.city, state: input.customer.state, orderCount: 0, lifetimeValue: 0, issueCount: 0 }; data.customers.push(customer); } const orderId = id(); const order: Order = { id: orderId, number: input.number || `FO-${String(data.orders.length + 1001).padStart(4, "0")}`, marketplace: input.marketplace, customerId: customer.id, items: input.items.map((item) => { const variant = data.variants.find((entry) => entry.id === item.variantId); if (!variant || !Number.isInteger(item.quantity) || item.quantity <= 0) throw new Error("Every order item needs a valid variant and positive whole quantity."); return { id: id(), productId: item.productId || variant.productId, variantId: item.variantId, listingId: item.listingId, title: item.title || variant.title, quantity: item.quantity, unitSellingPrice: item.unitSellingPrice, discountAllocation: item.discountAllocation || 0, taxAllocation: item.taxAllocation || 0, marketplaceFeeAllocation: item.marketplaceFeeAllocation || 0, paymentFeeAllocation: item.paymentFeeAllocation || 0, feeAllocation: item.marketplaceFeeAllocation || 0, unitCost: item.unitCost ?? variant.landedUnitCost, fulfillmentState: "unfulfilled", returnState: "none", refundState: "none" }; }), shippingCharged: input.shippingCharged || 0, shippingCost: input.shippingCost || 0, marketplaceFee: input.marketplaceFee || 0, paymentFee: input.paymentFee || 0, taxCollected: input.taxCollected || 0, status: "pending_payment", orderedAt: now(), shipBy: input.shipBy, notes: input.notes, idempotencyKey: input.idempotencyKey, statusEvents: [{ id: id(), toStatus: "pending_payment", detail: "Manual order created", createdAt: now() }] }; data.orders.unshift(order); customer.orderCount += 1; customer.lifetimeValue += order.items.reduce((sum, item) => sum + item.unitSellingPrice * item.quantity - item.discountAllocation, 0) + order.shippingCharged; activity(data, "Order created", "order", order.id, `${order.number} created with ${order.items.length} line item(s).`); return write(data); }
export const importOrder = createOrder;
/** Production boundary for manual and external imports; local mode preserves the JSON fallback. */
export async function createOrderTargeted(input: ManualOrderInput) { return isProductionAuthEnabled() ? applyCreateOrderRpc(input) : createOrder(input); }
export async function createOrderImportBatch(input: { filename: string; marketplace: Marketplace; lines: ImportedOrderLine[]; errors: { row: number; message: string }[]; duplicates: string[]; reviews: OrderImportReview[]; mapping: string[] }) {
 const data = await read(); ensureOrderCollections(data); const time = now(); const batchId = id(); const duplicateSet = new Set(input.duplicates);
 const rows: OrderImportBatch["rows"] = input.lines.map((line, index) => { const review = input.reviews.find((entry) => entry.externalOrderId === line.externalOrderId && entry.itemTitle === line.title); const duplicate = duplicateSet.has(line.externalOrderId); return { id: id(), rowNumber: index + 2, externalOrderId: line.externalOrderId, marketplace: line.marketplace, customerName: line.customerName, email: line.email, externalSku: line.sku, externalListingId: line.listingId, itemTitle: line.title, quantity: line.quantity, unitPrice: line.unitPrice, sourceValues: { ...line }, status: duplicate ? "rejected" as const : review ? "review_required" as const : "accepted" as const, error: duplicate ? "Duplicate external order ID." : undefined, reviewId: review?.id }; });
 rows.push(...input.errors.map((error) => ({ id: id(), rowNumber: error.row, externalOrderId: `row-${error.row}`, marketplace: input.marketplace, customerName: "", email: undefined, externalSku: undefined, externalListingId: undefined, itemTitle: "Rejected row", quantity: 0, unitPrice: 0, sourceValues: {}, status: "rejected" as const, error: error.message, reviewId: undefined })));
 const reviews = input.reviews.map((review) => ({ ...review, batchId, rowNumber: rows.find((row) => row.reviewId === review.id)?.rowNumber, updatedAt: time }));
 const batch: OrderImportBatch = { id: batchId, filename: input.filename, marketplace: input.marketplace, mapping: input.mapping, status: "preview", rows, acceptedRows: 0, rejectedRows: 0, unresolvedRows: 0, failedRows: 0, importedOrders: 0, createdOrderIds: [], createdAt: time, updatedAt: time };
 summarizeBatch(batch); data.orderImportBatches!.unshift(batch); data.orderImportReviews!.unshift(...reviews);
 for (const review of reviews) orderNotice(data, "Unresolved import item", `${review.externalOrderId} needs item mapping for ${review.itemTitle}.`, "/orders", "order_import_review", review.id);
 activity(data, "Order import preview created", "order_import_batch", batch.id, `${input.filename} has ${batch.acceptedRows} accepted row(s), ${batch.unresolvedRows} review row(s), and ${batch.rejectedRows} rejected row(s).`);
 return write(data);
}
export async function resolveOrderImportReview(input: { reviewId: string; action: "link_variant" | "link_listing" | "create_variant" | "non_inventory" | "ignore" | "cancel" | "reopen"; variantId?: string; listingId?: string; productTitle?: string; variantSku?: string }) {
 const data = await read(); ensureOrderCollections(data); const review = data.orderImportReviews!.find((entry) => entry.id === input.reviewId); if (!review) throw new Error("Import review item not found."); const batch = data.orderImportBatches!.find((entry) => entry.id === review.batchId); if (!batch) throw new Error("Import batch not found."); const row = batch.rows.find((entry) => entry.reviewId === review.id); if (!row) throw new Error("Import row not found.");
 if (input.action === "reopen") { review.state = "open"; review.resolution = undefined; row.status = "review_required"; }
 else if (input.action === "link_variant") { if (!input.variantId || !data.variants.some((entry) => entry.id === input.variantId)) throw new Error("Choose a valid variant."); review.state = "linked"; review.resolution = "variant"; review.resolvedVariantId = input.variantId; row.status = "resolved"; }
 else if (input.action === "link_listing") { const listing = data.listings.find((entry) => entry.id === input.listingId); if (!listing) throw new Error("Choose a valid listing."); review.state = "linked"; review.resolution = "listing"; review.resolvedListingId = listing.id; review.resolvedVariantId = listing.variantId; row.status = "resolved"; }
 else if (input.action === "create_variant") { const createdAt = now(); const productId = id(); const variantId = id(); data.products.push({ id: productId, title: input.productTitle || review.itemTitle, category: "Imported order", tags: ["order-import"], status: "active", createdAt, updatedAt: createdAt }); data.variants.push({ id: variantId, productId, sku: input.variantSku || `IMP-${review.externalOrderId.slice(0, 8).toUpperCase()}`, title: review.itemTitle, condition: "Unknown", landedUnitCost: 0, defaultSalePrice: review.unitPrice, reorderPoint: 0, reorderQuantity: 0, active: true }); data.balances.push({ id: id(), variantId, onHand: 0, reserved: 0, incoming: 0, damaged: 0, returned: 0, lost: 0, quarantined: 0 }); review.state = "resolved"; review.resolution = "created_variant"; review.createdProductId = productId; review.createdVariantId = variantId; review.resolvedVariantId = variantId; row.status = "resolved"; }
 else if (input.action === "non_inventory") { review.state = "non_inventory"; review.resolution = "non_inventory"; row.status = "resolved"; }
 else if (input.action === "ignore") { review.state = "ignored"; review.resolution = "ignored"; row.status = "ignored"; }
 else { review.state = "cancelled"; review.resolution = "cancelled"; row.status = "cancelled"; }
 review.updatedAt = now(); summarizeBatch(batch); data.notices.filter((notice) => notice.entityType === "order_import_review" && notice.entityId === review.id).forEach((notice) => { notice.resolved = row.status !== "review_required"; }); activity(data, "Order import row resolved", "order_import_review", review.id, `${review.externalOrderId} marked ${review.state}.`); return write(data);
}
export async function confirmOrderImportBatchLocal(batchId: string) {
 const data = await read(); ensureOrderCollections(data); const batch = data.orderImportBatches!.find((entry) => entry.id === batchId); if (!batch) throw new Error("Import batch not found."); if (batch.status === "completed") throw new Error("This import batch is already confirmed."); if (batch.rows.some((row) => row.status === "review_required")) throw new Error("Resolve every required review row before confirming.");
 const grouped = new Map<string, typeof batch.rows>(); for (const row of batch.rows.filter((entry) => ["accepted", "resolved"].includes(entry.status))) { const rows = grouped.get(row.externalOrderId) || []; rows.push(row); grouped.set(row.externalOrderId, rows); }
 for (const [externalOrderId, rows] of grouped) { if (data.orders.some((order) => order.marketplace === batch.marketplace && order.number === externalOrderId)) { rows.forEach((row) => { row.status = "failed"; row.error = "Duplicate external order ID."; row.retryable = false; row.lastAttemptedAt = now(); }); orderNotice(data, "Duplicate import order", `${externalOrderId} already exists in ${batch.marketplace}.`, "/orders", "order_import_batch", batch.id); continue; } const first = rows[0]; let customer = first.email ? data.customers.find((entry) => entry.email?.toLowerCase() === first.email?.toLowerCase()) : undefined; if (!customer) { customer = { id: id(), name: first.customerName, email: first.email, orderCount: 0, lifetimeValue: 0, issueCount: 0 }; data.customers.push(customer); } const orderId = id(); const order: Order = { id: orderId, number: externalOrderId, marketplace: batch.marketplace, customerId: customer.id, items: rows.filter((row) => row.status !== "ignored").map((row) => { const review = row.reviewId ? data.orderImportReviews!.find((entry) => entry.id === row.reviewId) : undefined; const listing = row.externalListingId ? data.listings.find((entry) => entry.id === row.externalListingId) : undefined; const variant = data.variants.find((entry) => entry.id === review?.resolvedVariantId || entry.sku.toLowerCase() === (row.externalSku || "").toLowerCase()) || data.variants[0]; return { id: id(), productId: variant?.productId, variantId: variant?.id || id(), listingId: listing?.id || review?.resolvedListingId, title: row.itemTitle, quantity: row.quantity, unitSellingPrice: row.unitPrice, discountAllocation: 0, taxAllocation: 0, feeAllocation: 0, unitCost: variant?.landedUnitCost || 0, fulfillmentState: review?.resolution === "non_inventory" ? "unfulfilled" : "unfulfilled", returnState: "none", refundState: "none" }; }), shippingCharged: 0, shippingCost: 0, marketplaceFee: 0, paymentFee: 0, taxCollected: 0, status: "pending_payment", orderedAt: now(), notes: `Imported from ${batch.filename} row(s): ${rows.map((row) => row.rowNumber).join(", ")}`, idempotencyKey: `${batch.id}:${externalOrderId}`, statusEvents: [{ id: id(), toStatus: "pending_payment", detail: "Imported from CSV batch", createdAt: now() }] }; if (!order.items.length) { rows.forEach((row) => { row.status = "cancelled"; }); continue; } data.orders.unshift(order); customer.orderCount += 1; customer.lifetimeValue += order.items.reduce((sum, item) => sum + item.quantity * item.unitSellingPrice, 0); rows.forEach((row) => { row.status = "imported"; row.orderId = order.id; row.lastAttemptedAt = now(); }); batch.createdOrderIds.push(order.id); activity(data, "Imported order created", "order", order.id, `${order.number} created from ${batch.filename}.`); }
 summarizeBatch(batch); batch.confirmedAt = now(); activity(data, "Order import batch confirmed", "order_import_batch", batch.id, `${batch.importedOrders} order(s) created.`); return write(data);
}
export async function updateOrderImportBatch(input: { action: "confirm" | "retry" | "reopen" | "archive"; batchId: string }) { if (input.action === "confirm" || input.action === "retry") return confirmOrderImportBatchLocal(input.batchId); const data = await read(); ensureOrderCollections(data); const batch = data.orderImportBatches!.find((entry) => entry.id === input.batchId); if (!batch) throw new Error("Import batch not found."); if (input.action === "reopen") { batch.rows.filter((row) => row.status === "failed").forEach((row) => { row.status = "accepted"; row.error = undefined; }); } else { batch.archivedAt = now(); } summarizeBatch(batch); activity(data, `Order import batch ${input.action}`, "order_import_batch", batch.id, batch.filename); return write(data); }
export async function updateSavedOrderView(input: { action: string; id?: string; ids?: string[]; name?: string; query?: string; marketplace?: Marketplace; status?: OrderStatus; isDefault?: boolean }) { const data = await read(); ensureOrderCollections(data); const views = data.savedOrderViews!; const selected = input.id ? views.find((view) => view.id === input.id) : undefined; if (["rename", "update", "duplicate", "delete", "default"].includes(input.action) && !selected) throw new Error("Saved view not found."); if (input.action === "create") views.push({ id: id(), name: input.name || "New view", filters: { query: input.query, marketplace: input.marketplace, status: input.status }, isDefault: input.isDefault, position: views.length, createdAt: now() }); else if (input.action === "rename" && selected) { selected.name = input.name || selected.name; selected.updatedAt = now(); } else if (input.action === "update" && selected) { selected.filters = { ...selected.filters, query: input.query, marketplace: input.marketplace, status: input.status }; selected.updatedAt = now(); } else if (input.action === "duplicate" && selected) views.push({ ...selected, id: id(), name: `${selected.name} copy`, isDefault: false, position: views.length, createdAt: now(), updatedAt: now() }); else if (input.action === "delete" && selected) views.splice(views.indexOf(selected), 1); else if (input.action === "default" && selected) views.forEach((view) => { view.isDefault = view.id === selected.id; }); else if (input.action === "reorder" && input.ids) input.ids.forEach((viewId, position) => { const view = views.find((entry) => entry.id === viewId); if (view) view.position = position; }); activity(data, "Saved order view updated", "saved_order_view", input.id || "new", input.action); return write(data); }
export async function bulkUpdateOrders(input: { action: "reserve" | "release" | "ready-to-pack" | "packed" | "attach-preset" | "ready-to-ship" | "ship" | "cancel" | "tag" | "export"; orderIds: string[]; tag?: string; reason?: string }) { const results: { orderId: string; ok: boolean; message: string }[] = []; for (const orderId of input.orderIds) { try { if (input.action === "tag") { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); order.tags = [...new Set([...(order.tags || []), input.tag || "bulk"])]; activity(data, "Order tagged", "order", order.id, input.tag || "bulk"); await write(data); } else if (input.action === "release") await cancelOrder(orderId, input.reason || "Bulk release/cancel"); else if (input.action === "attach-preset") await attachShippingLabel(orderId, { trackingNumber: `PRESET-${orderId.slice(0, 8)}` }); else if (input.action === "reserve") await reserveOrderInventory(orderId); else if (input.action === "ready-to-pack") await markReadyToPack(orderId); else if (input.action === "packed") await markPacked(orderId); else if (input.action === "ready-to-ship") await markReadyToShip(orderId); else if (input.action === "ship") await shipOrder(orderId); else if (input.action === "cancel") await cancelOrder(orderId, input.reason || "Bulk cancellation"); results.push({ orderId, ok: true, message: "Saved" }); } catch (error) { results.push({ orderId, ok: false, message: error instanceof Error ? error.message : "Failed" }); } }
 const data = await read(); activity(data, "Bulk order action completed", "order", "bulk", `${input.action}: ${results.filter((result) => result.ok).length}/${results.length} succeeded.`); await write(data); return { data, results };
}
export async function updateOrderNotice(input: { id: string; action: "read" | "unread" | "resolve" | "reopen" | "archive" }) { const data = await read(); const notice = data.notices.find((entry) => entry.id === input.id); if (!notice) throw new Error("Notification not found."); if (input.action === "read") notice.read = true; else if (input.action === "unread") notice.read = false; else if (input.action === "resolve") notice.resolved = true; else if (input.action === "reopen") { notice.resolved = false; notice.archived = false; } else notice.archived = true; activity(data, `Notification ${input.action}`, "notice", notice.id, notice.title); return write(data); }
export async function createRefundTargeted(orderId: string, input: Parameters<typeof createOrderRefund>[1] & { idempotencyKey?: string }) { return isProductionAuthEnabled() ? applyOrderRefundRpc(orderId, input) : createRefund(orderId, input); }
export async function receiveReturnTargeted(orderId: string, returnId: string, dispositions: Parameters<typeof receiveOrderReturn>[3], idempotencyKey?: string) { return isProductionAuthEnabled() ? applyReturnReceiptRpc(returnId, dispositions, idempotencyKey) : receiveReturn(orderId, returnId, dispositions); }
export async function reserveOrderInventory(orderId: string) { return transitionOrder(orderId, "reserved"); }
export async function cancelOrder(orderId: string, reason: string) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = advanceOrder(order, data.balances, "cancelled"); Object.assign(order, result.order); order.notes = [order.notes, `Cancellation: ${reason}`].filter(Boolean).join("\n"); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement, note: reason }))); activity(data, "Order cancelled", "order", order.id, reason); return write(data); }
export async function partiallyCancelOrder(orderId: string, lines: { itemId: string; quantity: number }[], reason: string) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = cancelOrderItems(order, data.balances, lines, reason); Object.assign(order, result.order); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, "Order partially cancelled", "order", order.id, reason); return write(data); }
export async function createRefund(orderId: string, input: Parameters<typeof createOrderRefund>[1]) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = createOrderRefund(order, input); Object.assign(order, result.order); data.transactions.unshift({ id: id(), type: "refund", amount: -input.amount, status: "cleared", occurredAt: now(), orderId, description: `Refund for ${order.number}: ${input.reason}`, category: "Refund" }); activity(data, "Order refund created", "order", order.id, `${input.reason}: $${input.amount.toFixed(2)}`); return write(data); }
export async function createReturn(orderId: string, input: { reason: string; items: { orderItemId: string; quantity: number }[]; trackingNumber?: string }) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const transition = advanceOrder(order, data.balances, "return_requested"); const returnRecord = { id: id(), status: "requested" as const, reason: input.reason, trackingNumber: input.trackingNumber, items: input.items, createdAt: now() }; Object.assign(order, { ...transition.order, returns: [...(order.returns || []), returnRecord] }); activity(data, "Return requested", "order", order.id, input.reason); return write(data); }
export async function receiveReturn(orderId: string, returnId: string, dispositions: Parameters<typeof receiveOrderReturn>[3]) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = receiveOrderReturn(order, data.balances, returnId, dispositions); Object.assign(order, result.order); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, "Return received", "order", order.id, `Return ${returnId} received.`); return write(data); }
export async function updateOrderCustomer(orderId: string, customerId: string) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); const customer = data.customers.find((entry) => entry.id === customerId); if (!order || !customer) throw new Error("Order or customer not found."); order.customerId = customerId; activity(data, "Order customer updated", "order", order.id, customer.name); return write(data); }
export async function updateShippingAddress(orderId: string, address: NonNullable<Order["shippingAddress"]>) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); order.shippingAddress = address; activity(data, "Shipping address updated", "order", order.id, `${address.line1}, ${address.city}`); return write(data); }
export async function releaseOrderReservation(orderId: string, reason: string) { return cancelOrder(orderId, reason); }
export const markReadyToPack = (orderId: string) => transitionOrder(orderId, "ready_to_pack");
export const markPacked = (orderId: string) => transitionOrder(orderId, "packed");
export async function attachShippingLabel(orderId: string, input: { trackingNumber: string; labelUrl?: string }) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); order.trackingNumber = input.trackingNumber; order.shippingLabelUrl = input.labelUrl; activity(data, "Shipping label attached", "order", order.id, input.trackingNumber); return write(data); }
export const markReadyToShip = (orderId: string) => transitionOrder(orderId, "ready_to_ship");
export const shipOrder = (orderId: string) => transitionOrder(orderId, "shipped");
export const markInTransit = (orderId: string) => transitionOrder(orderId, "in_transit");
export const markDelivered = (orderId: string) => transitionOrder(orderId, "delivered");
export const closeOrder = (orderId: string) => transitionOrder(orderId, "closed");
export async function receiveParcel(idValue: string) { if (isProductionAuthEnabled()) return applyParcelReceipt(idValue); const data = await read(); const parcel = data.parcels.find((entry) => entry.id === idValue); if (!parcel) throw new Error("Parcel not found."); const po = data.purchaseOrders.find((entry) => entry.id === parcel.purchaseOrderId); const result = receiveParcelItems(parcel, po, data.balances); Object.assign(parcel, result.parcel); if (po && result.purchaseOrder) Object.assign(po, result.purchaseOrder); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, "Parcel received", "parcel", parcel.id, `${parcel.trackingNumber} was received into its linked variant balances.`); return write(data); }
export async function adjustInventory(balanceId: string, quantity: number, reason: string, idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryMutationRpc({ balanceId, action: "adjust", quantity, reason, idempotencyKey })).data; const data = await read(); const balance = data.balances.find((entry) => entry.id === balanceId); if (!balance) throw new Error("Inventory balance not found."); const result = adjustStock(balance, quantity, reason); Object.assign(balance, result.balance); data.stockMovements.unshift({ id: id(), createdAt: now(), ...result.movement }); activity(data, "Inventory adjusted", "inventory_balance", balance.id, reason); return write(data); }
export async function transferInventory(sourceBalanceId: string, destinationBalanceId: string, quantity: number, notes = "Inventory transfer", idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryTransferRpc({ sourceBalanceId, destinationBalanceId, quantity, reason: notes, idempotencyKey })).data; const data = await read(); const source = data.balances.find((entry) => entry.id === sourceBalanceId); const destination = data.balances.find((entry) => entry.id === destinationBalanceId); if (!source || !destination) throw new Error("Both source and destination balances are required."); const result = transferStock(source, destination, quantity); Object.assign(source, result.source); Object.assign(destination, result.destination); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement, note: notes }))); activity(data, "Inventory transferred", "inventory_balance", source.id, notes); return write(data); }
export async function reconcileInventoryCount(balanceId: string, countedQuantity: number, idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryMutationRpc({ balanceId, action: "cycle_count", quantity: countedQuantity, reason: "Approved cycle count", idempotencyKey })).data; const data = await read(); const balance = data.balances.find((entry) => entry.id === balanceId); if (!balance) throw new Error("Inventory balance not found."); const result = reconcileCycleCount(balance, countedQuantity); Object.assign(balance, result.balance); if (result.movement) data.stockMovements.unshift({ id: id(), createdAt: now(), ...result.movement }); activity(data, "Cycle count approved", "inventory_balance", balance.id, `Counted ${countedQuantity} units.`); return write(data); }
async function inventoryStateMutation(balanceId: string, action: "damage" | "quarantine" | "release" | "lost" | "found" | "location", quantity: number, reason: string, locationId?: string, idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryMutationRpc({ balanceId, action: action === "release" ? "release_quarantine" : action, quantity, reason, destinationLocationId: locationId, idempotencyKey })).data; const data = await read(); const balance = data.balances.find((entry) => entry.id === balanceId); if (!balance) throw new Error("Inventory balance not found."); const result = action === "damage" ? markDamaged(balance, quantity, reason) : action === "quarantine" ? moveToQuarantine(balance, quantity, reason) : action === "release" ? releaseFromQuarantine(balance, quantity, reason) : action === "lost" ? markLost(balance, quantity, reason) : action === "found" ? recordFound(balance, quantity, reason) : assignLocation(balance, locationId || ""); Object.assign(balance, result.balance); data.stockMovements.unshift({ id: id(), createdAt: now(), ...result.movement }); activity(data, `Inventory ${action}`, "inventory_balance", balance.id, reason); return write(data); }
export const markInventoryDamaged = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "damage", quantity, reason, undefined, idempotencyKey);
export const moveInventoryToQuarantine = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "quarantine", quantity, reason, undefined, idempotencyKey);
export const releaseInventoryFromQuarantine = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "release", quantity, reason, undefined, idempotencyKey);
export const markInventoryLost = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "lost", quantity, reason, undefined, idempotencyKey);
export const recordInventoryFound = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "found", quantity, reason, undefined, idempotencyKey);
export const assignInventoryLocation = (balanceId: string, locationId: string, reason = "Inventory location assigned", idempotencyKey?: string) => inventoryStateMutation(balanceId, "location", 0, reason, locationId, idempotencyKey);
export async function beginPicking(orderId: string, picker = "Unassigned", mode: "single" | "batch" | "zone" = "single") {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("beginPicking", { order_id: orderId, picker, mode });
 const data = await read(); ensureFulfillmentCollections(data); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); if (["pending_payment", "draft"].includes(order.status)) throw new Error("Order must be paid or reserved before picking.");
 let shipment = data.fulfillmentShipments!.find((entry) => entry.orderId === order.id); if (!shipment) { const createdAt = now(); shipment = { id: id(), orderId: order.id, status: "ready_to_pick", priority: order.shipBy && new Date(order.shipBy).getTime() - Date.now() < 86400000 ? "urgent" : "standard", shippingMethod: order.marketplace === "Manual" ? "Manual carrier" : `${order.marketplace} standard`, picker, slaDeadline: order.shipBy, shippingProvider: "local_mock", rateState: "idle", packageIds: [], packages: [], scanLog: [], timestamps: { ready_to_pick: createdAt }, events: [shipmentEvent("ready_to_pick", "Shipment created")], createdAt, updatedAt: createdAt }; data.fulfillmentShipments!.push(shipment); }
 const items = order.items.map((item) => { const variant = data.variants.find((entry) => entry.id === item.variantId); const balance = data.balances.find((entry) => entry.variantId === item.variantId); const location = data.locations.find((entry) => entry.id === balance?.locationId); return { id: id(), orderItemId: item.id, variantId: item.variantId, locationId: location?.id, sku: variant?.sku || item.variantId, title: item.title, quantity: item.quantity, status: "open" as const, notes: location ? location.label : "Unlocated stock" }; });
 const pickList: FulfillmentPickList = { id: id(), orderIds: [order.id], mode, picker, status: "picking", path: items.map((item) => item.locationId || "unlocated").sort(), items, createdAt: now(), updatedAt: now() }; data.fulfillmentPickLists!.unshift(pickList); setShipmentStatus(shipment, "picking", `Picking started by ${picker}.`); activity(data, "Picking started", "fulfillment_shipment", shipment.id, `${order.number} assigned to ${picker}.`); return write(data);
}
export async function completePicking(shipmentId: string, outcomes: { itemId: string; status: "picked" | "missing" | "substituted" | "damaged"; notes?: string }[] = []) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("completePicking", { shipment_id: shipmentId, outcomes });
 const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); const pickList = data.fulfillmentPickLists?.find((entry) => entry.orderIds.includes(order.id) && entry.status !== "completed"); if (!pickList) throw new Error("Open pick list not found.");
 pickList.items = pickList.items.map((item) => ({ ...item, ...(outcomes.find((entry) => entry.itemId === item.id) || { status: "picked" as const }) })); pickList.status = pickList.items.some((item) => item.status !== "picked") ? "exception" : "completed"; pickList.completedAt = now(); pickList.updatedAt = now();
 if (pickList.status === "exception") { setShipmentStatus(shipment, "exception", "Pick exception recorded."); shippingNotice(data, "Pick exception", `${order.number} has missing, damaged, or substituted items.`, "fulfillment_shipment", shipment.id, "critical"); } else { setShipmentStatus(shipment, "ready_to_pack", "Picking completed."); }
 activity(data, "Picking completed", "fulfillment_shipment", shipment.id, `${order.number} pick list ${pickList.status}.`); return write(data);
}
export async function beginPacking(shipmentId: string, packer = "Unassigned", station = "Station 1") { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("beginPacking", { shipment_id: shipmentId, packer, station }); const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (!["ready_to_pack", "packed", "picking"].includes(shipment.status)) throw new Error("Shipment must be picked before packing."); shipment.packer = packer; shipment.station = station; order.status = "ready_to_pack"; setShipmentStatus(shipment, "packing", `Packing started at ${station}.`); activity(data, "Packing started", "fulfillment_shipment", shipment.id, `${order.number} assigned to ${packer}.`); return write(data); }
export async function completePacking(shipmentId: string, input: { packageType: "poly_mailer" | "box" | "custom"; weightOz: number; lengthIn: number; widthIn: number; heightIn: number; notes?: string }) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("completePacking", { shipment_id: shipmentId, package_type: input.packageType, weight_oz: input.weightOz, length_in: input.lengthIn, width_in: input.widthIn, height_in: input.heightIn, notes: input.notes });
 const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (shipment.status !== "packing") throw new Error("Begin packing before completing the package."); const pack: FulfillmentPackage = { id: id(), type: input.packageType, weightOz: input.weightOz, lengthIn: input.lengthIn, widthIn: input.widthIn, heightIn: input.heightIn, notes: input.notes }; shipment.packages.push(pack); shipment.packageIds.push(pack.id); shipment.scanLog.push(...order.items.map((item) => ({ sku: data.variants.find((variant) => variant.id === item.variantId)?.sku || item.variantId, quantity: item.quantity, verifiedAt: now() }))); order.status = "packed"; order.items = order.items.map((item) => ({ ...item, fulfillmentState: "packed" })); setShipmentStatus(shipment, "packed", "Package verified and packed."); activity(data, "Packing completed", "fulfillment_shipment", shipment.id, `${order.number} packed in ${input.packageType}.`); return write(data);
}
export async function createPackage(shipmentId: string, input: { packageType: "poly_mailer" | "box" | "custom"; weightOz: number; lengthIn: number; widthIn: number; heightIn: number; notes?: string }) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("createPackage", { shipment_id: shipmentId, package_type: input.packageType, weight_oz: input.weightOz, length_in: input.lengthIn, width_in: input.widthIn, height_in: input.heightIn, notes: input.notes }); return completePacking(shipmentId, input); }
export async function updatePackage(shipmentId: string, packageId: string, input: Partial<{ packageType: "poly_mailer" | "box" | "custom"; weightOz: number; lengthIn: number; widthIn: number; heightIn: number; notes: string }>) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("updatePackage", { shipment_id: shipmentId, package_id: packageId, package_type: input.packageType, weight_oz: input.weightOz, length_in: input.lengthIn, width_in: input.widthIn, height_in: input.heightIn, notes: input.notes }); const data = await read(); const shipment = getShipment(data, shipmentId); const pack = shipment.packages.find((entry) => entry.id === packageId); if (!pack) throw new Error("Package not found."); Object.assign(pack, { type: input.packageType || pack.type, weightOz: input.weightOz ?? pack.weightOz, lengthIn: input.lengthIn ?? pack.lengthIn, widthIn: input.widthIn ?? pack.widthIn, heightIn: input.heightIn ?? pack.heightIn, notes: input.notes ?? pack.notes }); activity(data, "Package updated", "fulfillment_shipment", shipment.id, packageId); return write(data); }
export async function splitPackage(shipmentId: string, packageId: string, input: { weightOz: number; lengthIn: number; widthIn: number; heightIn: number; notes?: string }) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("splitPackage", { shipment_id: shipmentId, split_from: packageId, package_type: "custom", weight_oz: input.weightOz, length_in: input.lengthIn, width_in: input.widthIn, height_in: input.heightIn, notes: input.notes }); const data = await read(); const shipment = getShipment(data, shipmentId); if (!shipment.packages.some((entry) => entry.id === packageId)) throw new Error("Package not found."); const pack: FulfillmentPackage = { id: id(), type: "custom", weightOz: input.weightOz, lengthIn: input.lengthIn, widthIn: input.widthIn, heightIn: input.heightIn, splitFrom: packageId, notes: input.notes }; shipment.packages.push(pack); shipment.packageIds.push(pack.id); activity(data, "Package split", "fulfillment_shipment", shipment.id, packageId); return write(data); }
export async function mergePackage(shipmentId: string, packageIds: string[], input: { weightOz: number; lengthIn: number; widthIn: number; heightIn: number; notes?: string }) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("mergePackage", { shipment_id: shipmentId, merged_from: packageIds, package_type: "custom", weight_oz: input.weightOz, length_in: input.lengthIn, width_in: input.widthIn, height_in: input.heightIn, notes: input.notes }); const data = await read(); const shipment = getShipment(data, shipmentId); const source = shipment.packages.filter((entry) => packageIds.includes(entry.id)); if (source.length !== packageIds.length) throw new Error("Every merged package must exist."); const pack: FulfillmentPackage = { id: id(), type: "custom", weightOz: input.weightOz, lengthIn: input.lengthIn, widthIn: input.widthIn, heightIn: input.heightIn, mergedFrom: packageIds, notes: input.notes }; shipment.packages = shipment.packages.filter((entry) => !packageIds.includes(entry.id)); shipment.packages.push(pack); shipment.packageIds = shipment.packages.map((entry) => entry.id); activity(data, "Packages merged", "fulfillment_shipment", shipment.id, packageIds.join(", ")); return write(data); }
export async function validateShipmentAddress(shipmentId: string, providerKey: ShippingProviderKey = "local_mock") {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("validateAddress", { shipment_id: shipmentId, provider: providerKey });
 const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); const provider = getShippingProvider(providerKey); const validation = await provider.validateAddress(shipmentAddress(order)); shipment.shippingProvider = providerKey; shipment.addressValidation = validation; if (validation.status === "invalid") { shipment.rateState = "address_issue"; shippingNotice(data, "Invalid shipping address", `${order.number} requires address review before label purchase.`, "fulfillment_shipment", shipment.id, "critical"); } shipment.events.unshift(shipmentEvent(shipment.status, `Address validation ${validation.status}.`)); activity(data, "Address validated", "fulfillment_shipment", shipment.id, validation.warnings.join("; ") || "Address accepted."); return write(data);
}
export async function overrideShipmentAddress(shipmentId: string, reason: string) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("overrideAddress", { shipment_id: shipmentId, reason });
 const data = await read(); const shipment = getShipment(data, shipmentId); if (!shipment.addressValidation) throw new Error("Validate the address before overriding it."); shipment.addressValidation = { ...shipment.addressValidation, status: "overridden", confirmedAt: now(), overrideReason: reason }; shipment.rateState = "idle"; shipment.events.unshift(shipmentEvent(shipment.status, `Address override confirmed: ${reason}`)); activity(data, "Address override", "fulfillment_shipment", shipment.id, reason); return write(data);
}
export async function shopShipmentRates(shipmentId: string, providerKey: ShippingProviderKey = "local_mock", insurance = false, signature = false) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("requestRates", { shipment_id: shipmentId, provider: providerKey, insurance, signature });
 const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (shipment.addressValidation?.status === "invalid") throw new Error("Resolve or override the invalid address before rate shopping."); const provider = getShippingProvider(providerKey); shipment.rateState = "loading"; try { const rates = await provider.getRates({ shipmentId, orderId: order.id, address: shipmentAddress(order), packages: selectedPackage(shipment).map((pack) => ({ weightOz: pack.weightOz, lengthIn: pack.lengthIn, widthIn: pack.widthIn, heightIn: pack.heightIn, packageType: pack.type })), insurance, signature }); shipment.shippingProvider = providerKey; shipment.rates = rates as FulfillmentRate[]; shipment.rateState = rates.length ? "success" : "no_rates"; shipment.events.unshift(shipmentEvent(shipment.status, `${rates.length} shipping rate(s) returned.`)); activity(data, "Shipping rates loaded", "fulfillment_shipment", shipment.id, `${rates.length} rate options available.`); } catch (error) { shipment.rateState = error instanceof Error && error.message.includes("provider-ready") ? "provider_unavailable" : "invalid_package"; throw error; } finally { shipment.updatedAt = now(); } return write(data);
}
export async function selectShipmentRate(shipmentId: string, rateId: string) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("selectRate", { shipment_id: shipmentId, rate_id: rateId });
 const data = await read(); const shipment = getShipment(data, shipmentId); const rate = shipment.rates?.find((entry) => entry.id === rateId); if (!rate) throw new Error("Selected rate was not found."); shipment.selectedRateId = rate.id; shipment.carrier = rate.carrier; shipment.service = rate.service; shipment.postageCost = rate.negotiatedRate ?? rate.retailRate; shipment.estimatedDelivery = new Date(Date.now() + rate.deliveryDays * 86400000).toISOString(); shipment.events.unshift(shipmentEvent(shipment.status, `Selected ${rate.carrier} ${rate.service} at $${shipment.postageCost.toFixed(2)}.`)); activity(data, "Shipping rate selected", "fulfillment_shipment", shipment.id, rate.id); return write(data);
}
export async function generateShippingLabel(shipmentId: string, input: { carrier: string; service: string; postageCost: number; insurance?: boolean; signature?: boolean; regenerate?: boolean }) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc(input.regenerate ? "regenerateLabel" : "generateLabel", { shipment_id: shipmentId, carrier: input.carrier, service: input.service, postage_cost: input.postageCost, insurance: input.insurance, signature: input.signature });
 const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (!["packed", "ready_to_ship"].includes(shipment.status)) throw new Error("Shipment must be packed before label generation."); if (shipment.addressValidation?.status === "invalid") throw new Error("Resolve or override invalid address before buying a label."); const provider = getShippingProvider(shipment.shippingProvider || "local_mock"); const previousLabel = input.regenerate ? shipment.labelHistory?.[0] : activeLabel(shipment); const label = previousLabel && input.regenerate ? await provider.regenerateLabel(previousLabel, { shipmentId, orderId: order.id, address: shipmentAddress(order), packages: selectedPackage(shipment).map((pack) => ({ weightOz: pack.weightOz, lengthIn: pack.lengthIn, widthIn: pack.widthIn, heightIn: pack.heightIn, packageType: pack.type })), carrier: input.carrier || shipment.carrier, service: input.service || shipment.service, postageCost: input.postageCost || shipment.postageCost, rateId: shipment.selectedRateId, format: shipment.labelFormat || "4x6" }) : await provider.buyLabel({ shipmentId, orderId: order.id, address: shipmentAddress(order), packages: selectedPackage(shipment).map((pack) => ({ weightOz: pack.weightOz, lengthIn: pack.lengthIn, widthIn: pack.widthIn, heightIn: pack.heightIn, packageType: pack.type })), carrier: input.carrier || shipment.carrier, service: input.service || shipment.service, postageCost: input.postageCost || shipment.postageCost, rateId: shipment.selectedRateId, format: shipment.labelFormat || "4x6" });
 if (previousLabel && input.regenerate) previousLabel.status = "regenerated"; shipment.labelHistory = [label as FulfillmentLabel, ...(shipment.labelHistory || [])]; shipment.carrier = label.carrier; shipment.service = label.service; shipment.postageCost = label.postageCost; shipment.trackingNumber = label.trackingNumber; shipment.labelUrl = label.labelUrl; shipment.labelFormat = label.format; shipment.estimatedDelivery ||= new Date(Date.now() + 3 * 86400000).toISOString(); order.trackingNumber = shipment.trackingNumber; order.shippingLabelUrl = shipment.labelUrl; order.shippingCost = label.postageCost; order.statusEvents = [...(order.statusEvents || []), { id: id(), fromStatus: order.status, toStatus: "ready_to_ship", detail: input.regenerate ? "Shipping label regenerated" : "Shipping label generated", createdAt: now() }]; order.status = "ready_to_ship"; data.transactions.unshift({ id: id(), type: "shipping", amount: -label.postageCost, status: "pending", occurredAt: now(), orderId: order.id, description: `${label.carrier} ${label.service} postage for ${order.number}`, category: "Shipping" }); setShipmentStatus(shipment, "ready_to_ship", `${label.source === "mock" ? "Mock" : "Shipping"} label ${input.regenerate ? "regenerated" : "generated"}: ${shipment.trackingNumber}.`); activity(data, input.regenerate ? "Shipping label regenerated" : "Shipping label generated", "fulfillment_shipment", shipment.id, `${label.carrier} ${label.service} ${label.trackingNumber}.`); return write(data);
}
export async function attachExternalShippingLabel(shipmentId: string, providerKey: "manual_label" | "marketplace_label", input: { trackingNumber: string; labelUrl: string; carrier?: string; service?: string; postageCost?: number }) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc(providerKey === "manual_label" ? "attachManualLabel" : "attachMarketplaceLabel", { shipment_id: shipmentId, tracking_number: input.trackingNumber, label_url: input.labelUrl, carrier: input.carrier, service: input.service, postage_cost: input.postageCost });
 const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (!["packed", "ready_to_ship"].includes(shipment.status)) throw new Error("Pack the shipment before attaching a label."); const label = await getShippingProvider(providerKey).buyLabel({ shipmentId, orderId: order.id, address: shipmentAddress(order), packages: selectedPackage(shipment).map((pack) => ({ weightOz: pack.weightOz, lengthIn: pack.lengthIn, widthIn: pack.widthIn, heightIn: pack.heightIn, packageType: pack.type })), carrier: input.carrier, service: input.service, postageCost: input.postageCost, externalLabelUrl: input.labelUrl, externalTrackingNumber: input.trackingNumber }); shipment.shippingProvider = providerKey; shipment.labelHistory = [label as FulfillmentLabel, ...(shipment.labelHistory || [])]; shipment.carrier = label.carrier; shipment.service = label.service; shipment.trackingNumber = label.trackingNumber; shipment.labelUrl = label.labelUrl; shipment.postageCost = label.postageCost; order.trackingNumber = label.trackingNumber; order.shippingLabelUrl = label.labelUrl; order.shippingCost = label.postageCost; order.status = "ready_to_ship"; setShipmentStatus(shipment, "ready_to_ship", `${providerKey === "manual_label" ? "Manual" : "Marketplace"} label attached.`); activity(data, "External shipping label attached", "fulfillment_shipment", shipment.id, label.trackingNumber); return write(data);
}
export async function voidShippingLabel(shipmentId: string, reason: string) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("voidLabel", { shipment_id: shipmentId, reason });
 const data = await read(); const shipment = getShipment(data, shipmentId); const label = activeLabel(shipment); if (!label) throw new Error("No active label exists to void."); const voided = await getShippingProvider(label.provider).voidLabel(label, reason); Object.assign(label, voided); shipment.events.unshift(shipmentEvent(shipment.status, `Label voided: ${reason}`)); shippingNotice(data, "Label voided", reason, "fulfillment_shipment", shipment.id, "info"); activity(data, "Shipping label voided", "fulfillment_shipment", shipment.id, reason); return write(data);
}
export async function printShippingLabel(shipmentId: string, kind: "print" | "reprint" = "print") { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("printLabel", { shipment_id: shipmentId, kind }); const data = await read(); const shipment = getShipment(data, shipmentId); if (!shipment.labelUrl) throw new Error("Generate a label before printing."); shipment.events.unshift(shipmentEvent("printed", kind === "reprint" ? "Label reprinted." : "Label printed.")); shipment.timestamps.printed = now(); shipment.updatedAt = now(); activity(data, kind === "reprint" ? "Shipping label reprinted" : "Shipping label printed", "fulfillment_shipment", shipment.id, shipment.labelUrl); return write(data); }
export async function dispatchShipment(shipmentId: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("dispatchShipment", { shipment_id: shipmentId }); const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (!["ready_to_ship", "printed", "manifested"].includes(shipment.status)) throw new Error("Shipment must be ready to ship before dispatch."); const result = advanceOrder(order, data.balances, "shipped"); Object.assign(order, result.order); order.items = order.items.map((item) => ({ ...item, fulfillmentState: "shipped" })); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); setShipmentStatus(shipment, "dispatched", "Shipment dispatched."); setShipmentStatus(shipment, "in_transit", "Carrier accepted package."); activity(data, "Shipment dispatched", "fulfillment_shipment", shipment.id, `${order.number} dispatched with ${shipment.trackingNumber || "manual tracking"}.`); return write(data); }
export async function createFulfillmentManifest(shipmentIds: string[], carrier = "Mixed carriers") {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("createManifest", { shipment_ids: shipmentIds, carrier });
 const data = await read(); ensureFulfillmentCollections(data); const shipments = shipmentIds.map((shipmentId) => getShipment(data, shipmentId)); const blocked = shipments.filter((shipment) => !["ready_to_ship", "printed"].includes(shipment.status) || !activeLabel(shipment)); if (blocked.length) throw new Error("Only label-ready shipments can be added to a manifest."); const manifest: FulfillmentManifest = { id: id(), carrier, status: "closed", shipmentIds, labelCount: shipments.length, generatedAt: now(), closedAt: now(), activity: [`${now()}: Manifest generated for ${shipments.length} shipment(s).`] }; data.fulfillmentManifests!.unshift(manifest); shipments.forEach((shipment) => { shipment.manifestId = manifest.id; setShipmentStatus(shipment, "manifested", `Manifest ${manifest.id} generated.`); }); activity(data, "Fulfillment manifest created", "fulfillment_manifest", manifest.id, `${carrier} manifest with ${shipments.length} shipment(s).`); return write(data);
}
export async function dispatchFulfillmentManifest(manifestId: string) {
 if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("dispatchManifest", { manifest_id: manifestId });
 const data = await read(); ensureFulfillmentCollections(data); const manifest = data.fulfillmentManifests!.find((entry) => entry.id === manifestId); if (!manifest) throw new Error("Manifest not found."); if (manifest.status === "dispatched") return data; manifest.status = "dispatched"; manifest.dispatchedAt = now(); manifest.handoffConfirmedAt = now(); manifest.activity.unshift(`${now()}: Carrier handoff confirmed.`); for (const shipmentId of manifest.shipmentIds) { const shipment = getShipment(data, shipmentId); if (shipment.status === "manifested") { const order = getShipmentOrder(data, shipment); const result = advanceOrder(order, data.balances, "shipped"); Object.assign(order, result.order); order.items = order.items.map((item) => ({ ...item, fulfillmentState: "shipped" })); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); setShipmentStatus(shipment, "dispatched", "Manifest dispatched."); setShipmentStatus(shipment, "in_transit", "Carrier accepted manifest handoff."); } } activity(data, "Fulfillment manifest dispatched", "fulfillment_manifest", manifest.id, `${manifest.shipmentIds.length} shipment(s) handed off.`); return write(data);
}
export async function holdShipment(shipmentId: string, reason: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("placeHold", { shipment_id: shipmentId, reason }); const data = await read(); const shipment = getShipment(data, shipmentId); shipment.hold = { active: true, reason, createdAt: now() }; shipment.events.unshift(shipmentEvent(shipment.status, `Shipment held: ${reason}`)); shippingNotice(data, "Shipment on hold", reason, "fulfillment_shipment", shipment.id, "warning"); activity(data, "Shipment held", "fulfillment_shipment", shipment.id, reason); return write(data); }
export async function releaseShipmentHold(shipmentId: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("releaseHold", { shipment_id: shipmentId }); const data = await read(); const shipment = getShipment(data, shipmentId); shipment.hold = { ...(shipment.hold || { active: false }), active: false, releasedAt: now() }; shipment.events.unshift(shipmentEvent(shipment.status, "Shipment hold released.")); data.notices.filter((notice) => notice.category === "shipping" && notice.entityType === "fulfillment_shipment" && notice.entityId === shipment.id && notice.title === "Shipment on hold").forEach((notice) => { notice.resolved = true; }); activity(data, "Shipment hold released", "fulfillment_shipment", shipment.id, "Hold released."); return write(data); }
export async function assignFulfillment(shipmentId: string, input: { picker?: string; packer?: string; station?: string; priority?: "standard" | "high" | "urgent"; slaDeadline?: string }) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("assignFulfillment", { shipment_id: shipmentId, picker: input.picker, packer: input.packer, station: input.station, priority: input.priority, sla_deadline: input.slaDeadline }); const data = await read(); const shipment = getShipment(data, shipmentId); if (input.picker !== undefined) shipment.picker = input.picker || undefined; if (input.packer !== undefined) shipment.packer = input.packer || undefined; if (input.station !== undefined) shipment.station = input.station || undefined; if (input.priority) shipment.priority = input.priority; if (input.slaDeadline) shipment.slaDeadline = input.slaDeadline; shipment.updatedAt = now(); shipment.events.unshift(shipmentEvent(shipment.status, "Fulfillment assignment updated.")); activity(data, "Fulfillment assignment updated", "fulfillment_shipment", shipment.id, `${shipment.picker || "open picker"} / ${shipment.packer || "open packer"} / ${shipment.station || "open station"}`); return write(data); }
export async function refreshShipmentTracking(shipmentId: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("refreshTracking", { shipment_id: shipmentId }); const data = await read(); const shipment = getShipment(data, shipmentId); if (!shipment.trackingNumber) throw new Error("Tracking number is required before tracking refresh."); const tracking = await getShippingProvider(shipment.shippingProvider || "local_mock").trackShipment(shipment.trackingNumber); shipment.trackingStatus = tracking.status; shipment.lastScan = tracking.lastScan; shipment.estimatedDelivery = tracking.estimatedDelivery || shipment.estimatedDelivery; shipment.actualDelivery = tracking.actualDelivery || shipment.actualDelivery; shipment.events.unshift(...tracking.events.map((event) => ({ id: id(), status: tracking.status === "delivered" ? "delivered" as const : tracking.status === "returned" ? "returned" as const : tracking.status === "lost" ? "lost" as const : tracking.status === "claim_required" ? "claim_filed" as const : "in_transit" as const, label: event.label, timestamp: event.occurredAt, location: event.location }))); if (["delayed", "returned", "lost", "claim_required"].includes(tracking.status)) shippingNotice(data, "Tracking exception", tracking.lastScan || tracking.status, "fulfillment_shipment", shipment.id, "warning"); activity(data, "Tracking refreshed", "fulfillment_shipment", shipment.id, tracking.lastScan || tracking.status); return write(data); }
export async function markShipmentDelivered(shipmentId: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("markDelivered", { shipment_id: shipmentId }); const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); if (!["dispatched", "in_transit"].includes(shipment.status)) throw new Error("Shipment must be dispatched before delivery."); const fromStatus = order.status; order.status = "delivered"; order.statusEvents = [...(order.statusEvents || []), { id: id(), fromStatus, toStatus: "delivered", detail: "Carrier delivered shipment", createdAt: now() }]; setShipmentStatus(shipment, "delivered", "Delivered."); activity(data, "Shipment delivered", "fulfillment_shipment", shipment.id, order.number); return write(data); }
export async function markShipmentReturned(shipmentId: string, notes = "Returned by carrier") { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("markReturned", { shipment_id: shipmentId, notes }); const data = await read(); const shipment = getShipment(data, shipmentId); const order = getShipmentOrder(data, shipment); order.status = "return_requested"; setShipmentStatus(shipment, "returned", notes); shippingNotice(data, "Shipment returned", `${order.number} was returned by carrier.`, "fulfillment_shipment", shipment.id, "critical"); activity(data, "Shipment returned", "fulfillment_shipment", shipment.id, notes); return write(data); }
export async function recordFulfillmentException(input: { orderId?: string; shipmentId?: string; type: FulfillmentException["type"]; severity: FulfillmentException["severity"]; owner?: string; notes: string }) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("createException", { order_id: input.orderId, shipment_id: input.shipmentId, type: input.type, severity: input.severity, owner: input.owner, notes: input.notes }); const data = await read(); ensureFulfillmentCollections(data); const exception: FulfillmentException = { id: id(), orderId: input.orderId, shipmentId: input.shipmentId, type: input.type, severity: input.severity, owner: input.owner, notes: input.notes, status: "open", activity: [`${now()}: ${input.notes}`], createdAt: now() }; data.fulfillmentExceptions!.unshift(exception); if (input.shipmentId) { const shipment = getShipment(data, input.shipmentId); setShipmentStatus(shipment, "exception", input.notes); } shippingNotice(data, "Fulfillment exception", input.notes, "fulfillment_exception", exception.id, input.severity); activity(data, "Fulfillment exception recorded", "fulfillment_exception", exception.id, input.notes); return write(data); }
export async function resolveFulfillmentException(exceptionId: string, notes: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("resolveException", { exception_id: exceptionId, notes }); const data = await read(); ensureFulfillmentCollections(data); const exception = data.fulfillmentExceptions!.find((entry) => entry.id === exceptionId); if (!exception) throw new Error("Fulfillment exception not found."); exception.status = "resolved"; exception.resolvedAt = now(); exception.activity.push(`${now()}: ${notes}`); data.notices.filter((notice) => notice.entityType === "fulfillment_exception" && notice.entityId === exception.id).forEach((notice) => { notice.resolved = true; }); activity(data, "Fulfillment exception resolved", "fulfillment_exception", exception.id, notes); return write(data); }
export async function reopenFulfillmentException(exceptionId: string, notes: string) { if (isProductionAuthEnabled()) return applyFulfillmentMutationRpc("reopenException", { exception_id: exceptionId, notes }); const data = await read(); ensureFulfillmentCollections(data); const exception = data.fulfillmentExceptions!.find((entry) => entry.id === exceptionId); if (!exception) throw new Error("Fulfillment exception not found."); exception.status = "open"; exception.reopenedAt = now(); exception.activity.push(`${now()}: reopened - ${notes}`); shippingNotice(data, "Fulfillment exception", notes, "fulfillment_exception", exception.id, exception.severity); activity(data, "Fulfillment exception reopened", "fulfillment_exception", exception.id, notes); return write(data); }

export async function mutateFinance(action: string, input: Record<string, unknown>) {
 if (isProductionAuthEnabled()) {
  const rpcAction = action.includes("expense") ? "recordExpense" : action.includes("payout") ? "recordPayout" : action.includes("budget") || action === "yearly-template" ? "upsertBudget" : "reserveTax";
  return applyFinanceMutationRpc(rpcAction, input);
 }
 const data = await read(); ensureFinanceCollections(data); const time = now(); const key = typeof input.idempotencyKey === "string" ? input.idempotencyKey : id();
 if (data.transactions.some((transaction) => transaction.idempotencyKey === key)) return write(data);
 const note = (typeof input.notes === "string" && input.notes) || action;
 if (action === "create-expense" || action === "edit-expense" || action === "duplicate-expense") {
  const source = action === "edit-expense" ? data.expenses!.find((expense) => expense.id === input.id) : action === "duplicate-expense" ? data.expenses!.find((expense) => expense.id === input.id) : undefined;
  if ((action === "edit-expense" || action === "duplicate-expense") && !source) throw new Error("Expense not found.");
  const expense: Expense = action === "edit-expense" && source ? source : { id: id(), vendor: String(input.vendor || source?.vendor || "Manual vendor"), category: String(input.category || source?.category || "Software"), amount: Number(input.amount ?? source?.amount ?? 0), date: String(input.date || source?.date || time), recurring: (input.recurring as Expense["recurring"]) || source?.recurring || "none", taxDeductible: Boolean(input.taxDeductible ?? source?.taxDeductible ?? true), receiptStatus: (input.receiptStatus as Expense["receiptStatus"]) || source?.receiptStatus || "pending_attachment", supplierId: typeof input.supplierId === "string" ? input.supplierId : source?.supplierId, orderId: typeof input.orderId === "string" ? input.orderId : source?.orderId, notes: String(input.notes || source?.notes || ""), createdAt: time, audit: [] };
  expense.vendor = String(input.vendor || expense.vendor); expense.category = String(input.category || expense.category); expense.amount = Number(input.amount ?? expense.amount); expense.date = String(input.date || expense.date); expense.recurring = (input.recurring as Expense["recurring"]) || expense.recurring; expense.taxDeductible = Boolean(input.taxDeductible ?? expense.taxDeductible); expense.receiptStatus = (input.receiptStatus as Expense["receiptStatus"]) || expense.receiptStatus; expense.notes = String(input.notes || expense.notes || ""); expense.updatedAt = time; expense.audit = [...(expense.audit || []), `${time}: ${action.replaceAll("-", " ")}`];
  if (action !== "edit-expense") data.expenses!.unshift(expense);
  const transaction = { id: id(), type: "expense" as const, amount: -Math.abs(expense.amount), status: "cleared" as const, occurredAt: expense.date, expenseId: expense.id, sourceType: "expense" as const, sourceId: expense.id, sourceAccountId: "cash-main", destinationAccountId: "vendor", linkedObjectType: "expense" as const, linkedObjectId: expense.id, description: `${expense.vendor} ${expense.category}`, category: expense.category, idempotencyKey: key, audit: [`${time}: Created from ${action}.`] }; expense.transactionId ||= transaction.id; data.transactions.unshift(transaction); activity(data, `Finance ${action}`, "expense", expense.id, `${expense.vendor} ${expense.category} ${expense.amount}.`);
 } else if (action === "archive-expense" || action === "delete-expense") {
  const expense = data.expenses!.find((entry) => entry.id === input.id); if (!expense) throw new Error("Expense not found."); if (action === "archive-expense") expense.archivedAt = time; else expense.deletedAt = time; expense.audit = [...(expense.audit || []), `${time}: ${action.replaceAll("-", " ")}`]; activity(data, `Finance ${action}`, "expense", expense.id, note);
 } else if (action === "create-payout" || action === "import-payout" || action === "reconcile-payout") {
  const payout: Payout = { id: id(), marketplace: (input.marketplace as Marketplace) || "Depop", status: action === "reconcile-payout" ? "reconciled" : "received", expectedAmount: Number(input.expectedAmount || 0), actualAmount: Number(input.actualAmount ?? input.expectedAmount ?? 0), fees: Number(input.fees || 0), adjustments: Number(input.adjustments || 0), orderIds: data.orders.map((order) => order.id), transactionIds: [], expectedAt: String(input.expectedAt || time), receivedAt: time, externalPayoutId: String(input.externalPayoutId || `manual-${Date.now()}`), discrepancyAmount: Number(input.actualAmount ?? input.expectedAmount ?? 0) - Number(input.expectedAmount || 0), notes: String(input.notes || ""), audit: [`${time}: ${action.replaceAll("-", " ")}`], createdAt: time };
  if (payout.discrepancyAmount) payout.status = "discrepancy"; data.payouts!.unshift(payout);
  const transaction = { id: id(), type: "payout" as const, amount: payout.actualAmount || payout.expectedAmount, status: "cleared" as const, occurredAt: time, payoutId: payout.id, sourceType: "payout" as const, sourceId: payout.id, sourceAccountId: "marketplace-clearing", destinationAccountId: "cash-main", linkedObjectType: "payout" as const, linkedObjectId: payout.id, description: `${payout.marketplace} payout ${payout.externalPayoutId}`, category: "Payout", idempotencyKey: key, audit: [`${time}: Payout cash movement recorded.`] }; payout.transactionIds.push(transaction.id); data.transactions.unshift(transaction);
  data.payoutReconciliations!.unshift({ id: id(), payoutId: payout.id, status: payout.discrepancyAmount ? "discrepancy" : "matched", expectedAmount: payout.expectedAmount, actualAmount: payout.actualAmount || payout.expectedAmount, discrepancyAmount: payout.discrepancyAmount || 0, resolution: payout.discrepancyAmount ? undefined : "Matched exactly", includedOrderIds: payout.orderIds, feeTransactionIds: [], adjustmentTransactionIds: [], audit: [`${time}: Payout reconciliation created.`], createdAt: time }); activity(data, `Finance ${action}`, "payout", payout.id, `${payout.marketplace} payout reconciled.`);
 } else if (action === "resolve-payout" || action === "reopen-payout" || action === "archive-payout") {
  const payout = data.payouts!.find((entry) => entry.id === input.id); if (!payout) throw new Error("Payout not found."); if (action === "archive-payout") { payout.status = "archived"; payout.archivedAt = time; } const reconciliation = data.payoutReconciliations!.find((entry) => entry.payoutId === payout.id); if (reconciliation) { reconciliation.status = action === "reopen-payout" ? "reopened" : action === "resolve-payout" ? "resolved" : reconciliation.status; reconciliation.resolution = String(input.resolution || note); reconciliation.audit.push(`${time}: ${action.replaceAll("-", " ")}`); } payout.audit = [...(payout.audit || []), `${time}: ${action.replaceAll("-", " ")}`]; activity(data, `Finance ${action}`, "payout", payout.id, note);
 } else if (action === "create-budget" || action === "edit-budget" || action === "duplicate-budget" || action === "rollover-budget" || action === "yearly-template") {
  const source = data.budgets!.find((budget) => budget.id === input.id); if (input.id && !source && action !== "create-budget") throw new Error("Budget not found.");
  const budget: Budget = action === "edit-budget" && source ? source : { id: id(), month: String(input.month || new Date().toISOString().slice(0, 7)), category: String(input.category || source?.category || "Software"), amount: Number(input.amount ?? source?.amount ?? 100), actualAmount: Number(input.actualAmount ?? source?.actualAmount ?? 0), remainingAmount: 0, alertThreshold: Number(input.alertThreshold ?? source?.alertThreshold ?? 0.85), status: "on_track", templateName: action === "yearly-template" ? String(input.templateName || "Annual operating template") : source?.templateName, rolloverFromBudgetId: action === "rollover-budget" ? source?.id : undefined, audit: [], createdAt: time };
  budget.amount = Number(input.amount ?? budget.amount); budget.actualAmount = Number(input.actualAmount ?? budget.actualAmount); budget.remainingAmount = budget.amount - budget.actualAmount; budget.status = budget.actualAmount > budget.amount ? "overspent" : budget.actualAmount >= budget.amount * budget.alertThreshold ? "near_limit" : "on_track"; budget.updatedAt = time; budget.audit = [...(budget.audit || []), `${time}: ${action.replaceAll("-", " ")}`]; if (action !== "edit-budget") data.budgets!.unshift(budget); activity(data, `Finance ${action}`, "budget", budget.id, `${budget.category} ${budget.month}.`);
 } else if (action === "reserve-tax" || action === "release-tax" || action === "adjust-tax") {
  const movement: TaxReserveMovement = { id: id(), amount: action === "release-tax" ? -Math.abs(Number(input.amount || 0)) : Number(input.amount || 0), basisAmount: Number(input.basisAmount || input.amount || 0), rate: Number(input.rate || 0.18), sourceType: "manual", sourceId: String(input.sourceId || id()), status: action === "release-tax" ? "released" : action === "adjust-tax" ? "adjusted" : "reserved", createdAt: time, notes: String(input.notes || ""), audit: [`${time}: ${action.replaceAll("-", " ")}`] }; data.taxReserveMovements!.unshift(movement); data.transactions.unshift({ id: id(), type: "tax_reserve_movement", amount: -movement.amount, status: "cleared", occurredAt: time, sourceType: "tax_reserve", sourceId: movement.id, sourceAccountId: "cash-main", destinationAccountId: "tax-reserve", linkedObjectType: "tax_reserve", linkedObjectId: movement.id, description: `Tax reserve ${movement.status}`, category: "Tax reserve", idempotencyKey: key, audit: [`${time}: Tax reserve movement recorded.`] }); activity(data, `Finance ${action}`, "tax_reserve", movement.id, note);
 } else if (action === "edit-allocation" || action === "simulate-allocation" || action === "approve-allocation") {
  const target = String(input.target || "inventory") as ReinvestmentAllocation["target"]; let allocation = data.reinvestmentAllocations!.find((entry) => entry.target === target); if (!allocation) { allocation = { id: id(), target, percentage: Number(input.percentage || 10), amount: 0, basis: "deployable_cash", approvalHistory: [], createdAt: time }; data.reinvestmentAllocations!.push(allocation); } allocation.percentage = Number(input.percentage ?? allocation.percentage); allocation.amount = Number(input.amount ?? allocation.amount); allocation.recommendation = action === "simulate-allocation" ? `Scenario recommends ${allocation.percentage}% toward ${target.replaceAll("_", " ")}.` : allocation.recommendation; if (action === "approve-allocation") { allocation.approvedAt = time; allocation.approvalHistory = [...(allocation.approvalHistory || []), `${time}: approved ${allocation.percentage}%`]; } allocation.updatedAt = time; activity(data, `Finance ${action}`, "reinvestment", allocation.id, `${target} ${allocation.percentage}%.`);
 } else if (action === "configure-forecast") {
  const forecast: Forecast = data.forecasts![0] || { id: id(), period: new Date().toISOString().slice(0, 7), revenue: 0, contributionProfit: 0, operatingProfit: 0, cash: 0, inventoryPurchasing: 0, payouts: 0, stockouts: 0, reorderCosts: 0, confidence: 0.5, assumptions: [], createdAt: time }; if (!data.forecasts!.length) data.forecasts!.push(forecast); forecast.scenarios = [{ id: "best", name: "best", revenueMultiplier: 1.25, expenseMultiplier: 0.9, confidence: 0.38, assumptions: ["Higher conversion", "Lower fee leakage"] }, { id: "expected", name: "expected", revenueMultiplier: Number(input.revenueMultiplier || 1), expenseMultiplier: Number(input.expenseMultiplier || 1), confidence: 0.62, assumptions: [String(input.assumption || "Current trend continues")] }, { id: "worst", name: "worst", revenueMultiplier: 0.75, expenseMultiplier: 1.15, confidence: 0.41, assumptions: ["Lower sales velocity", "Higher shipping and fees"] }]; forecast.selectedScenarioId = String(input.scenario || "expected"); forecast.updatedAt = time; activity(data, "Finance configure forecast", "forecast", forecast.id, forecast.selectedScenarioId);
 } else {
  throw new Error("Unsupported finance action.");
 }
 return write(data);
}
export function snapshot(data: OperatingData) { const completed = data.orders.filter((order) => !["draft", "cancelled", "refunded"].includes(order.status)); const profits = completed.map((order) => orderProfit(order, data.variants)); const revenue = profits.reduce((total, value) => total + value.revenue, 0); const grossProfit = profits.reduce((total, value) => total + value.grossProfit, 0); const netProfit = profits.reduce((total, value) => total + value.netProfit, 0); const units = completed.reduce((total, order) => total + order.items.reduce((lineTotal, item) => lineTotal + item.quantity, 0), 0); const unitsOnHand = data.balances.reduce((total, balance) => total + balance.onHand, 0); const readyToShip = data.orders.filter((order) => ["paid", "confirmed", "inventory_reserved", "ready_to_pack", "packed", "label_purchased", "ready_to_ship"].includes(order.status)); return { data, metrics: { revenue, grossProfit, netProfit, margin: revenue ? netProfit / revenue * 100 : 0, orders: completed.length, units, averageOrderValue: completed.length ? revenue / completed.length : 0, cash: availableCash(data.transactions), inventoryValue: inventoryValue(data.balances, data.variants), unitsOnHand, availableUnits: data.balances.reduce((total, balance) => total + availableUnits(balance), 0), readyToShip: readyToShip.length, incoming: data.balances.reduce((total, balance) => total + balance.incoming, 0) }, attention: data.notices.filter((notice) => !notice.resolved), reorders: data.variants.map((variant) => ({ variant, quantity: reorderSuggestion(data.balances.find((balance) => balance.variantId === variant.id), variant) })).filter((entry) => entry.quantity > 0) }; }
