import "server-only";
import fs from "fs/promises";
import path from "path";
import type { Marketplace, OperatingData, Order, OrderStatus, StockBalance } from "@/domain/business";
import { availableCash, availableUnits, inventoryValue, orderProfit, reorderSuggestion } from "@/lib/business-calculations";
import type { Opportunity as LegacyOpportunity } from "@/types/opportunity";
import { isProductionAuthEnabled } from "@/lib/env";
import { applyInventoryMutationRpc, applyInventoryTransferRpc, applyOrderTransition, applyParcelReceipt, readNormalizedOperatingData, writeNormalizedOperatingData } from "@/services/operating-system/supabase-repository";
import { advanceOrder, cancelOrderItems, createOrderRefund, receiveOrderReturn, receiveParcelItems } from "@/lib/operational-workflows";
import { adjustStock, assignLocation, markDamaged, markLost, moveToQuarantine, recordFound, reconcileCycleCount, releaseFromQuarantine, transferStock } from "@/lib/inventory-actions";
import { applyCreateOrderRpc } from "@/services/operating-system/supabase-repository";
import { applyOrderRefundRpc, applyReturnReceiptRpc } from "@/services/operating-system/supabase-repository";

const file = path.join(process.cwd(), ".faust", "operating-system.json");
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const empty = (): OperatingData => ({ version: 1, mode: "empty", products: [], variants: [], locations: [], balances: [], stockMovements: [], suppliers: [], purchaseOrders: [], parcels: [], listings: [], customers: [], orders: [], transactions: [], tasks: [], notices: [], insights: [], activity: [], updatedAt: now() });
async function readLocal(): Promise<OperatingData> { try { return JSON.parse(await fs.readFile(file, "utf8")) as OperatingData; } catch (error: unknown) { if (typeof error === "object" && error && "code" in error && error.code === "ENOENT") return empty(); throw error; } }
async function read(): Promise<OperatingData> { return isProductionAuthEnabled() ? readNormalizedOperatingData() : readLocal(); }
async function write(data: OperatingData) { data.updatedAt = now(); if (isProductionAuthEnabled()) return writeNormalizedOperatingData(data); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, JSON.stringify(data, null, 2)); return data; }
function activity(data: OperatingData, action: string, entityType: string, entityId: string, detail: string) { data.activity.unshift({ id: id(), action, entityType, entityId, detail, createdAt: now() }); }

export function developmentDemo(): OperatingData {
 const time = now(); const supplierId = id(), productId = id(), variantId = id(), locationId = id(), customerId = id(), listingId = id(), orderId = id(), poId = id(), parcelId = id(), poItemId = id();
 const order: Order = { id: orderId, number: "FO-1042", marketplace: "Depop", customerId, items: [{ id: id(), productId, variantId, listingId, title: "Vintage wash heavyweight hoodie - charcoal L", quantity: 1, unitSellingPrice: 86, discountAllocation: 0, taxAllocation: 0, feeAllocation: 0, unitCost: 31.7 }], shippingCharged: 8, shippingCost: 7.45, marketplaceFee: 9.4, paymentFee: 2.82, taxCollected: 0, status: "ready_to_ship", orderedAt: time, shipBy: new Date(Date.now() + 86400000).toISOString() };
 return { version: 1, mode: "development_demo", updatedAt: time,
  suppliers: [{ id: supplierId, name: "North Star Trading", contact: "Li Wei", email: "orders@example.test", sourcePlatform: "Superbuy", leadDays: 12, rating: 4.6, status: "active" }],
  products: [{ id: productId, title: "Vintage wash heavyweight hoodie", brand: "Unbranded", category: "Streetwear", tags: ["hoodie", "vintage"], supplierId, sourceUrl: "https://example.test/product", status: "active", createdAt: time, updatedAt: time }],
  variants: [{ id: variantId, productId, sku: "FST-HOOD-001", title: "Charcoal / L", condition: "New with tags", landedUnitCost: 31.7, defaultSalePrice: 86, weightOz: 22, reorderPoint: 2, reorderQuantity: 8, active: true }],
  locations: [{ id: locationId, label: "VA-01 / A / 04 / 03", warehouse: "Virginia", zone: "A", aisle: "04", bin: "03" }],
  balances: [{ id: id(), variantId, locationId, onHand: 3, reserved: 1, incoming: 6, damaged: 0, returned: 0, lost: 0, quarantined: 0 }],
  stockMovements: [{ id: id(), variantId, quantity: 4, type: "purchase_received", referenceType: "purchase_order", referenceId: poId, note: "Received at VA-01", createdAt: time }, { id: id(), variantId, quantity: -1, type: "order_reservation", referenceType: "order", referenceId: orderId, note: "Reserved for FO-1042", createdAt: time }],
  purchaseOrders: [{ id: poId, supplierId, reference: "PO-2008", status: "ordered", orderedAt: time, expectedAt: new Date(Date.now() + 5 * 86400000).toISOString(), totalCost: 190.2, itemCount: 6, items: [{ id: poItemId, variantId, expectedQuantity: 6, receivedQuantity: 0, unitCost: 31.7 }], parcelId }],
  parcels: [{ id: parcelId, trackingNumber: "DEMO-17TRACK-1042", carrier: "17TRACK manual", status: "in_transit", origin: "Guangzhou, CN", destination: "Virginia, US", estimatedArrival: new Date(Date.now() + 5 * 86400000).toISOString(), purchaseOrderId: poId, items: [{ id: id(), variantId, purchaseOrderItemId: poItemId, expectedQuantity: 6, receivedQuantity: 0 }], events: [{ label: "Departed origin facility", timestamp: time, location: "Guangzhou, CN" }] }],
  listings: [{ id: listingId, variantId, marketplace: "Depop", title: "Vintage wash heavyweight hoodie - charcoal L", price: 86, quantity: 2, status: "active", syncState: "manual", views: 43, likes: 7, createdAt: time }],
  customers: [{ id: customerId, name: "Jordan Williams", email: "jordan@example.test", city: "Richmond", state: "VA", orderCount: 1, lifetimeValue: 94, issueCount: 0 }], orders: [order],
  transactions: [{ id: id(), type: "payout", amount: 81.18, status: "pending", occurredAt: time, orderId, description: "Depop payout for FO-1042", category: "Marketplace payout" }, { id: id(), type: "inventory", amount: -190.2, status: "cleared", occurredAt: time, purchaseOrderId: poId, description: "PO-2008 supplier payment", category: "Inventory" }],
  tasks: [{ id: id(), title: "Pack FO-1042 before shipping deadline", status: "open", priority: "critical", dueAt: order.shipBy, entityType: "order", entityId: orderId, createdAt: time }],
  notices: [{ id: id(), severity: "critical", title: "1 order needs shipment", detail: "FO-1042 has a ship-by deadline tomorrow.", actionLabel: "Open fulfillment", href: "/shipping", createdAt: time }, { id: id(), severity: "warning", title: "Reorder point reached", detail: "FST-HOOD-001 has two available units.", actionLabel: "Create purchase order", href: "/purchasing", createdAt: time }],
  insights: [{ id: id(), type: "profit", title: "Healthy margin on active order", summary: "FO-1042 is expected to remain profitable after known fees and shipping.", evidence: "Based on $94.00 collected, $31.70 landed cost, $19.67 known fees.", actionLabel: "Review order", href: "/orders", createdAt: time }, { id: id(), type: "inventory", title: "Inventory is approaching reorder point", summary: "Order six more units only after reviewing inbound stock.", evidence: "2 available, 6 incoming, reorder point is 2.", actionLabel: "Review purchasing", href: "/purchasing", createdAt: time }],
  activity: [{ id: id(), action: "Order reserved inventory", entityType: "order", entityId: orderId, detail: "FO-1042 reserved 1 × FST-HOOD-001.", createdAt: time }]
 };
}

export async function getOperatingData() { return read(); }
export async function resetOperatingData(mode: "empty" | "development_demo") { return write(mode === "development_demo" ? developmentDemo() : empty()); }
/** Converts a reviewed sourcing opportunity into connected catalog, stock, and listing-draft records. */
export async function convertOpportunity(opportunity: LegacyOpportunity) {
 const data = await read(); const sourceUrl = opportunity.product.sourcing.superbuyUrl; let product = data.products.find((entry) => entry.sourceUrl === sourceUrl);
 if (product) return write(data);
 if (data.mode === "empty") data.mode = "local";
 const supplierName = opportunity.product.supplier.storeName || opportunity.product.supplier.name || "Unassigned supplier";
 let supplier = data.suppliers.find((entry) => entry.name.toLowerCase() === supplierName.toLowerCase());
 if (!supplier) { supplier = { id: id(), name: supplierName, sourcePlatform: "Superbuy", status: "active", notes: "Created from saved opportunity." }; data.suppliers.push(supplier); }
 const createdAt = now(); product = { id: id(), title: opportunity.product.name, category: opportunity.product.category || "Uncategorized", tags: opportunity.listing.tags || [], supplierId: supplier.id, sourceUrl, image: opportunity.product.media.images[0], status: "draft", createdAt, updatedAt: createdAt }; data.products.push(product);
 const unitCost = Object.values(opportunity.costs).reduce((sum, line) => sum + (line.amount || 0), 0); const variant = { id: id(), productId: product.id, sku: `FST-${product.id.slice(0, 6).toUpperCase()}`, title: opportunity.product.variants[0]?.name || "Default variant", condition: "New", landedUnitCost: unitCost, defaultSalePrice: opportunity.salePrice, weightOz: Number.parseFloat(opportunity.product.shippingWeight || opportunity.product.weight || "") || undefined, reorderPoint: 1, reorderQuantity: 5, active: true }; data.variants.push(variant);
 const balance: StockBalance = { id: id(), variantId: variant.id, onHand: 0, reserved: 0, incoming: 0, damaged: 0, returned: 0, lost: 0, quarantined: 0 }; data.balances.push(balance);
 const marketplace = opportunity.listing.marketplaceId === "depop" ? "Depop" : opportunity.listing.marketplaceId === "ebay" ? "eBay" : opportunity.listing.marketplaceId === "etsy" ? "Etsy" : opportunity.listing.marketplaceId === "mercari" ? "Mercari" : opportunity.listing.marketplaceId === "poshmark" ? "Poshmark" : "Manual";
 data.listings.push({ id: id(), variantId: variant.id, marketplace, title: opportunity.listing.title || product.title, price: opportunity.salePrice, quantity: 0, status: "draft", syncState: "manual", createdAt });
 activity(data, "Opportunity converted to product", "product", product.id, `${product.title} is now a catalog product with a listing draft. Create a purchase order before receiving stock.`); return write(data);
}
export async function transitionOrder(idValue: string, status: OrderStatus) { if (isProductionAuthEnabled()) return applyOrderTransition(idValue, status); const data = await read(); const order = data.orders.find((entry) => entry.id === idValue); if (!order) throw new Error("Order not found."); const result = advanceOrder(order, data.balances, status); Object.assign(order, result.order); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, `Order marked ${status.replaceAll("_", " ")}`, "order", order.id, `${order.number} status updated.`); return write(data); }
export type ManualOrderInput = { number?: string; marketplace: Marketplace; customer: { name: string; email?: string; city?: string; state?: string }; items: { productId?: string; variantId: string; listingId?: string; title?: string; quantity: number; unitSellingPrice: number; discountAllocation?: number; taxAllocation?: number; marketplaceFeeAllocation?: number; paymentFeeAllocation?: number; unitCost?: number }[]; shippingCharged?: number; shippingCost?: number; marketplaceFee?: number; paymentFee?: number; taxCollected?: number; shipBy?: string; notes?: string; idempotencyKey?: string };
export async function createOrder(input: ManualOrderInput) { if (isProductionAuthEnabled()) throw new Error("Production order RPC setup is required before creating orders."); const data = await read(); if (!input.items.length) throw new Error("An order must contain at least one line item."); if (input.idempotencyKey && data.orders.some((order) => order.idempotencyKey === input.idempotencyKey)) return data; let customer = input.customer.email ? data.customers.find((entry) => entry.email?.toLowerCase() === input.customer.email?.toLowerCase()) : undefined; if (!customer) { customer = { id: id(), name: input.customer.name, email: input.customer.email, city: input.customer.city, state: input.customer.state, orderCount: 0, lifetimeValue: 0, issueCount: 0 }; data.customers.push(customer); } const orderId = id(); const order: Order = { id: orderId, number: input.number || `FO-${String(data.orders.length + 1001).padStart(4, "0")}`, marketplace: input.marketplace, customerId: customer.id, items: input.items.map((item) => { const variant = data.variants.find((entry) => entry.id === item.variantId); if (!variant || !Number.isInteger(item.quantity) || item.quantity <= 0) throw new Error("Every order item needs a valid variant and positive whole quantity."); return { id: id(), productId: item.productId || variant.productId, variantId: item.variantId, listingId: item.listingId, title: item.title || variant.title, quantity: item.quantity, unitSellingPrice: item.unitSellingPrice, discountAllocation: item.discountAllocation || 0, taxAllocation: item.taxAllocation || 0, marketplaceFeeAllocation: item.marketplaceFeeAllocation || 0, paymentFeeAllocation: item.paymentFeeAllocation || 0, feeAllocation: item.marketplaceFeeAllocation || 0, unitCost: item.unitCost ?? variant.landedUnitCost, fulfillmentState: "unfulfilled", returnState: "none", refundState: "none" }; }), shippingCharged: input.shippingCharged || 0, shippingCost: input.shippingCost || 0, marketplaceFee: input.marketplaceFee || 0, paymentFee: input.paymentFee || 0, taxCollected: input.taxCollected || 0, status: "pending_payment", orderedAt: now(), shipBy: input.shipBy, notes: input.notes, idempotencyKey: input.idempotencyKey, statusEvents: [{ id: id(), toStatus: "pending_payment", detail: "Manual order created", createdAt: now() }] }; data.orders.unshift(order); customer.orderCount += 1; customer.lifetimeValue += order.items.reduce((sum, item) => sum + item.unitSellingPrice * item.quantity - item.discountAllocation, 0) + order.shippingCharged; activity(data, "Order created", "order", order.id, `${order.number} created with ${order.items.length} line item(s).`); return write(data); }
export const importOrder = createOrder;
/** Production boundary for manual and external imports; local mode preserves the JSON fallback. */
export async function createOrderTargeted(input: ManualOrderInput) { return isProductionAuthEnabled() ? applyCreateOrderRpc(input) : createOrder(input); }
export async function createRefundTargeted(orderId: string, input: Parameters<typeof createOrderRefund>[1] & { idempotencyKey?: string }) { return isProductionAuthEnabled() ? applyOrderRefundRpc(orderId, input) : createRefund(orderId, input); }
export async function receiveReturnTargeted(orderId: string, returnId: string, dispositions: Parameters<typeof receiveOrderReturn>[3], idempotencyKey?: string) { return isProductionAuthEnabled() ? applyReturnReceiptRpc(returnId, dispositions, idempotencyKey) : receiveReturn(orderId, returnId, dispositions); }
export async function reserveOrderInventory(orderId: string) { return transitionOrder(orderId, "reserved"); }
export async function cancelOrder(orderId: string, reason: string) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = advanceOrder(order, data.balances, "cancelled"); Object.assign(order, result.order); order.notes = [order.notes, `Cancellation: ${reason}`].filter(Boolean).join("\n"); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement, note: reason }))); activity(data, "Order cancelled", "order", order.id, reason); return write(data); }
export async function partiallyCancelOrder(orderId: string, lines: { itemId: string; quantity: number }[], reason: string) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = cancelOrderItems(order, data.balances, lines, reason); Object.assign(order, result.order); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, "Order partially cancelled", "order", order.id, reason); return write(data); }
export async function createRefund(orderId: string, input: Parameters<typeof createOrderRefund>[1]) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = createOrderRefund(order, input); Object.assign(order, result.order); data.transactions.unshift({ id: id(), type: "refund", amount: -input.amount, status: "cleared", occurredAt: now(), orderId, description: `Refund for ${order.number}: ${input.reason}`, category: "Refund" }); activity(data, "Order refund created", "order", order.id, `${input.reason}: $${input.amount.toFixed(2)}`); return write(data); }
export async function createReturn(orderId: string, input: { reason: string; items: { orderItemId: string; quantity: number }[]; trackingNumber?: string }) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const transition = advanceOrder(order, data.balances, "return_requested"); const returnRecord = { id: id(), status: "requested" as const, reason: input.reason, trackingNumber: input.trackingNumber, items: input.items, createdAt: now() }; Object.assign(order, { ...transition.order, returns: [...(order.returns || []), returnRecord] }); activity(data, "Return requested", "order", order.id, input.reason); return write(data); }
export async function receiveReturn(orderId: string, returnId: string, dispositions: Parameters<typeof receiveOrderReturn>[3]) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); const result = receiveOrderReturn(order, data.balances, returnId, dispositions); Object.assign(order, result.order); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, "Return received", "order", order.id, `Return ${returnId} received.`); return write(data); }
export async function updateOrderCustomer(orderId: string, customerId: string) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); const customer = data.customers.find((entry) => entry.id === customerId); if (!order || !customer) throw new Error("Order or customer not found."); order.customerId = customerId; activity(data, "Order customer updated", "order", order.id, customer.name); return write(data); }
export async function updateShippingAddress(orderId: string, address: NonNullable<Order["shippingAddress"]>) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); order.shippingAddress = address; activity(data, "Shipping address updated", "order", order.id, `${address.line1}, ${address.city}`); return write(data); }
export async function releaseOrderReservation(orderId: string, reason: string) { return cancelOrder(orderId, reason); }
export const markReadyToPack = (orderId: string) => transitionOrder(orderId, "ready_to_pack");
export const markPacked = (orderId: string) => transitionOrder(orderId, "packed");
export async function attachShippingLabel(orderId: string, input: { trackingNumber: string; labelUrl?: string }) { const data = await read(); const order = data.orders.find((entry) => entry.id === orderId); if (!order) throw new Error("Order not found."); order.trackingNumber = input.trackingNumber; order.shippingLabelUrl = input.labelUrl; activity(data, "Shipping label attached", "order", order.id, input.trackingNumber); return write(data); }
export const markReadyToShip = (orderId: string) => transitionOrder(orderId, "ready_to_ship");
export const shipOrder = (orderId: string) => transitionOrder(orderId, "shipped");
export const markInTransit = (orderId: string) => transitionOrder(orderId, "in_transit");
export const markDelivered = (orderId: string) => transitionOrder(orderId, "delivered");
export const closeOrder = (orderId: string) => transitionOrder(orderId, "closed");
export async function receiveParcel(idValue: string) { if (isProductionAuthEnabled()) return applyParcelReceipt(idValue); const data = await read(); const parcel = data.parcels.find((entry) => entry.id === idValue); if (!parcel) throw new Error("Parcel not found."); const po = data.purchaseOrders.find((entry) => entry.id === parcel.purchaseOrderId); const result = receiveParcelItems(parcel, po, data.balances); Object.assign(parcel, result.parcel); if (po && result.purchaseOrder) Object.assign(po, result.purchaseOrder); data.balances.splice(0, data.balances.length, ...result.balances); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement }))); activity(data, "Parcel received", "parcel", parcel.id, `${parcel.trackingNumber} was received into its linked variant balances.`); return write(data); }
export async function adjustInventory(balanceId: string, quantity: number, reason: string, idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryMutationRpc({ balanceId, action: "adjust", quantity, reason, idempotencyKey })).data; const data = await read(); const balance = data.balances.find((entry) => entry.id === balanceId); if (!balance) throw new Error("Inventory balance not found."); const result = adjustStock(balance, quantity, reason); Object.assign(balance, result.balance); data.stockMovements.unshift({ id: id(), createdAt: now(), ...result.movement }); activity(data, "Inventory adjusted", "inventory_balance", balance.id, reason); return write(data); }
export async function transferInventory(sourceBalanceId: string, destinationBalanceId: string, quantity: number, notes = "Inventory transfer", idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryTransferRpc({ sourceBalanceId, destinationBalanceId, quantity, reason: notes, idempotencyKey })).data; const data = await read(); const source = data.balances.find((entry) => entry.id === sourceBalanceId); const destination = data.balances.find((entry) => entry.id === destinationBalanceId); if (!source || !destination) throw new Error("Both source and destination balances are required."); const result = transferStock(source, destination, quantity); Object.assign(source, result.source); Object.assign(destination, result.destination); data.stockMovements.unshift(...result.movements.map((movement) => ({ id: id(), createdAt: now(), ...movement, note: notes }))); activity(data, "Inventory transferred", "inventory_balance", source.id, notes); return write(data); }
export async function reconcileInventoryCount(balanceId: string, countedQuantity: number, idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryMutationRpc({ balanceId, action: "cycle_count", quantity: countedQuantity, reason: "Approved cycle count", idempotencyKey })).data; const data = await read(); const balance = data.balances.find((entry) => entry.id === balanceId); if (!balance) throw new Error("Inventory balance not found."); const result = reconcileCycleCount(balance, countedQuantity); Object.assign(balance, result.balance); if (result.movement) data.stockMovements.unshift({ id: id(), createdAt: now(), ...result.movement }); activity(data, "Cycle count approved", "inventory_balance", balance.id, `Counted ${countedQuantity} units.`); return write(data); }
async function inventoryStateMutation(balanceId: string, action: "damage" | "quarantine" | "release" | "lost" | "found" | "location", quantity: number, reason: string, locationId?: string, idempotencyKey?: string) { if (isProductionAuthEnabled()) return (await applyInventoryMutationRpc({ balanceId, action: action === "release" ? "release_quarantine" : action, quantity, reason, destinationLocationId: locationId, idempotencyKey })).data; const data = await read(); const balance = data.balances.find((entry) => entry.id === balanceId); if (!balance) throw new Error("Inventory balance not found."); const result = action === "damage" ? markDamaged(balance, quantity, reason) : action === "quarantine" ? moveToQuarantine(balance, quantity, reason) : action === "release" ? releaseFromQuarantine(balance, quantity, reason) : action === "lost" ? markLost(balance, quantity, reason) : action === "found" ? recordFound(balance, quantity, reason) : assignLocation(balance, locationId || ""); Object.assign(balance, result.balance); data.stockMovements.unshift({ id: id(), createdAt: now(), ...result.movement }); activity(data, `Inventory ${action}`, "inventory_balance", balance.id, reason); return write(data); }
export const markInventoryDamaged = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "damage", quantity, reason, undefined, idempotencyKey);
export const moveInventoryToQuarantine = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "quarantine", quantity, reason, undefined, idempotencyKey);
export const releaseInventoryFromQuarantine = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "release", quantity, reason, undefined, idempotencyKey);
export const markInventoryLost = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "lost", quantity, reason, undefined, idempotencyKey);
export const recordInventoryFound = (balanceId: string, quantity: number, reason: string, idempotencyKey?: string) => inventoryStateMutation(balanceId, "found", quantity, reason, undefined, idempotencyKey);
export const assignInventoryLocation = (balanceId: string, locationId: string, reason = "Inventory location assigned", idempotencyKey?: string) => inventoryStateMutation(balanceId, "location", 0, reason, locationId, idempotencyKey);
export function snapshot(data: OperatingData) { const completed = data.orders.filter((order) => !["draft", "cancelled", "refunded"].includes(order.status)); const profits = completed.map((order) => orderProfit(order, data.variants)); const revenue = profits.reduce((total, value) => total + value.revenue, 0); const grossProfit = profits.reduce((total, value) => total + value.grossProfit, 0); const netProfit = profits.reduce((total, value) => total + value.netProfit, 0); const units = completed.reduce((total, order) => total + order.items.reduce((lineTotal, item) => lineTotal + item.quantity, 0), 0); const unitsOnHand = data.balances.reduce((total, balance) => total + balance.onHand, 0); const readyToShip = data.orders.filter((order) => ["paid", "confirmed", "inventory_reserved", "ready_to_pack", "packed", "label_purchased", "ready_to_ship"].includes(order.status)); return { data, metrics: { revenue, grossProfit, netProfit, margin: revenue ? netProfit / revenue * 100 : 0, orders: completed.length, units, averageOrderValue: completed.length ? revenue / completed.length : 0, cash: availableCash(data.transactions), inventoryValue: inventoryValue(data.balances, data.variants), unitsOnHand, availableUnits: data.balances.reduce((total, balance) => total + availableUnits(balance), 0), readyToShip: readyToShip.length, incoming: data.balances.reduce((total, balance) => total + balance.incoming, 0) }, attention: data.notices.filter((notice) => !notice.resolved), reorders: data.variants.map((variant) => ({ variant, quantity: reorderSuggestion(data.balances.find((balance) => balance.variantId === variant.id), variant) })).filter((entry) => entry.quantity > 0) }; }
