import { z } from "zod";

export const authCredentialsSchema = z.object({ email: z.string().trim().email().max(320), password: z.string().min(8).max(256) });
export const passwordRecoverySchema = z.object({ email: z.string().trim().email().max(320) });
export const passwordUpdateSchema = z.object({ password: z.string().min(8).max(256), confirmPassword: z.string().min(8).max(256) }).refine((value) => value.password === value.confirmPassword, { message: "Passwords do not match.", path: ["confirmPassword"] });
export const businessInputSchema = z.object({ name: z.string().trim().min(1).max(120), currency: z.string().regex(/^[A-Za-z]{3}$/).default("USD"), timezone: z.string().trim().min(1).max(100).default("America/New_York") });
export const orderStatusSchema = z.enum(["draft", "pending_payment", "paid", "confirmed", "inventory_reserved", "ready_to_pack", "packed", "label_purchased", "ready_to_ship", "shipped", "in_transit", "delivered", "closed", "cancelled", "return_requested", "return_in_transit", "returned", "refunded"]);
export const operatingActionSchema = z.discriminatedUnion("action", [z.object({ action: z.literal("reset"), mode: z.enum(["empty", "development_demo"]) }), z.object({ action: z.literal("transition-order"), id: z.string().uuid(), status: orderStatusSchema }), z.object({ action: z.literal("receive-parcel"), id: z.string().uuid() })]);
export const settingsInputSchema = z.object({ currency: z.string().regex(/^[A-Za-z]{3}$/).optional(), warehouseName: z.string().trim().max(120).optional(), targetMargin: z.coerce.number().min(0).max(100).optional(), defaultMarketplace: z.string().trim().max(50).optional() });
export const inventoryMutationSchema = z.object({ quantity: z.coerce.number().int().min(0).optional(), status: z.enum(["planned", "available", "reserved", "sold", "damaged", "lost"]).optional(), warehouse: z.string().trim().max(120).optional(), shelf: z.string().trim().max(120).optional(), bin: z.string().trim().max(120).optional() }).refine((value) => Object.keys(value).length > 0, "At least one inventory field is required.");
const idempotencyKey = z.string().uuid().optional();
export const inventoryAdjustSchema = z.object({ balanceId: z.string().uuid(), quantity: z.coerce.number().int().refine((value) => value !== 0), reason: z.string().trim().min(2).max(500), notes: z.string().trim().max(1000).optional(), relatedEntityId: z.string().uuid().optional(), idempotencyKey });
export const inventoryTransferSchema = z.object({ sourceBalanceId: z.string().uuid(), destinationBalanceId: z.string().uuid(), quantity: z.coerce.number().int().positive(), notes: z.string().trim().max(500).optional(), idempotencyKey });
export const inventoryCycleCountSchema = z.object({ balanceId: z.string().uuid(), countedQuantity: z.coerce.number().int().min(0), idempotencyKey });
export const inventoryDamageSchema = z.object({ balanceId: z.string().uuid(), quantity: z.coerce.number().int().positive(), action: z.enum(["damage", "quarantine", "release_quarantine", "lost", "found"]), reason: z.string().trim().min(2).max(500), notes: z.string().trim().max(1000).optional(), relatedEntityId: z.string().uuid().optional(), idempotencyKey });
export const inventoryLocationSchema = z.object({ balanceId: z.string().uuid(), locationId: z.string().uuid(), reason: z.string().trim().min(2).max(500).default("Inventory location assigned"), notes: z.string().trim().max(1000).optional(), idempotencyKey });
const orderLineSchema = z.object({ productId: z.string().uuid().optional(), variantId: z.string().uuid(), listingId: z.string().uuid().optional(), title: z.string().trim().min(1).max(300).optional(), quantity: z.coerce.number().int().positive(), unitSellingPrice: z.coerce.number().nonnegative(), discountAllocation: z.coerce.number().nonnegative().optional(), taxAllocation: z.coerce.number().nonnegative().optional(), marketplaceFeeAllocation: z.coerce.number().nonnegative().optional(), paymentFeeAllocation: z.coerce.number().nonnegative().optional(), unitCost: z.coerce.number().nonnegative().optional() });
export const manualOrderSchema = z.object({ number: z.string().trim().max(100).optional(), marketplace: z.enum(["Depop", "eBay", "Etsy", "Mercari", "Poshmark", "Manual"]), customer: z.object({ name: z.string().trim().min(1).max(200), email: z.string().email().optional(), city: z.string().trim().max(120).optional(), state: z.string().trim().max(120).optional() }), items: z.array(orderLineSchema).min(1), shippingCharged: z.coerce.number().nonnegative().optional(), shippingCost: z.coerce.number().nonnegative().optional(), marketplaceFee: z.coerce.number().nonnegative().optional(), paymentFee: z.coerce.number().nonnegative().optional(), taxCollected: z.coerce.number().nonnegative().optional(), shipBy: z.string().datetime().optional(), notes: z.string().trim().max(2000).optional(), idempotencyKey });
export const orderActionSchema = z.discriminatedUnion("action", [z.object({ action: z.literal("reserve") }), z.object({ action: z.literal("cancel"), reason: z.string().trim().min(2).max(500) }), z.object({ action: z.literal("partial-cancel"), reason: z.string().trim().min(2).max(500), lines: z.array(z.object({ itemId: z.string().uuid(), quantity: z.coerce.number().int().positive() })).min(1) }), z.object({ action: z.literal("ready-to-pack") }), z.object({ action: z.literal("packed") }), z.object({ action: z.literal("attach-label"), trackingNumber: z.string().trim().min(2).max(200), labelUrl: z.string().url().optional() }), z.object({ action: z.literal("ready-to-ship") }), z.object({ action: z.literal("ship") }), z.object({ action: z.literal("in-transit") }), z.object({ action: z.literal("delivered") }), z.object({ action: z.literal("close") }), z.object({ action: z.literal("refund"), amount: z.coerce.number().positive(), reason: z.string().trim().min(2).max(500), itemId: z.string().uuid().optional(), quantity: z.coerce.number().int().positive().optional(), externalRefundId: z.string().trim().max(200).optional() }), z.object({ action: z.literal("return"), reason: z.string().trim().min(2).max(500), trackingNumber: z.string().trim().max(200).optional(), items: z.array(z.object({ orderItemId: z.string().uuid(), quantity: z.coerce.number().int().positive() })).min(1) }), z.object({ action: z.literal("receive-return"), returnId: z.string().uuid(), dispositions: z.array(z.object({ itemId: z.string().uuid(), quantity: z.coerce.number().int().positive(), disposition: z.enum(["available", "damaged", "quarantine"]) })).min(1) }) ]);
export const importBatchConfirmSchema = z.object({ batchId: z.string().uuid(), idempotencyKey: z.string().uuid().optional() });
export const orderImportResolutionSchema = z.object({ reviewId: z.string().uuid(), action: z.enum(["link_variant", "link_listing", "create_variant", "non_inventory", "ignore", "cancel", "reopen"]), variantId: z.string().uuid().optional(), listingId: z.string().uuid().optional(), productTitle: z.string().trim().max(200).optional(), variantSku: z.string().trim().max(120).optional() });
export const orderImportBatchActionSchema = z.discriminatedUnion("action", [z.object({ action: z.literal("confirm"), batchId: z.string().uuid() }), z.object({ action: z.literal("retry"), batchId: z.string().uuid() }), z.object({ action: z.literal("reopen"), batchId: z.string().uuid() }), z.object({ action: z.literal("archive"), batchId: z.string().uuid() })]);
export const savedOrderViewActionSchema = z.discriminatedUnion("action", [z.object({ action: z.literal("create"), name: z.string().trim().min(1).max(80), query: z.string().trim().max(120).optional(), marketplace: z.enum(["Depop", "eBay", "Etsy", "Mercari", "Poshmark", "Manual"]).optional(), status: orderStatusSchema.optional(), isDefault: z.boolean().optional() }), z.object({ action: z.literal("rename"), id: z.string().uuid(), name: z.string().trim().min(1).max(80) }), z.object({ action: z.literal("update"), id: z.string().uuid(), query: z.string().trim().max(120).optional(), marketplace: z.enum(["Depop", "eBay", "Etsy", "Mercari", "Poshmark", "Manual"]).optional(), status: orderStatusSchema.optional() }), z.object({ action: z.literal("duplicate"), id: z.string().uuid() }), z.object({ action: z.literal("delete"), id: z.string().uuid() }), z.object({ action: z.literal("default"), id: z.string().uuid() }), z.object({ action: z.literal("reorder"), ids: z.array(z.string().uuid()).min(1) })]);
export const bulkOrderActionSchema = z.object({ action: z.enum(["reserve", "release", "ready-to-pack", "packed", "attach-preset", "ready-to-ship", "ship", "cancel", "tag", "export"]), orderIds: z.array(z.string().uuid()).min(1), tag: z.string().trim().max(60).optional(), reason: z.string().trim().max(500).optional() });
export const orderNoticeActionSchema = z.object({ id: z.string().uuid(), action: z.enum(["read", "unread", "resolve", "reopen", "archive"]) });
export const fulfillmentActionSchema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("begin-picking"), orderId: z.string().uuid(), picker: z.string().trim().max(80).optional(), mode: z.enum(["single", "batch", "zone"]).default("single") }),
  z.object({ action: z.literal("complete-picking"), shipmentId: z.string().uuid(), outcomes: z.array(z.object({ itemId: z.string().uuid(), status: z.enum(["picked", "missing", "substituted", "damaged"]), notes: z.string().trim().max(300).optional() })).optional() }),
  z.object({ action: z.literal("begin-packing"), shipmentId: z.string().uuid(), packer: z.string().trim().max(80).optional(), station: z.string().trim().max(80).optional() }),
  z.object({ action: z.literal("complete-packing"), shipmentId: z.string().uuid(), packageType: z.enum(["poly_mailer", "box", "custom"]).default("poly_mailer"), weightOz: z.coerce.number().positive(), lengthIn: z.coerce.number().positive(), widthIn: z.coerce.number().positive(), heightIn: z.coerce.number().positive(), notes: z.string().trim().max(500).optional() }),
  z.object({ action: z.literal("validate-address"), shipmentId: z.string().uuid(), provider: z.enum(["local_mock", "manual_label", "marketplace_label", "easypost", "shippo"]).default("local_mock") }),
  z.object({ action: z.literal("override-address"), shipmentId: z.string().uuid(), reason: z.string().trim().min(2).max(500) }),
  z.object({ action: z.literal("get-rates"), shipmentId: z.string().uuid(), provider: z.enum(["local_mock", "easypost", "shippo"]).default("local_mock"), insurance: z.boolean().optional(), signature: z.boolean().optional() }),
  z.object({ action: z.literal("select-rate"), shipmentId: z.string().uuid(), rateId: z.string().trim().min(2).max(200) }),
  z.object({ action: z.literal("generate-label"), shipmentId: z.string().uuid(), carrier: z.string().trim().min(2).max(80), service: z.string().trim().min(2).max(80), postageCost: z.coerce.number().nonnegative(), insurance: z.boolean().optional(), signature: z.boolean().optional() }),
  z.object({ action: z.literal("attach-manual-label"), shipmentId: z.string().uuid(), trackingNumber: z.string().trim().min(2).max(200), labelUrl: z.string().trim().min(2).max(500), carrier: z.string().trim().max(80).optional(), service: z.string().trim().max(80).optional(), postageCost: z.coerce.number().nonnegative().optional() }),
  z.object({ action: z.literal("attach-marketplace-label"), shipmentId: z.string().uuid(), trackingNumber: z.string().trim().min(2).max(200), labelUrl: z.string().trim().min(2).max(500), carrier: z.string().trim().max(80).optional(), service: z.string().trim().max(80).optional(), postageCost: z.coerce.number().nonnegative().optional() }),
  z.object({ action: z.literal("print-label"), shipmentId: z.string().uuid(), kind: z.enum(["print", "reprint"]).default("print") }),
  z.object({ action: z.literal("void-label"), shipmentId: z.string().uuid(), reason: z.string().trim().min(2).max(500) }),
  z.object({ action: z.literal("regenerate-label"), shipmentId: z.string().uuid() }),
  z.object({ action: z.literal("refresh-tracking"), shipmentId: z.string().uuid() }),
  z.object({ action: z.literal("dispatch"), shipmentId: z.string().uuid() }),
  z.object({ action: z.literal("create-manifest"), carrier: z.string().trim().max(80).optional(), shipmentIds: z.array(z.string().uuid()).min(1) }),
  z.object({ action: z.literal("dispatch-manifest"), manifestId: z.string().uuid() }),
  z.object({ action: z.literal("hold-shipment"), shipmentId: z.string().uuid(), reason: z.string().trim().min(2).max(500) }),
  z.object({ action: z.literal("release-hold"), shipmentId: z.string().uuid() }),
  z.object({ action: z.literal("assign-fulfillment"), shipmentId: z.string().uuid(), picker: z.string().trim().max(80).optional(), packer: z.string().trim().max(80).optional(), station: z.string().trim().max(80).optional(), priority: z.enum(["standard", "high", "urgent"]).optional(), slaDeadline: z.string().datetime().optional() }),
  z.object({ action: z.literal("delivered"), shipmentId: z.string().uuid() }),
  z.object({ action: z.literal("returned"), shipmentId: z.string().uuid(), notes: z.string().trim().max(500).optional() }),
  z.object({ action: z.literal("record-exception"), orderId: z.string().uuid().optional(), shipmentId: z.string().uuid().optional(), type: z.enum(["missing_inventory", "damaged_package", "failed_scan", "duplicate_shipment", "invalid_address", "label_failure", "returned_to_sender", "carrier_delay", "lost_shipment", "customer_hold", "manual_review"]), severity: z.enum(["critical", "warning", "info"]), owner: z.string().trim().max(80).optional(), notes: z.string().trim().min(2).max(1000) }),
  z.object({ action: z.literal("resolve-exception"), exceptionId: z.string().uuid(), notes: z.string().trim().min(2).max(1000) }),
  z.object({ action: z.literal("reopen-exception"), exceptionId: z.string().uuid(), notes: z.string().trim().min(2).max(1000) }),
]);
