import type { Order, StockBalance, Transaction, Variant } from "@/domain/business";

export const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value || 0);
// Lost units are removed from on-hand by the loss mutation, so they must not be
// subtracted again when determining currently usable stock.
export function availableUnits(balance: StockBalance) { return Math.max(0, balance.onHand - balance.reserved - balance.damaged - balance.quarantined); }
export function landedCost(unitCost: number, domesticShipping = 0, internationalShipping = 0, customs = 0, packaging = 0) { return unitCost + domesticShipping + internationalShipping + customs + packaging; }
export function marketplaceFee(salePrice: number, feeRate: number) { return Math.round(salePrice * feeRate * 100) / 100; }
export function orderProfit(order: Order, variants: Variant[] | Variant = []) { const variantList = Array.isArray(variants) ? variants : [variants]; const lines = order.items.map((item) => ({ ...item, unitCost: item.unitCost || variantList.find((variant) => variant.id === item.variantId)?.landedUnitCost || 0 })); const grossSales = lines.reduce((sum, item) => sum + item.unitSellingPrice * item.quantity, 0) + order.shippingCharged; const discounts = lines.reduce((sum, item) => sum + item.discountAllocation, 0); const refunds = (order.refunds || []).reduce((sum, refund) => sum + refund.amount, 0); const netSales = grossSales - discounts - refunds; const cogs = lines.reduce((sum, item) => sum + item.unitCost * Math.max(0, item.quantity - (item.cancelledQuantity || 0)), 0); const marketplaceFees = order.marketplaceFee + lines.reduce((sum, item) => sum + (item.marketplaceFeeAllocation || item.feeAllocation || 0), 0); const paymentFees = order.paymentFee + lines.reduce((sum, item) => sum + (item.paymentFeeAllocation || 0), 0); const sellerShipping = order.shippingCost; const packaging = order.packagingCost || 0; const advertising = order.advertisingCost || 0; const fees = marketplaceFees + paymentFees + sellerShipping + packaging + advertising; const contributionProfit = netSales - cogs - fees; return { grossSales, discounts, refunds, netSales, revenue: netSales, cogs, marketplaceFees, paymentFees, sellerShipping, packaging, advertising, fees, grossProfit: netSales - cogs, netProfit: contributionProfit, contributionProfit, margin: netSales ? contributionProfit / netSales * 100 : 0, lineContributions: lines.map((item) => ({ itemId: item.id, netSales: item.unitSellingPrice * item.quantity - item.discountAllocation - ((order.refunds || []).filter((refund) => refund.itemId === item.id).reduce((sum, refund) => sum + refund.amount, 0)), cogs: item.unitCost * item.quantity, contributionProfit: item.unitSellingPrice * item.quantity - item.discountAllocation - item.unitCost * item.quantity - (item.marketplaceFeeAllocation || item.feeAllocation || 0) - (item.paymentFeeAllocation || 0) })) }; }
export function inventoryValue(balances: StockBalance[], variants: Variant[]) { return balances.reduce((total, balance) => total + balance.onHand * (variants.find((variant) => variant.id === balance.variantId)?.landedUnitCost ?? 0), 0); }
export function availableCash(transactions: Transaction[]) { return transactions.filter((transaction) => transaction.status === "cleared").reduce((total, transaction) => total + transaction.amount, 0); }
export function reorderSuggestion(balance: StockBalance | undefined, variant: Variant | undefined) { if (!balance || !variant) return 0; return availableUnits(balance) <= variant.reorderPoint ? Math.max(variant.reorderQuantity, variant.reorderPoint * 2 - availableUnits(balance)) : 0; }
