import type { StockBalance, StockMovement } from "@/domain/business";

type Movement = Omit<StockMovement, "id" | "createdAt">;
const ensureInteger = (value: number, label: string) => { if (!Number.isInteger(value) || value <= 0) throw new Error(`${label} must be a positive whole number.`); };
export function adjustStock(balance: StockBalance, quantity: number, reason: string): { balance: StockBalance; movement: Movement } { if (!Number.isInteger(quantity) || quantity === 0) throw new Error("Adjustment quantity must be a non-zero whole number."); if (balance.onHand + quantity < 0) throw new Error("Adjustment would make on-hand stock negative."); return { balance: { ...balance, onHand: balance.onHand + quantity }, movement: { variantId: balance.variantId, quantity, onHandDelta: quantity, reservedDelta: 0, type: "manual_adjustment", referenceType: "inventory_adjustment", note: reason } }; }
export function transferStock(source: StockBalance, destination: StockBalance, quantity: number): { source: StockBalance; destination: StockBalance; movements: Movement[] } { ensureInteger(quantity, "Transfer quantity"); if (source.id === destination.id || source.locationId === destination.locationId) throw new Error("Source and destination locations must be different."); if (source.variantId !== destination.variantId) throw new Error("Transfers must use balances for the same variant."); if (source.onHand - source.reserved - source.damaged - source.quarantined < quantity) throw new Error("Insufficient available unreserved inventory to transfer."); return { source: { ...source, onHand: source.onHand - quantity }, destination: { ...destination, onHand: destination.onHand + quantity }, movements: [{ variantId: source.variantId, quantity: -quantity, onHandDelta: -quantity, reservedDelta: 0, type: "transfer", sourceLocationId: source.locationId, destinationLocationId: destination.locationId, referenceType: "inventory_transfer" }, { variantId: destination.variantId, quantity, onHandDelta: quantity, reservedDelta: 0, type: "transfer", sourceLocationId: source.locationId, destinationLocationId: destination.locationId, referenceType: "inventory_transfer" }] }; }
export function reconcileCycleCount(balance: StockBalance, countedQuantity: number): { balance: StockBalance; movement?: Movement } { if (!Number.isInteger(countedQuantity) || countedQuantity < 0) throw new Error("Counted quantity must be a non-negative whole number."); if (countedQuantity < balance.reserved) throw new Error("Cycle count cannot reduce on-hand below reserved quantity."); const delta = countedQuantity - balance.onHand; return { balance: { ...balance, onHand: countedQuantity }, movement: delta ? { variantId: balance.variantId, quantity: delta, onHandDelta: delta, reservedDelta: 0, type: "cycle_count", referenceType: "inventory_count", note: "Approved cycle count variance" } : undefined }; }
export function markDamaged(balance: StockBalance, quantity: number, reason: string) { ensureInteger(quantity, "Damage quantity"); if (balance.onHand - balance.reserved - balance.damaged - balance.quarantined < quantity) throw new Error("Insufficient usable inventory to mark damaged."); return { balance: { ...balance, damaged: balance.damaged + quantity }, movement: { variantId: balance.variantId, quantity: -quantity, onHandDelta: 0, reservedDelta: 0, type: "damage" as const, referenceType: "inventory_damage", note: reason } }; }
export function moveToQuarantine(balance: StockBalance, quantity: number, reason: string) { ensureInteger(quantity, "Quarantine quantity"); if (balance.onHand - balance.reserved - balance.damaged - balance.quarantined < quantity) throw new Error("Insufficient usable inventory to quarantine."); return { balance: { ...balance, quarantined: balance.quarantined + quantity }, movement: { variantId: balance.variantId, quantity: -quantity, onHandDelta: 0, reservedDelta: 0, type: "manual_adjustment" as const, referenceType: "inventory_quarantine", note: reason } }; }
export function releaseFromQuarantine(balance: StockBalance, quantity: number, reason: string) { ensureInteger(quantity, "Release quantity"); if (balance.quarantined < quantity) throw new Error("Cannot release more than the quarantined quantity."); return { balance: { ...balance, quarantined: balance.quarantined - quantity }, movement: { variantId: balance.variantId, quantity, onHandDelta: 0, reservedDelta: 0, type: "manual_adjustment" as const, referenceType: "inventory_quarantine_release", note: reason } }; }
export function markLost(balance: StockBalance, quantity: number, reason: string) { ensureInteger(quantity, "Loss quantity"); if (balance.onHand - balance.reserved - balance.damaged - balance.quarantined < quantity) throw new Error("Insufficient usable inventory to mark lost."); return { balance: { ...balance, onHand: balance.onHand - quantity, lost: balance.lost + quantity }, movement: { variantId: balance.variantId, quantity: -quantity, onHandDelta: -quantity, reservedDelta: 0, type: "loss" as const, referenceType: "inventory_loss", note: reason } }; }
export function recordFound(balance: StockBalance, quantity: number, reason: string) { ensureInteger(quantity, "Found quantity"); return { balance: { ...balance, onHand: balance.onHand + quantity }, movement: { variantId: balance.variantId, quantity, onHandDelta: quantity, reservedDelta: 0, type: "manual_adjustment" as const, referenceType: "inventory_found", note: reason } }; }
export function assignLocation(balance: StockBalance, locationId: string) { if (!locationId) throw new Error("A destination location is required."); return { balance: { ...balance, locationId }, movement: { variantId: balance.variantId, quantity: 0, onHandDelta: 0, reservedDelta: 0, type: "transfer" as const, sourceLocationId: balance.locationId, destinationLocationId: locationId, referenceType: "inventory_location_assignment", note: "Inventory location assigned" } }; }
