import type { Marketplace, OrderImportReview, Variant } from "@/domain/business";

export type MarketplaceCapabilities = { orderRead: boolean; refundRead: boolean; returnRead: boolean; payoutRead: boolean; messagesRead: boolean };
export type ImportedOrderLine = { externalOrderId: string; marketplace: Marketplace; customerName: string; email?: string; sku?: string; listingId?: string; title: string; quantity: number; unitPrice: number; tax?: number; shippingCharged?: number; marketplaceFee?: number; paymentFee?: number; orderedAt?: string; status?: string };
export type ImportOrdersInput = { dryRun?: boolean; since?: string };
export type ImportOrdersResult = { lines: ImportedOrderLine[]; errors: { row: number; message: string }[] };
export interface MarketplaceOrderAdapter { capabilities(): MarketplaceCapabilities; importOrders(input: ImportOrdersInput): Promise<ImportOrdersResult>; getOrder(externalOrderId: string): Promise<ImportedOrderLine[]>; }
export class LocalDemoOrderAdapter implements MarketplaceOrderAdapter { capabilities() { return { orderRead: true, refundRead: false, returnRead: false, payoutRead: false, messagesRead: false }; } async importOrders() { return { lines: [], errors: [] }; } async getOrder() { return []; } }
export function parseOrderCsv(text: string, marketplace: Marketplace): ImportOrdersResult { const rows = text.trim().split(/\r?\n/).filter(Boolean); if (!rows.length) return { lines: [], errors: [{ row: 1, message: "CSV is empty." }] }; const headers = rows[0].split(",").map((value) => value.trim().toLowerCase()); const field = (cells: string[], name: string) => cells[headers.indexOf(name)]?.trim(); const lines: ImportedOrderLine[] = []; const errors: { row: number; message: string }[] = []; rows.slice(1).forEach((row, index) => { const cells = row.split(","); const externalOrderId = field(cells, "external order id") || field(cells, "order id"); const customerName = field(cells, "customer") || field(cells, "customer name"); const title = field(cells, "title") || field(cells, "item title"); const quantity = Number(field(cells, "quantity")); const unitPrice = Number(field(cells, "unit price") || field(cells, "price")); if (!externalOrderId || !customerName || !title || !Number.isInteger(quantity) || quantity <= 0 || !Number.isFinite(unitPrice) || unitPrice < 0) { errors.push({ row: index + 2, message: "External order ID, customer, title, positive quantity, and non-negative unit price are required." }); return; } lines.push({ externalOrderId, marketplace, customerName, email: field(cells, "email"), sku: field(cells, "sku"), listingId: field(cells, "listing id"), title, quantity, unitPrice, tax: Number(field(cells, "tax") || 0), shippingCharged: Number(field(cells, "shipping") || 0), marketplaceFee: Number(field(cells, "marketplace fee") || 0), paymentFee: Number(field(cells, "payment fee") || 0), orderedAt: field(cells, "order date"), status: field(cells, "status") }); }); return { lines, errors }; }
export function reviewImportedLine(line: ImportedOrderLine, variants: Variant[]): OrderImportReview | undefined { const candidates = variants.filter((variant) => line.sku ? variant.sku.toLowerCase() === line.sku.toLowerCase() : variant.title.toLowerCase().includes(line.title.toLowerCase())).map((variant) => variant.id); if (candidates.length === 1) return undefined; return { id: crypto.randomUUID(), marketplace: line.marketplace, externalOrderId: line.externalOrderId, externalListingId: line.listingId, externalSku: line.sku, itemTitle: line.title, quantity: line.quantity, unitPrice: line.unitPrice, likelyVariantIds: candidates, matchConfidence: candidates.length ? 0.5 : 0, state: "open", createdAt: new Date().toISOString() }; }
