import Link from "next/link";
import type { ReturnTypeSnapshot } from "@/components/operations/types";
import { AiCenterPanel } from "@/components/operations/ai-center-panel";
import type { AiProviderKey } from "@/domain/business";
import { money } from "@/lib/business-calculations";
import { buildAiOperatingContext, ensureAiCollections } from "@/lib/ai-center";

const Panel = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border border-border bg-card"><h2 className="border-b border-border px-5 py-4 font-semibold">{title}</h2>{children}</section>;
const Status = ({ value }: { value: string }) => <span className="text-xs capitalize text-emerald-300">{value.replaceAll("_", " ")}</span>;
const Row = ({ label, value }: { label: string; value: React.ReactNode }) => <div className="flex justify-between gap-4 border-b border-border px-5 py-3 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><span className="text-right">{value}</span></div>;
const Header = ({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) => <header><p className="text-xs uppercase tracking-[0.2em] text-emerald-400">{eyebrow}</p><h1 data-testid="page-title" className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></header>;
const Metric = ({ label, value }: { label: string; value: string }) => <article className="border border-border bg-card p-5"><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-3 font-mono text-2xl">{value}</p></article>;

export function AiCenterWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot; ensureAiCollections(data); const context = buildAiOperatingContext(data);
  const configuredProvider = (process.env.AI_PROVIDER || "deterministic") as AiProviderKey;
  const latestBrief = data.aiDailyBriefs?.[0];
  const latestConversation = [...(data.aiConversations || [])].sort((a, b) => new Date(b.updatedAt || b.createdAt).getTime() - new Date(a.updatedAt || a.createdAt).getTime())[0];
  const latestMessages = latestConversation ? (data.aiMessages || []).filter((message) => message.conversationId === latestConversation.id).sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()) : [];
  return <div className="space-y-6"><Header eyebrow="AI center" title="Daily brief and evidence-backed recommendations" description="Faust answers questions by calling safe internal tools, citing real operating records, and routing risky actions through approval." />
    <AiCenterPanel data={data} provider={configuredProvider} />
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Provider mode" value={configuredProvider === "openai" ? "OpenAI" : "Deterministic"} /><Metric label="Evidence links" value={String((data.aiEvidenceLinks || []).length)} /><Metric label="Recommendations" value={String((data.aiRecommendations || []).length)} /><Metric label="Tool calls" value={String((data.aiToolCalls || []).length)} /></div>
    <div className="grid gap-6 lg:grid-cols-3"><Panel title="Safe internal tools"><Row label="Inventory / reorder" value={`${context.reorders.filter((entry) => entry.suggested > 0).length} risk(s)`} /><Row label="Finance / deployable cash" value={money(context.finance.overview.deployableCash)} /><Row label="Fulfillment exceptions" value={String(context.shipmentsNeedingAttention.length)} /><Row label="Listing risks" value={String(context.listingRisks.length)} /><Row label="Automation failures" value={String(context.automationFailures.length)} /></Panel><Panel title="Provider adapters"><Row label="No-provider deterministic mode" value={configuredProvider === "deterministic" ? "active" : "available"} /><Row label="OpenAI adapter" value={configuredProvider === "openai" ? "active" : "configured later"} /><Row label="Anthropic-ready adapter" value="credentials later" /><Row label="Gemini-ready adapter" value="credentials later" /><p className="px-5 pb-4 text-xs text-muted-foreground">Model providers receive structured tool output and evidence, not unverified free-form operating data.</p></Panel><Panel title="Safety and approvals"><Row label="Risky purchase orders" value="approval required" /><Row label="Tax reserve moves" value="approval required" /><Row label="Bulk delists/refunds" value="approval required" /><Row label="Open AI approvals" value={String((data.aiApprovalProposals || []).filter((proposal) => proposal.status === "pending").length)} /></Panel></div>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="Daily operating brief">{latestBrief ? latestBrief.sections.map((section) => <div className="border-b border-border p-5 last:border-0" key={`${latestBrief.id}-${section.title}`}><div className="flex justify-between gap-4"><b>{section.title}</b><Status value={section.severity} /></div><p className="mt-2 text-sm text-muted-foreground">{section.summary}</p><Link className="mt-3 inline-block text-xs text-emerald-400" href={section.href}>Open source records →</Link></div>) : <p className="p-5 text-sm text-muted-foreground">Generate a daily brief to summarize urgent actions, cash, inventory risks, purchasing, fulfillment, listing sync, suppliers, automations, and opportunities.</p>}</Panel><Panel title="Latest grounded answer">{latestMessages.length ? latestMessages.map((message) => <div className="border-b border-border p-5 last:border-0" key={message.id}><Status value={message.role} /><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{message.content}</p><p className="mt-3 text-xs text-muted-foreground">Grounded: {message.grounded ? "yes" : "no"} · citations {message.evidenceIds.length} · tools {message.toolCallIds.length}</p></div>) : <p className="p-5 text-sm text-muted-foreground">Ask a question to create a persisted conversation with citations and tool-call history.</p>}</Panel></div>
    <Panel title="Evidence-backed recommendations"><div className="grid gap-4 p-5 md:grid-cols-2">{(data.aiRecommendations || []).map((recommendation) => <article className="border border-border p-4" key={recommendation.id}><div className="flex items-start justify-between gap-3"><div><Status value={recommendation.type} /><h2 className="mt-2 font-semibold">{recommendation.title}</h2></div><span className="text-xs text-muted-foreground">{Math.round(recommendation.confidence * 100)}% confidence</span></div><p className="mt-2 text-sm text-muted-foreground">{recommendation.recommendation}</p><p className="mt-2 text-xs text-muted-foreground">Reasoning: {recommendation.reasoning}</p><p className="mt-2 text-xs text-muted-foreground">Impact: {recommendation.expectedImpact}</p><p className="mt-2 text-xs text-muted-foreground">Risk: {recommendation.risk}</p><p className="mt-2 text-xs text-muted-foreground">Approval: {recommendation.approvalRequired ? "required" : "not required"} · status {recommendation.status}</p></article>)}{!(data.aiRecommendations || []).length && <p className="text-sm text-muted-foreground">Ask a question or generate a brief to create recommendations grounded in Faust records.</p>}</div></Panel>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="Scenario analysis">{(data.aiScenarios || []).map((scenario) => <div className="border-b border-border p-5 last:border-0" key={scenario.id}><b>{scenario.name}</b><p className="mt-2 text-sm text-muted-foreground">{scenario.prompt}</p><div className="mt-3 grid gap-2 md:grid-cols-2"><Row label="Deployable cash impact" value={money(scenario.impacts.deployableCash)} /><Row label="Purchase commitments" value={money(scenario.impacts.purchaseCommitments)} /><Row label="Forecast revenue" value={money(scenario.impacts.forecastRevenue)} /><Row label="Stockout risk" value={`${Math.round(scenario.impacts.stockoutRisk * 100)}%`} /></div><p className="mt-3 text-xs text-muted-foreground">Assumptions: {scenario.assumptions.join(" · ")}</p></div>)}{!(data.aiScenarios || []).length && <p className="p-5 text-sm text-muted-foreground">Run scenarios for unit buys, price changes, safety stock, supplier changes, marketing spend, and cash reserves.</p>}</Panel><Panel title="Citations and drilldowns">{(data.aiEvidenceLinks || []).slice(0, 10).map((link) => <div className="border-b border-border p-5 last:border-0" key={link.id}><Link className="font-semibold text-emerald-300" href={link.href}>{link.label}</Link><p className="mt-2 text-xs text-muted-foreground">{link.sourceType} · {link.excerpt}</p></div>)}{!(data.aiEvidenceLinks || []).length && <p className="p-5 text-sm text-muted-foreground">Citations appear after Faust answers a question or generates a brief.</p>}</Panel></div>
    <div className="grid gap-6 lg:grid-cols-3"><Panel title="Saved questions">{(data.aiSavedQuestions || []).slice(0, 8).map((question) => <Row key={question.id} label={question.question} value={question.category} />)}</Panel><Panel title="Tool-call observability">{(data.aiToolCalls || []).slice(0, 8).map((call) => <Row key={call.id} label={call.toolName} value={`${call.status} · ${call.latencyMs}ms`} />)}{!(data.aiToolCalls || []).length && <p className="p-5 text-sm text-muted-foreground">Tool calls are persisted with inputs, outputs, latency, and evidence links.</p>}</Panel><Panel title="Feedback and history">{(data.aiFeedback || []).slice(0, 5).map((feedback) => <Row key={feedback.id} label={feedback.rating} value={new Date(feedback.createdAt).toLocaleTimeString()} />)}{(data.aiObservabilityEvents || []).slice(0, 3).map((event) => <Row key={event.id} label={`${event.provider} confidence`} value={`${Math.round(event.confidence * 100)}%`} />)}{!(data.aiFeedback || []).length && !(data.aiObservabilityEvents || []).length && <p className="p-5 text-sm text-muted-foreground">Feedback, token usage, latency, provider, retry count, and confidence appear after AI Center activity.</p>}</Panel></div>
  </div>;
}
