import Link from "next/link";
import { AlertTriangle, ArrowRight, Banknote, Boxes, ClipboardCheck, PackageCheck, Sparkles, TrendingUp } from "lucide-react";
import { MetricCard } from "@/components/operations/metric-card";
import { money } from "@/lib/business-calculations";
import { buildAnalyticsModel } from "@/lib/analytics";
import { buildFinanceModel } from "@/lib/finance";
import type { ReturnTypeSnapshot } from "@/components/operations/types";

function EmptyMissionControl() {
  return <div className="space-y-6"><section className="mx-auto max-w-5xl rounded-3xl border border-dashed border-sky-400/35 bg-zinc-950/60 p-10 text-center shadow-2xl shadow-black/25 backdrop-blur"><Sparkles className="mx-auto h-9 w-9 text-sky-200" /><h1 className="mt-4 text-2xl font-semibold">Set up Mission Control</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Faust is ready for your first real product. Start by importing from the browser extension, then create product records, purchase inventory, publish listings, and let orders populate the operating system.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/sourcing" className="rounded-full bg-sky-500 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-sky-950/30 transition hover:bg-sky-400">Import first product</Link><Link href="/settings" className="rounded-full border border-sky-950/60 bg-zinc-950/50 px-4 py-2 text-sm transition hover:border-sky-400/50">Complete business profile</Link><Link href="/listings" className="rounded-full border border-sky-950/60 bg-zinc-950/50 px-4 py-2 text-sm transition hover:border-sky-400/50">Connect marketplace</Link></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Products" value="0" detail="No product records yet" /><MetricCard label="Inventory" value="0" detail="No stock received yet" /><MetricCard label="Orders" value="0" detail="No marketplace orders yet" /><MetricCard label="Revenue" value="$0.00" detail="No sales recorded yet" /><MetricCard label="Cash" value="$0.00" detail="No financial activity yet" /></section></div>;
}

function ActionRow({ title, detail, href, action = "Open" }: { title: string; detail: string; href: string; action?: string }) {
  return <Link href={href} className="group flex items-center justify-between gap-4 rounded-2xl border border-transparent px-4 py-3 transition hover:border-sky-950/60 hover:bg-sky-950/15"><span><span className="block text-sm font-medium">{title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{detail}</span></span><span className="inline-flex items-center gap-1 text-xs font-semibold text-sky-200">{action}<ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></Link>;
}

export function MissionControl({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data, metrics, attention, reorders } = snapshot;
  if (data.mode === "empty") return <EmptyMissionControl />;

  const finance = buildFinanceModel(data);
  const analytics = buildAnalyticsModel(data);
  const ordersNeedingAction = data.orders.filter((order) => ["paid", "confirmed", "inventory_reserved", "ready_to_pack", "packed", "label_purchased", "ready_to_ship"].includes(order.status));
  const listingRisks = (data.channelListingDrafts || []).filter((draft) => draft.status === "failed" || draft.syncState === "failed" || draft.syncState === "risk_locked" || draft.validationErrors.length);
  const delayedShipments = (data.fulfillmentShipments || []).filter((shipment) => ["exception", "delayed", "address_issue"].includes(shipment.status) || shipment.trackingStatus === "delayed");
  const openPurchasePlans = data.purchaseOrders.filter((po) => ["draft", "pending_approval", "approved", "ordered"].includes(po.status)).slice(0, 3);
  const strongestSku = analytics.products.slice().sort((a, b) => b.profit - a.profit)[0];
  const recentOrders = data.orders.slice(0, 4);
  const kpis = [
    ["Cash to reinvest", money(finance.overview.deployableCash), `${money(finance.overview.cash)} cash less reserves and commitments`, <Banknote key="cash" size={15} />],
    ["Orders needing action", String(ordersNeedingAction.length), "Pack, ship, cancel, refund, or review", <PackageCheck key="orders" size={15} />],
    ["Products to reorder", String(reorders.length), `${metrics.incoming} units already incoming`, <Boxes key="reorder" size={15} />],
    ["Listings needing attention", String(listingRisks.length), "Validation, sync, or risk-lock review", <AlertTriangle key="listings" size={15} />],
    ["Recent net profit", money(metrics.netProfit), `${metrics.margin.toFixed(1)}% net margin from recorded orders`, <TrendingUp key="profit" size={15} />],
  ] as const;

  return <div className="space-y-7"><section className="relative overflow-hidden rounded-3xl border border-sky-950/45 bg-zinc-950/60 p-6 shadow-2xl shadow-black/25 backdrop-blur"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-sky-500/20 blur-3xl" /><div className="pointer-events-none absolute -bottom-28 left-1/4 h-64 w-64 rounded-full bg-sky-950/30 blur-3xl" /><div className="relative"><p className="text-xs font-medium uppercase tracking-[0.2em] text-sky-200">Mission Control</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Know what needs action next.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">A daily business cockpit for orders, inventory, listings, cash, purchasing, and sourcing decisions. Technical diagnostics are kept out of the way unless you open System.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded-full bg-sky-500 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-sky-950/30 transition hover:bg-sky-400" href="/sourcing">Import Superbuy product</Link><Link className="rounded-full border border-sky-950/60 bg-zinc-950/50 px-4 py-2 text-sm transition hover:border-sky-400/50" href="/orders">Review orders</Link><Link className="rounded-full border border-sky-950/60 bg-zinc-950/50 px-4 py-2 text-sm transition hover:border-sky-400/50" href="/ai-center">Ask Faust</Link></div></div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(([label, value, detail, icon]) => <MetricCard key={label} label={label} value={value} detail={detail} icon={icon} />)}</section>

    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur xl:col-span-2"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Today&apos;s action list</h2><p className="text-sm text-muted-foreground">The work most likely to protect revenue or free up cash.</p></div><ClipboardCheck className="h-5 w-5 text-sky-200" /></div><div className="space-y-1">{ordersNeedingAction.length ? <ActionRow title={`${ordersNeedingAction.length} order${ordersNeedingAction.length === 1 ? "" : "s"} need fulfillment`} detail="Pack, label, dispatch, or resolve blocked orders." href="/shipping" action="Go ship" /> : <ActionRow title="No urgent fulfillment queue" detail="Import orders or keep marketplace order sync current." href="/orders" action="Open orders" />}{reorders.length ? <ActionRow title={`${reorders.length} product${reorders.length === 1 ? "" : "s"} need reorder review`} detail={`${reorders[0].variant.sku} is the highest-priority reorder right now.`} href="/inventory" action="Review stock" /> : <ActionRow title="No reorder alerts" detail="Reorder points are healthy based on current inventory." href="/inventory" action="Open inventory" />}{listingRisks.length ? <ActionRow title={`${listingRisks.length} listing issue${listingRisks.length === 1 ? "" : "s"} need attention`} detail="Fix validation, sync failures, or channel risk locks." href="/listings" action="Fix listings" /> : <ActionRow title="Listings look clean" detail="Drafts and channel sync have no active validation failures." href="/listings" action="Open listings" />}{delayedShipments.length ? <ActionRow title={`${delayedShipments.length} shipment issue${delayedShipments.length === 1 ? "" : "s"}`} detail="Delayed, exception, or address-risk shipments need review." href="/shipping" action="Resolve" /> : <ActionRow title="No delayed shipments" detail="Shipment exception queue is clear." href="/shipping" action="Open shipping" />}</div></div>

      <div className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur"><h2 className="text-lg font-semibold">Best current opportunity</h2>{strongestSku ? <div className="mt-4 rounded-2xl border border-sky-950/35 bg-black/35 p-4"><p className="text-sm font-medium">{strongestSku.sku}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{strongestSku.title}</p><p className="mt-4 text-2xl font-semibold">{money(strongestSku.profit)}</p><p className="text-xs text-muted-foreground">recorded profit · {strongestSku.margin.toFixed(1)}% margin</p><Link href={strongestSku.sourceHref} className="mt-4 inline-flex text-xs font-semibold text-sky-200">Open product</Link></div> : <p className="mt-4 text-sm leading-6 text-muted-foreground">Import products and orders to see which SKU deserves more capital.</p>}</div></section>

    <section className="grid gap-5 lg:grid-cols-4"><div className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur"><h2 className="text-lg font-semibold">Purchasing plans</h2><div className="mt-3 space-y-2">{openPurchasePlans.length ? openPurchasePlans.map((po) => <ActionRow key={po.id} title={po.reference} detail={`${po.status.replaceAll("_", " ")} · ${money(po.totalCost)} committed`} href="/purchasing" action="Review" />) : <p className="text-sm leading-6 text-muted-foreground">No active purchase plans. Import a Superbuy opportunity to create one.</p>}</div></div><div className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur"><h2 className="text-lg font-semibold">Recent performance</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Revenue</span><span>{money(metrics.revenue)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Orders</span><span>{metrics.orders}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Average order</span><span>{money(metrics.averageOrderValue)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Units sold</span><span>{metrics.units}</span></div></div><Link href="/analytics" className="mt-5 inline-flex text-xs font-semibold text-sky-200">Open analytics</Link></div><div className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur"><h2 className="text-lg font-semibold">Recent orders</h2><div className="mt-3 space-y-2">{recentOrders.length ? recentOrders.map((order) => <ActionRow key={order.id} title={`${order.number} · ${order.marketplace}`} detail={`${order.status.replaceAll("_", " ")} · ${money(order.items.reduce((sum, item) => sum + item.quantity * item.unitSellingPrice, 0))}`} href="/orders" action="Open" />) : <p className="text-sm leading-6 text-muted-foreground">No orders yet. Import marketplace orders to activate daily performance tracking.</p>}</div></div><div className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur"><h2 className="text-lg font-semibold">Alerts</h2><div className="mt-3 space-y-2">{attention.slice(0, 3).length ? attention.slice(0, 3).map((notice) => <ActionRow key={notice.id} title={notice.title} detail={notice.detail} href={notice.href} action={notice.actionLabel || "Review"} />) : <p className="text-sm leading-6 text-muted-foreground">No active alerts. Faust will surface issues here when records need review.</p>}</div></div></section>

    <section className="rounded-3xl border border-sky-950/45 bg-zinc-950/55 p-5 shadow-lg shadow-black/20 backdrop-blur"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-semibold">Recent business activity</h2><p className="text-sm text-muted-foreground">Audit trail for meaningful actions. Raw logs and provider payloads belong in System.</p></div><Link href="/tasks" className="text-xs font-semibold text-sky-200">Open tasks</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.activity.slice(0, 6).length ? data.activity.slice(0, 6).map((entry) => <div key={entry.id} className="rounded-2xl border border-sky-950/35 bg-black/35 p-4"><p className="text-sm font-medium">{entry.action}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{entry.detail}</p></div>) : <p className="text-sm leading-6 text-muted-foreground">No activity yet. Import your first product or create a purchase plan to start building the operating trail.</p>}</div></section></div>;
}
