import Link from "next/link";
import { OperationButton } from "@/components/operations/operation-button";
import type { ReturnTypeSnapshot } from "@/components/operations/types";
import { availableUnits, money, orderProfit } from "@/lib/business-calculations";

const Panel = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border border-border bg-card"><h2 className="border-b border-border px-5 py-4 font-semibold">{title}</h2>{children}</section>;
const Status = ({ value }: { value: string }) => <span className="text-xs capitalize text-emerald-300">{value.replaceAll("_", " ")}</span>;
const Row = ({ label, value }: { label: string; value: React.ReactNode }) => <div className="flex justify-between gap-4 border-b border-border px-5 py-3 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><span className="text-right">{value}</span></div>;
const Header = ({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) => <header><p className="text-xs uppercase tracking-[0.2em] text-emerald-400">{eyebrow}</p><h1 data-testid="page-title" className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></header>;
const Metric = ({ label, value }: { label: string; value: string }) => <article className="border border-border bg-card p-5"><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-3 font-mono text-2xl">{value}</p></article>;

export function InventoryWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot;
  return <div className="space-y-6"><Header eyebrow="Inventory control" title="Stock, locations, and receiving" description="Balances separate on-hand, reserved, incoming, damaged, lost, and quarantined units." /><div className="grid gap-6 lg:grid-cols-3"><Panel title="Inventory health">{data.variants.map((variant) => { const balance = data.balances.find((x) => x.variantId === variant.id); const available = balance ? availableUnits(balance) : 0; return <Row key={variant.id} label={`${variant.sku} · ${variant.title}`} value={`${available} available`} />; })}</Panel><Panel title="Locations & bins">{data.locations.map((location) => <Row key={location.id} label={location.warehouse} value={location.label} />)}{!data.locations.length && <p className="p-5 text-sm text-muted-foreground">Create warehouse, zone, aisle, shelf, and bin locations before receiving stock.</p>}</Panel><Panel title="Barcode workflow"><p className="p-5 text-sm text-muted-foreground">Use a SKU or barcode scan to identify a variant before packing, receiving, transferring, counting, or adjusting inventory. Scans never create ambiguous quantity changes.</p></Panel></div><Panel title="Variant balances & movement history"><div className="divide-y divide-border">{data.variants.map((variant) => { const balance = data.balances.find((x) => x.variantId === variant.id); return <div className="grid gap-3 p-5 md:grid-cols-3" key={variant.id}><div><b>{variant.sku}</b><p className="text-xs text-muted-foreground">{variant.title}</p></div><div className="text-sm">On hand {balance?.onHand || 0} · reserved {balance?.reserved || 0} · incoming {balance?.incoming || 0}</div><div className="text-xs text-muted-foreground">{data.stockMovements.filter((x) => x.variantId === variant.id).slice(0, 3).map((x) => `${x.type.replaceAll("_", " ")} ${x.quantity}`).join(" · ") || "No movements"}</div></div>; })}</div></Panel><Panel title="Partial receiving">{data.parcels.map((parcel) => <div className="border-b border-border p-5 last:border-0" key={parcel.id}><b>{parcel.trackingNumber}</b><p className="mt-1 text-sm text-muted-foreground">{parcel.items.map((item) => `${item.expectedQuantity - item.receivedQuantity} units remaining`).join(" · ")}</p><p className="mt-2 text-xs text-muted-foreground">Receiving uses explicit parcel rows and linked PO items. It supports partial, damaged, missing, rejected, and overage quantities.</p>{parcel.status !== "delivered" && <div className="mt-3"><OperationButton action="receive-parcel" id={parcel.id}>Receive remaining linked items</OperationButton></div>}</div>)}</Panel></div>;
}

export function OrdersWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot;
  return <div className="space-y-6"><Header eyebrow="Order operations" title="Orders, reservations, returns, and reconciliation" description="Each order owns explicit line items and is reconciled against its inventory and fees." /><div className="grid gap-6 lg:grid-cols-3"><Panel title="Fulfillment queue">{data.orders.filter((x) => ["inventory_reserved", "ready_to_pack", "packed", "label_purchased", "ready_to_ship"].includes(x.status)).map((order) => <Row key={order.id} label={order.number} value={<Status value={order.status} />}/>)}</Panel><Panel title="Returns & refunds">{data.orders.filter((x) => x.status.includes("return") || x.status === "refunded").map((order) => <Row key={order.id} label={order.number} value={<Status value={order.status} />}/>)}{!data.orders.some((x) => x.status.includes("return") || x.status === "refunded") && <p className="p-5 text-sm text-muted-foreground">No unresolved return or refund records.</p>}</Panel><Panel title="Customer context">{data.customers.slice(0, 5).map((customer) => <Row key={customer.id} label={customer.name} value={`${customer.orderCount} orders`} />)}</Panel></div>{data.orders.map((order) => { const profit = orderProfit(order, data.variants); const customer = data.customers.find((x) => x.id === order.customerId); return <Panel key={order.id} title={`${order.number} · ${order.marketplace}`}><div className="grid md:grid-cols-3"><div>{order.items.map((item) => <Row key={item.id} label={`${item.title} ×${item.quantity}`} value={`${money(item.unitSellingPrice * item.quantity)} / COGS ${money(item.unitCost * item.quantity)}`} />)}</div><div className="border-y border-border md:border-x md:border-y-0"><Row label="Marketplace fee" value={money(order.marketplaceFee)} /><Row label="Payment fee" value={money(order.paymentFee)} /><Row label="Shipping" value={money(order.shippingCost)} /><Row label="Contribution profit" value={money(profit.netProfit)} /></div><div><Row label="Customer" value={customer?.name || "Unmatched"} /><Row label="Tracking" value={order.trackingNumber || "Attach manually"} /><Row label="Timeline" value={<Status value={order.status} />} />{order.status === "ready_to_ship" && <div className="p-5"><OperationButton action="transition-order" id={order.id} status="shipped">Dispatch after scan and label check</OperationButton></div>}</div></div></Panel>; })}</div>;
}

export function ShippingWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot; const queue = data.orders.filter((x) => ["ready_to_pack", "packed", "label_purchased", "ready_to_ship"].includes(x.status));
  return <div className="space-y-6"><Header eyebrow="Fulfillment center" title="Packing, labels, dispatch, and tracking" description="Packing verifies each item before dispatch; labels are attached through a manual or provider adapter." /><div className="grid gap-6 lg:grid-cols-3"><Panel title="Ready to pack">{queue.map((order) => <Row key={order.id} label={order.number} value={<Status value={order.status} />}/>)}</Panel><Panel title="Tracking exceptions">{data.orders.filter((x) => x.status === "shipped" && !x.trackingNumber).map((order) => <Row key={order.id} label={order.number} value="Tracking required" />)}<p className="p-5 text-sm text-muted-foreground">Use provider events or manual tracking records; no fake carrier connection is shown.</p></Panel><Panel title="Print layouts"><p className="p-5 text-sm text-muted-foreground">4×6 labels, letter labels, packing slips, reprints, and batch print are browser-print workflows. Silent printer control is intentionally not claimed.</p></Panel></div><Panel title="Packing station">{queue.map((order) => <div className="border-b border-border p-5 last:border-0" key={order.id}><div className="flex justify-between"><b>{order.number}</b><Status value={order.status} /></div><p className="mt-2 text-sm text-muted-foreground">Scan and verify: {order.items.map((item) => `${item.title} ×${item.quantity}`).join(" · ")}</p><ol className="mt-3 list-decimal space-y-1 pl-5 text-xs text-muted-foreground"><li>Verify customer address and chosen package.</li><li>Record weight/dimensions and attach or buy a label.</li><li>Print label/packing slip, then dispatch.</li></ol>{order.status === "ready_to_ship" && <div className="mt-4"><OperationButton action="transition-order" id={order.id} status="shipped">Confirm dispatch</OperationButton></div>}</div>)}</Panel></div>;
}

export function ListingsWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot;
  return <div className="space-y-6"><Header eyebrow="Cross-listing" title="Marketplace drafts, validation, and delist coordination" description="Listings are separate marketplace records; manual publication is explicit until a provider adapter is connected." /><div className="grid gap-6 lg:grid-cols-3"><Panel title="Manual publish workflow"><ol className="list-decimal space-y-2 p-5 pl-9 text-sm text-muted-foreground"><li>Copy title, description, price, category, condition, and shipping fields.</li><li>Download/upload images in order.</li><li>Paste external listing URL and ID.</li><li>Confirm active status; coordinate sibling delisting after a sale.</li></ol></Panel><Panel title="Validation & errors">{data.listings.filter((x) => x.status === "failed" || x.syncState === "error").map((listing) => <Row key={listing.id} label={listing.title} value="Review error" />)}<p className="p-5 text-sm text-muted-foreground">Provider validation is required before automated publishing. Manual listings retain an actionable checklist.</p></Panel><Panel title="Templates"><p className="p-5 text-sm text-muted-foreground">Templates hold marketplace-specific fields and validation presets. Add provider credentials later without changing product data.</p></Panel></div>{data.listings.map((listing) => <Panel key={listing.id} title={listing.title}><div className="grid md:grid-cols-3"><div><Row label="Marketplace" value={listing.marketplace} /><Row label="Price" value={money(listing.price)} /><Row label="Quantity" value={listing.quantity} /></div><div className="border-y border-border md:border-x md:border-y-0"><Row label="State" value={<Status value={listing.status} />} /><Row label="Sync" value={listing.syncState} /><Row label="External URL" value={listing.marketplaceUrl || "Paste after manual publish"} /></div><p className="p-5 text-sm text-muted-foreground">Use the manual workflow to copy content, upload images, publish, confirm external ID/URL, and mark active.</p></div></Panel>)}</div>;
}

export function FinanceWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data, metrics } = snapshot; const pending = data.transactions.filter((x) => x.status === "pending").reduce((sum, x) => sum + x.amount, 0);
  return <div className="space-y-6"><Header eyebrow="Finance control" title="Ledger, payout reconciliation, cash, and planning" description="Dashboards derive from stored transactions and order fee/COGS allocations." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Cleared cash" value={money(metrics.cash)} /><Metric label="Pending payouts" value={money(pending)} /><Metric label="Inventory value" value={money(metrics.inventoryValue)} /><Metric label="Contribution profit" value={money(metrics.netProfit)} /></div><div className="grid gap-6 lg:grid-cols-3"><Panel title="Tax reserve"><p className="p-5 text-sm text-muted-foreground">Maintain a tax reserve as a normalized finance record; it reduces deployable cash without changing realized profit.</p></Panel><Panel title="Budgets & reinvestment"><p className="p-5 text-sm text-muted-foreground">Budgets, committed POs, operating buffer, and forecast assumptions make reinvestment allocation explicit.</p></Panel><Panel title="Order reconciliation"><p className="p-5 text-sm text-muted-foreground">Gross sale − discounts/refunds − marketplace/payment/shipping/packaging/COGS = contribution profit.</p></Panel></div><Panel title="Transaction ledger">{data.transactions.map((transaction) => <div className="grid grid-cols-[1fr_auto] gap-5 border-b border-border p-5 text-sm last:border-0" key={transaction.id}><div><b>{transaction.description}</b><p className="mt-1 text-xs text-muted-foreground">{transaction.category} · {new Date(transaction.occurredAt).toLocaleDateString()} · {transaction.status}</p></div><span className={transaction.amount >= 0 ? "text-emerald-300" : "text-red-300"}>{money(transaction.amount)}</span></div>)}</Panel></div>;
}

export function AnalyticsWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data, metrics } = snapshot; const markets = [...new Set(data.orders.map((x) => x.marketplace))];
  return <div className="space-y-6"><Header eyebrow="Analytics" title="Business trends and drill-down comparisons" description="Every metric is calculated from stored orders, inventory, supplier, customer, and transaction records." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Revenue" value={money(metrics.revenue)} /><Metric label="Gross profit" value={money(metrics.grossProfit)} /><Metric label="Margin" value={`${metrics.margin.toFixed(1)}%`} /><Metric label="Units sold" value={String(metrics.units)} /></div><div className="grid gap-6 lg:grid-cols-2"><Panel title="Marketplace comparison">{markets.map((market) => <Row key={market} label={market} value={`${data.orders.filter((x) => x.marketplace === market).length} orders`} />)}</Panel><Panel title="Inventory & supplier performance">{data.variants.map((variant) => { const balance = data.balances.find((x) => x.variantId === variant.id); return <Row key={variant.id} label={variant.sku} value={`${balance ? availableUnits(balance) : 0} available`} />; })}</Panel><Panel title="Customer & geography"><p className="p-5 text-sm text-muted-foreground">Geographic analytics use stored customer addresses only; maps are suppressed until real locations exist.</p></Panel><Panel title="Fulfillment metrics"><p className="p-5 text-sm text-muted-foreground">Ship-by dates, status events, and shipments provide late-shipment and fulfillment-time reporting after records are available.</p></Panel></div></div>;
}

export function AutomationsWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot;
  return <div className="space-y-6"><Header eyebrow="Automation center" title="Rule builder, run logs, retries, and failures" description="Rules persist triggers, conditions, actions, retry policies, and idempotency keys once Supabase is connected." /><div className="grid gap-6 lg:grid-cols-2"><Panel title="Supported triggers"><p className="p-5 text-sm text-muted-foreground">Order created/paid/shipped, parcel delayed, low inventory, listing failed, return created, expense created, payout received, and scheduled events.</p></Panel><Panel title="Safe actions"><p className="p-5 text-sm text-muted-foreground">Create a notification/task, update a legal status, add a tag, create reorder draft, reserve inventory, generate insight, or add to review queue.</p></Panel></div><Panel title="Current review queue">{data.notices.map((notice) => <Row key={notice.id} label={notice.title} value={<Status value={notice.severity} />}/>) || <p className="p-5 text-sm text-muted-foreground">No current automation failures.</p>}</Panel></div>;
}

export function AiWorkspace({ snapshot }: { snapshot: ReturnTypeSnapshot }) {
  const { data } = snapshot;
  return <div className="space-y-6"><Header eyebrow="AI center" title="Daily brief and evidence-backed recommendations" description="The deterministic internal tool layer runs on verified business records before a model provider is connected." /><div className="grid gap-6 lg:grid-cols-3"><Panel title="Business tools"><p className="p-5 text-sm text-muted-foreground">Revenue, profit, low stock, dead inventory, marketplace/supplier performance, order detail, deployable cash, and shipment exceptions.</p></Panel><Panel title="Daily brief"><p className="p-5 text-sm text-muted-foreground">Briefs prioritize low stock, delayed inbound, overdue shipment, margin, cash, and unresolved exception signals.</p></Panel><Panel title="Provider adapter"><p className="p-5 text-sm text-muted-foreground">A future model receives structured tool output and evidence, never unverified raw operating data.</p></Panel></div><div className="grid gap-4 md:grid-cols-2">{data.insights.map((insight) => <article className="border border-border bg-card p-5" key={insight.id}><Status value={insight.type} /><h2 className="mt-2 font-semibold">{insight.title}</h2><p className="mt-2 text-sm text-muted-foreground">{insight.summary}</p><p className="mt-3 text-xs text-muted-foreground">Evidence: {insight.evidence}</p><Link className="mt-3 inline-block text-xs text-emerald-400" href={insight.href}>{insight.actionLabel} →</Link></article>)}</div></div>;
}
