/* eslint-disable @next/next/no-img-element -- imported Superbuy image hosts are dynamic and external. */
import Link from "next/link";
import { ExternalLink, PackageOpen, Plus } from "lucide-react";
import { AppLayout } from "@/components/navigation/app-layout";
import { getMarketplace } from "@/lib/marketplaces";
import { analyzeOpportunity } from "@/lib/analyze-opportunity";
import { getOpportunities } from "@/services/opportunities/local-opportunity-store";

export default async function CatalogPage() {
  const opportunities = await getOpportunities();
  return <AppLayout><div className="space-y-6"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-bold">Product Catalog</h1><p className="mt-2 text-muted-foreground">Every opportunity imported from Superbuy and saved in Faust.</p></div><Link href="/opportunity-analyzer" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-medium text-white hover:bg-violet-500"><Plus className="h-5 w-5" />New opportunity</Link></div>{opportunities.length === 0 ? <div className="rounded-xl border border-dashed border-border bg-card p-12 text-center"><PackageOpen className="mx-auto h-10 w-10 text-violet-400" /><h2 className="mt-4 text-lg font-semibold">Your catalog is ready</h2><p className="mt-2 text-sm text-muted-foreground">Import a Superbuy product and save its opportunity to see it here.</p></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{opportunities.map((opportunity) => { const analysis = analyzeOpportunity(opportunity); const marketplace = getMarketplace(opportunity.listing.marketplaceId); return <article key={opportunity.id} className="overflow-hidden rounded-xl border border-border bg-card"><div className="h-44 bg-muted/40">{opportunity.product.media.images[0] && <img src={opportunity.product.media.images[0]} alt="" className="h-full w-full object-cover" />}</div><div className="p-5"><p className="text-xs font-medium text-violet-400">{marketplace.name} · {opportunity.listing.status}</p><h2 className="mt-1 truncate text-lg font-semibold">{opportunity.product.name}</h2><p className="mt-1 truncate text-sm text-muted-foreground">{opportunity.product.supplier.name || "Unknown supplier"}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-muted-foreground">Sale price</p><p className="font-semibold">${opportunity.salePrice.toFixed(2)}</p></div><div><p className="text-muted-foreground">Net profit</p><p className="font-semibold text-emerald-400">${analysis.netProfit.toFixed(2)}</p></div></div><a href={opportunity.product.sourcing.superbuyUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-violet-400 hover:text-violet-300">Open Superbuy <ExternalLink className="h-4 w-4" /></a></div></article>; })}</div>}</div></AppLayout>;
}
