-- Faust OS: transactional onboarding and normalized core operational records
create or replace function public.create_business_with_defaults(p_name text, p_currency text default 'USD', p_timezone text default 'America/New_York') returns uuid language plpgsql security definer set search_path = public as $$
declare new_business_id uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if char_length(trim(p_name)) = 0 then raise exception 'Business name is required'; end if;
  insert into public.profiles(id) values (auth.uid()) on conflict (id) do nothing;
  insert into public.businesses(name,currency,timezone,owner_id) values (trim(p_name),upper(p_currency),p_timezone,auth.uid()) returning id into new_business_id;
  insert into public.business_members(business_id,user_id,role) values (new_business_id,auth.uid(),'owner');
  insert into public.business_settings(business_id) values (new_business_id);
  insert into public.business_workspace_states(business_id) values (new_business_id);
  return new_business_id;
end; $$;
revoke all on function public.create_business_with_defaults(text,text,text) from public;
grant execute on function public.create_business_with_defaults(text,text,text) to authenticated;

create table if not exists public.suppliers (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, source_platform text, store_url text, status text not null default 'active', lead_days integer, rating numeric, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, title text not null, description text, brand text, category text, subcategory text, source_platform text, source_url text, default_supplier_id uuid references public.suppliers(id) on delete set null, status text not null default 'draft', tags text[] not null default '{}', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);
create table if not exists public.product_variants (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, sku text not null, barcode text, title text not null, size text, color text, material text, condition text, attributes jsonb not null default '{}'::jsonb, weight_oz numeric, dimensions jsonb not null default '{}'::jsonb, landed_unit_cost numeric not null default 0 check (landed_unit_cost >= 0), default_price numeric not null default 0 check (default_price >= 0), reorder_point integer not null default 0 check (reorder_point >= 0), reorder_quantity integer not null default 0 check (reorder_quantity >= 0), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,sku));
create table if not exists public.inventory_locations (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, warehouse text not null, room text, zone text, aisle text, shelf text, bin text, scannable_code text, capacity integer, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,scannable_code));
create table if not exists public.inventory_balances (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, variant_id uuid not null references public.product_variants(id) on delete cascade, location_id uuid references public.inventory_locations(id), on_hand integer not null default 0 check (on_hand >= 0), reserved integer not null default 0 check (reserved >= 0), incoming integer not null default 0 check (incoming >= 0), damaged integer not null default 0 check (damaged >= 0), returned integer not null default 0 check (returned >= 0), quarantined integer not null default 0 check (quarantined >= 0), lost integer not null default 0 check (lost >= 0), updated_at timestamptz not null default now(), unique(variant_id,location_id));
create table if not exists public.stock_movements (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, variant_id uuid not null references public.product_variants(id), location_id uuid references public.inventory_locations(id), quantity_delta integer not null, movement_type text not null check (movement_type in ('initial_stock','purchase_received','reservation','reservation_release','shipment','customer_return','supplier_return','damage','loss','found','transfer_out','transfer_in','cycle_count_adjustment','manual_adjustment')), reference_type text, reference_id uuid, reason text, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.purchase_orders (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, supplier_id uuid references public.suppliers(id), reference text not null, status text not null default 'draft', ordered_at timestamptz, expected_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,reference));
create table if not exists public.purchase_order_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade, variant_id uuid not null references public.product_variants(id), expected_quantity integer not null check (expected_quantity > 0), received_quantity integer not null default 0 check (received_quantity >= 0), unit_cost numeric not null default 0 check (unit_cost >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.inbound_parcels (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, purchase_order_id uuid references public.purchase_orders(id), tracking_number text not null, carrier text, status text not null default 'awaiting_dispatch', origin text, destination text, estimated_arrival timestamptz, actual_arrival timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,tracking_number));
create table if not exists public.inbound_parcel_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, inbound_parcel_id uuid not null references public.inbound_parcels(id) on delete cascade, purchase_order_item_id uuid references public.purchase_order_items(id), variant_id uuid not null references public.product_variants(id), expected_quantity integer not null check (expected_quantity > 0), received_quantity integer not null default 0 check (received_quantity >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, email text, phone text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.listings (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, variant_id uuid not null references public.product_variants(id), marketplace text not null, external_id text, external_url text, title text not null, description text, price numeric not null default 0, quantity integer not null default 0, status text not null default 'draft', sync_state text not null default 'manual', error_state text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, customer_id uuid references public.customers(id), marketplace text not null, external_order_id text, status text not null default 'draft', ordered_at timestamptz not null default now(), paid_at timestamptz, shipping_charged numeric not null default 0, marketplace_fees numeric not null default 0, payment_fees numeric not null default 0, shipping_cost numeric not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, listing_id uuid references public.listings(id), variant_id uuid not null references public.product_variants(id), title text not null, quantity integer not null check (quantity > 0), unit_price numeric not null default 0, unit_cost numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.transactions (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid references public.orders(id), purchase_order_id uuid references public.purchase_orders(id), category text not null, amount numeric not null, currency text not null default 'USD', status text not null default 'pending', occurred_at timestamptz not null default now(), description text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, title text not null, description text, priority text not null default 'normal', status text not null default 'open', due_at timestamptz, entity_type text, entity_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, severity text not null default 'info', category text, title text not null, detail text, href text, read_at timestamptz, resolved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.activity_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, detail text, before_value jsonb, after_value jsonb, created_at timestamptz not null default now());

create index if not exists products_business_idx on public.products(business_id,created_at desc); create index if not exists variants_business_idx on public.product_variants(business_id,sku); create index if not exists balances_business_idx on public.inventory_balances(business_id,variant_id); create index if not exists movements_business_idx on public.stock_movements(business_id,variant_id,created_at desc); create index if not exists purchase_orders_business_idx on public.purchase_orders(business_id,status); create index if not exists parcels_business_idx on public.inbound_parcels(business_id,status); create index if not exists listings_business_idx on public.listings(business_id,status); create index if not exists orders_business_idx on public.orders(business_id,status,ordered_at desc); create index if not exists transactions_business_idx on public.transactions(business_id,occurred_at desc); create index if not exists tasks_business_idx on public.tasks(business_id,status,due_at); create index if not exists activity_business_idx on public.activity_events(business_id,created_at desc);
do $$ declare t text; begin foreach t in array array['suppliers','products','product_variants','inventory_locations','inventory_balances','stock_movements','purchase_orders','purchase_order_items','inbound_parcels','inbound_parcel_items','listings','customers','orders','order_items','transactions','tasks','notifications','activity_events'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists "tenant read" on public.%I',t); execute format('create policy "tenant read" on public.%I for select using (public.is_business_member(business_id))',t); execute format('drop policy if exists "tenant write" on public.%I',t); execute format('create policy "tenant write" on public.%I for all using (public.has_business_role(business_id,array[''owner'',''admin'',''operations'',''finance'',''fulfillment''])) with check (public.has_business_role(business_id,array[''owner'',''admin'',''operations'',''finance'',''fulfillment'']))',t); end loop; end $$;
