-- Faust OS completion domain: normalized supporting records, multi-line orders, and scoped roles.
alter table public.inventory_balances add column if not exists created_at timestamptz not null default now();
alter table public.orders add column if not exists tax_collected numeric not null default 0, add column if not exists idempotency_key text;
alter table public.orders add constraint orders_business_idempotency_unique unique (business_id,idempotency_key);
alter table public.order_items add column if not exists product_id uuid references public.products(id) on delete set null, add column if not exists discount_allocation numeric not null default 0, add column if not exists tax_allocation numeric not null default 0, add column if not exists fee_allocation numeric not null default 0, add column if not exists refunded_quantity integer not null default 0 check (refunded_quantity >= 0), add column if not exists returned_quantity integer not null default 0 check (returned_quantity >= 0);

create table if not exists public.product_images (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, url text not null, position integer not null default 0, alt_text text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(product_id,position));
create table if not exists public.inventory_counts (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, location_id uuid references public.inventory_locations(id) on delete set null, status text not null default 'draft' check (status in ('draft','in_progress','completed','cancelled')), counted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.inventory_count_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, inventory_count_id uuid not null references public.inventory_counts(id) on delete cascade, variant_id uuid not null references public.product_variants(id), expected_quantity integer not null, counted_quantity integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(inventory_count_id,variant_id));
create table if not exists public.supplier_contacts (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, supplier_id uuid not null references public.suppliers(id) on delete cascade, name text not null, email text, phone text, role text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.supplier_products (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, supplier_id uuid not null references public.suppliers(id) on delete cascade, variant_id uuid not null references public.product_variants(id) on delete cascade, supplier_sku text, unit_cost numeric not null default 0 check (unit_cost >= 0), lead_days integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(supplier_id,variant_id));
create table if not exists public.purchase_order_payments (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade, amount numeric not null check (amount <> 0), status text not null default 'pending', paid_at timestamptz, reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.receiving_sessions (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, inbound_parcel_id uuid not null references public.inbound_parcels(id) on delete cascade, location_id uuid references public.inventory_locations(id), status text not null default 'open' check (status in ('open','completed','cancelled')), received_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.receiving_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, receiving_session_id uuid not null references public.receiving_sessions(id) on delete cascade, inbound_parcel_item_id uuid not null references public.inbound_parcel_items(id), received_quantity integer not null default 0 check (received_quantity >= 0), damaged_quantity integer not null default 0 check (damaged_quantity >= 0), missing_quantity integer not null default 0 check (missing_quantity >= 0), rejected_quantity integer not null default 0 check (rejected_quantity >= 0), overage_quantity integer not null default 0 check (overage_quantity >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.supplier_issues (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, supplier_id uuid references public.suppliers(id) on delete set null, purchase_order_id uuid references public.purchase_orders(id) on delete set null, type text not null, status text not null default 'open', detail text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.marketplaces (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, code text not null, name text not null, enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,code));
create table if not exists public.marketplace_accounts (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, marketplace_id uuid not null references public.marketplaces(id) on delete cascade, account_name text not null, status text not null default 'disconnected', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.listing_images (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, listing_id uuid not null references public.listings(id) on delete cascade, product_image_id uuid references public.product_images(id) on delete set null, url text not null, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.listing_sync_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, listing_id uuid not null references public.listings(id) on delete cascade, idempotency_key text, direction text not null, status text not null, detail text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,idempotency_key));
create table if not exists public.listing_errors (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, listing_id uuid not null references public.listings(id) on delete cascade, code text, message text not null, resolved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.customer_addresses (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, customer_id uuid not null references public.customers(id) on delete cascade, name text, line1 text not null, line2 text, city text not null, region text, postal_code text, country text not null default 'US', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_status_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, from_status text, to_status text not null, actor_id uuid references public.profiles(id), idempotency_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,idempotency_key));
create table if not exists public.refunds (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, amount numeric not null check (amount > 0), reason text, external_ref text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.returns (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, status text not null default 'requested', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.return_items (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, return_id uuid not null references public.returns(id) on delete cascade, order_item_id uuid not null references public.order_items(id), quantity integer not null check (quantity > 0), disposition text not null default 'inspect', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.packages (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, weight_oz numeric, dimensions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.shipments (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, package_id uuid references public.packages(id) on delete set null, carrier text, service text, tracking_number text, status text not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.shipment_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, shipment_id uuid not null references public.shipments(id) on delete cascade, idempotency_key text, status text not null, location text, occurred_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,idempotency_key));
create table if not exists public.shipping_labels (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, shipment_id uuid not null references public.shipments(id) on delete cascade, format text not null default '4x6', url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.shipping_presets (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, dimensions jsonb not null default '{}'::jsonb, weight_oz numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.financial_accounts (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, type text not null, currency text not null default 'USD', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.transaction_categories (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, kind text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,name));
create table if not exists public.payouts (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, marketplace_account_id uuid references public.marketplace_accounts(id) on delete set null, amount numeric not null, status text not null default 'pending', idempotency_key text, paid_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,idempotency_key));
create table if not exists public.expenses (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, transaction_id uuid references public.transactions(id) on delete set null, amount numeric not null check (amount >= 0), merchant text, receipt_url text, occurred_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.budgets (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, category text not null, period_start date not null, amount numeric not null check (amount >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,category,period_start));
create table if not exists public.tax_reserves (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, amount numeric not null default 0, as_of date not null default current_date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.automation_rules (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, trigger text not null, conditions jsonb not null default '{}'::jsonb, actions jsonb not null default '[]'::jsonb, enabled boolean not null default true, retry_policy jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.automation_runs (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, automation_rule_id uuid not null references public.automation_rules(id) on delete cascade, idempotency_key text not null, status text not null default 'pending', detail text, started_at timestamptz not null default now(), finished_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,idempotency_key));
create table if not exists public.attachments (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, entity_type text not null, entity_id uuid not null, url text not null, filename text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.tags (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, color text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,name));
create table if not exists public.entity_tags (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, tag_id uuid not null references public.tags(id) on delete cascade, entity_type text not null, entity_id uuid not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tag_id,entity_type,entity_id));
create table if not exists public.imported_source_products (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, source_url text not null, source_platform text, raw_data jsonb not null default '{}'::jsonb, imported_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.opportunities (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, imported_source_product_id uuid references public.imported_source_products(id) on delete set null, status text not null default 'draft', title text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.opportunity_cost_inputs (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, opportunity_id uuid not null references public.opportunities(id) on delete cascade, item_cost numeric not null default 0, freight numeric not null default 0, duties numeric not null default 0, fees numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.comparable_listings (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, opportunity_id uuid not null references public.opportunities(id) on delete cascade, marketplace text, price numeric, sold_at timestamptz, url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.opportunity_analyses (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, opportunity_id uuid not null references public.opportunities(id) on delete cascade, score numeric not null default 0, estimated_profit numeric not null default 0, assumptions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.insights (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, type text not null, severity text not null default 'info', title text not null, explanation text not null, recommendation text, confidence numeric, status text not null default 'open', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.insight_evidence (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, insight_id uuid not null references public.insights(id) on delete cascade, entity_type text, entity_id uuid, detail text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.forecasts (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, metric text not null, period_start date not null, value numeric not null, assumptions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.saved_reports (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, definition jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create or replace function public.create_business_with_defaults(p_name text, p_currency text default 'USD', p_timezone text default 'America/New_York') returns uuid language plpgsql security definer set search_path = public as $$ declare new_business_id uuid; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if char_length(trim(p_name)) = 0 then raise exception 'Business name is required'; end if; insert into public.profiles(id) values (auth.uid()) on conflict (id) do nothing; insert into public.businesses(name,currency,timezone,owner_id) values (trim(p_name),upper(p_currency),p_timezone,auth.uid()) returning id into new_business_id; insert into public.business_members(business_id,user_id,role) values (new_business_id,auth.uid(),'owner'); insert into public.business_settings(business_id) values (new_business_id); insert into public.inventory_locations(business_id,warehouse,zone,aisle,shelf,bin,scannable_code) values (new_business_id,'Default warehouse','A','01','01','01','DEFAULT'); insert into public.marketplaces(business_id,code,name) values (new_business_id,'manual','Manual') on conflict do nothing; insert into public.business_workspace_states(business_id) values (new_business_id); return new_business_id; end; $$;

do $$ declare t text; begin foreach t in array array['product_images','inventory_counts','inventory_count_items','supplier_contacts','supplier_products','purchase_order_payments','receiving_sessions','receiving_items','supplier_issues','marketplaces','marketplace_accounts','listing_images','listing_sync_events','listing_errors','customer_addresses','order_status_events','refunds','returns','return_items','packages','shipments','shipment_events','shipping_labels','shipping_presets','financial_accounts','transaction_categories','payouts','expenses','budgets','tax_reserves','automation_rules','automation_runs','attachments','tags','entity_tags','imported_source_products','opportunities','opportunity_cost_inputs','comparable_listings','opportunity_analyses','insights','insight_evidence','forecasts','saved_reports'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "tenant read" on public.%I for select using (public.is_business_member(business_id))',t); execute format('create policy "tenant write" on public.%I for all using (public.has_business_role(business_id,array[''owner'',''admin'',''operations'',''finance'',''fulfillment''])) with check (public.has_business_role(business_id,array[''owner'',''admin'',''operations'',''finance'',''fulfillment'']))',t); end loop; end $$;

create index if not exists order_status_events_order_idx on public.order_status_events(business_id,order_id,created_at desc);
create index if not exists receiving_sessions_parcel_idx on public.receiving_sessions(business_id,inbound_parcel_id);
create index if not exists shipment_events_shipment_idx on public.shipment_events(business_id,shipment_id,occurred_at desc);
create index if not exists automation_runs_rule_idx on public.automation_runs(business_id,automation_rule_id,started_at desc);

-- Replace Phase 1's broad operational write policy with capability-specific policies.
do $$ declare t text; begin
  foreach t in array array['products','product_variants','product_images','inventory_locations','inventory_balances','stock_movements','inventory_counts','inventory_count_items','suppliers','supplier_contacts','supplier_products','purchase_orders','purchase_order_items','purchase_order_payments','inbound_parcels','inbound_parcel_items','receiving_sessions','receiving_items','supplier_issues','marketplaces','marketplace_accounts','listings','listing_images','listing_sync_events','listing_errors','imported_source_products','opportunities','opportunity_cost_inputs','comparable_listings','opportunity_analyses'] loop
    execute format('drop policy if exists "tenant write" on public.%I',t); execute format('create policy "catalog operations write" on public.%I for all using (public.has_business_role(business_id,array[''owner'',''admin'',''operations''])) with check (public.has_business_role(business_id,array[''owner'',''admin'',''operations'']))',t);
  end loop;
  foreach t in array array['orders','order_items','order_status_events','returns','return_items','packages','shipments','shipment_events','shipping_labels','shipping_presets'] loop
    execute format('drop policy if exists "tenant write" on public.%I',t); execute format('create policy "fulfillment write" on public.%I for all using (public.has_business_role(business_id,array[''owner'',''admin'',''fulfillment''])) with check (public.has_business_role(business_id,array[''owner'',''admin'',''fulfillment'']))',t);
  end loop;
  foreach t in array array['financial_accounts','transactions','transaction_categories','payouts','expenses','budgets','tax_reserves','refunds'] loop
    execute format('drop policy if exists "tenant write" on public.%I',t); execute format('create policy "finance write" on public.%I for all using (public.has_business_role(business_id,array[''owner'',''admin'',''finance''])) with check (public.has_business_role(business_id,array[''owner'',''admin'',''finance'']))',t);
  end loop;
  foreach t in array array['tasks','notifications','automation_rules','automation_runs','activity_events','attachments','tags','entity_tags','insights','insight_evidence','forecasts','saved_reports','customers','customer_addresses'] loop
    execute format('drop policy if exists "tenant write" on public.%I',t); execute format('create policy "shared operational write" on public.%I for all using (public.has_business_role(business_id,array[''owner'',''admin'',''operations'',''finance'',''fulfillment''])) with check (public.has_business_role(business_id,array[''owner'',''admin'',''operations'',''finance'',''fulfillment'']))',t);
  end loop;
end $$;
