-- Orders are mutated through this transactional boundary. It locks the order and
-- every affected balance before making a status, inventory, timeline, and audit change.
alter table public.orders add column if not exists packaging_cost numeric not null default 0, add column if not exists advertising_cost numeric not null default 0, add column if not exists shipping_address jsonb, add column if not exists billing_address jsonb, add column if not exists shipping_label_url text, add column if not exists ship_by timestamptz, add column if not exists paid_at timestamptz, add column if not exists tags text[] not null default '{}';
alter table public.order_items add column if not exists marketplace_fee_allocation numeric not null default 0, add column if not exists payment_fee_allocation numeric not null default 0, add column if not exists profit_contribution numeric not null default 0, add column if not exists fulfillment_state text not null default 'unfulfilled', add column if not exists return_state text not null default 'none', add column if not exists refund_state text not null default 'none', add column if not exists cancelled_quantity integer not null default 0 check (cancelled_quantity >= 0);
alter table public.refunds add column if not exists order_item_id uuid references public.order_items(id) on delete set null, add column if not exists shipping_amount numeric not null default 0, add column if not exists fee_adjustment numeric not null default 0, add column if not exists refunded_at timestamptz not null default now(), add column if not exists idempotency_key text;
alter table public.returns add column if not exists reason text, add column if not exists tracking_number text, add column if not exists received_at timestamptz, add column if not exists idempotency_key text;
create unique index if not exists refunds_business_idempotency_idx on public.refunds(business_id,idempotency_key) where idempotency_key is not null;
create unique index if not exists returns_business_idempotency_idx on public.returns(business_id,idempotency_key) where idempotency_key is not null;

create or replace function public.transition_order_status(p_order_id uuid, p_next_status text, p_detail text default '', p_idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.orders%rowtype; item record; b public.inventory_balances%rowtype; actor uuid := auth.uid(); allowed boolean := false; movement_count integer := 0; event_id uuid;
begin
  select * into o from public.orders where id = p_order_id for update; if not found then raise exception 'Order not found'; end if;
  if not public.has_business_role(o.business_id,array['owner','admin','operations','fulfillment']) then raise exception 'Unauthorized order mutation' using errcode='42501'; end if;
  if p_idempotency_key is not null and exists(select 1 from public.order_status_events where business_id=o.business_id and idempotency_key=p_idempotency_key) then return jsonb_build_object('idempotent',true,'order_id',o.id); end if;
  allowed := (o.status='pending_payment' and p_next_status in ('paid','cancelled')) or (o.status='paid' and p_next_status in ('confirmed','reserved','cancelled')) or (o.status='confirmed' and p_next_status in ('reserved','cancelled')) or (o.status in ('reserved','inventory_reserved') and p_next_status in ('ready_to_pack','cancelled')) or (o.status='ready_to_pack' and p_next_status in ('packed','cancelled')) or (o.status='packed' and p_next_status in ('label_created','label_purchased','cancelled')) or (o.status in ('label_created','label_purchased') and p_next_status in ('ready_to_ship','cancelled')) or (o.status='ready_to_ship' and p_next_status='shipped') or (o.status='shipped' and p_next_status in ('in_transit','return_requested')) or (o.status='in_transit' and p_next_status='delivered') or (o.status='delivered' and p_next_status in ('closed','return_requested')) or (o.status='return_requested' and p_next_status='return_in_transit') or (o.status='return_in_transit' and p_next_status='returned') or (o.status='returned' and p_next_status in ('partially_refunded','refunded')) or (o.status='partially_refunded' and p_next_status='refunded');
  if not allowed then raise exception 'Illegal order status transition from % to %',o.status,p_next_status; end if;
  -- Lock and validate every line before mutating any balance (all-or-nothing reservation/shipment).
  if p_next_status in ('reserved','shipped') or (p_next_status='cancelled' and o.status in ('reserved','inventory_reserved','ready_to_pack','packed','label_created','label_purchased','ready_to_ship')) then
    for item in select * from public.order_items where order_id=o.id order by id loop
      select * into b from public.inventory_balances where business_id=o.business_id and variant_id=item.variant_id order by id limit 1 for update; if not found then raise exception 'Missing inventory balance for order item'; end if;
      if p_next_status='reserved' and b.on_hand-b.reserved-b.damaged-b.quarantined < item.quantity-item.cancelled_quantity then raise exception 'Insufficient available inventory'; end if;
      if p_next_status='shipped' and (b.reserved < item.quantity-item.cancelled_quantity or b.on_hand < item.quantity-item.cancelled_quantity) then raise exception 'Insufficient reserved inventory to ship'; end if;
      if p_next_status='cancelled' and b.reserved < item.quantity-item.cancelled_quantity then raise exception 'Reservation cannot be released safely'; end if;
    end loop;
    for item in select * from public.order_items where order_id=o.id order by id loop
      select * into b from public.inventory_balances where business_id=o.business_id and variant_id=item.variant_id order by id limit 1 for update;
      if p_next_status='reserved' then update public.inventory_balances set reserved=reserved+(item.quantity-item.cancelled_quantity),updated_at=now() where id=b.id; insert into public.stock_movements(business_id,variant_id,location_id,quantity_delta,movement_type,reference_type,reference_id,reason,actor_id) values(o.business_id,item.variant_id,b.location_id,-(item.quantity-item.cancelled_quantity),'reservation','order',o.id,p_detail,actor); update public.order_items set fulfillment_state='reserved',updated_at=now() where id=item.id;
      elsif p_next_status='cancelled' then update public.inventory_balances set reserved=reserved-(item.quantity-item.cancelled_quantity),updated_at=now() where id=b.id; insert into public.stock_movements(business_id,variant_id,location_id,quantity_delta,movement_type,reference_type,reference_id,reason,actor_id) values(o.business_id,item.variant_id,b.location_id,(item.quantity-item.cancelled_quantity),'reservation_release','order',o.id,p_detail,actor); update public.order_items set fulfillment_state='cancelled',updated_at=now() where id=item.id;
      else update public.inventory_balances set reserved=reserved-(item.quantity-item.cancelled_quantity),on_hand=on_hand-(item.quantity-item.cancelled_quantity),updated_at=now() where id=b.id; insert into public.stock_movements(business_id,variant_id,location_id,quantity_delta,movement_type,reference_type,reference_id,reason,actor_id) values(o.business_id,item.variant_id,b.location_id,-(item.quantity-item.cancelled_quantity),'shipment','order',o.id,p_detail,actor); update public.order_items set fulfillment_state='shipped',updated_at=now() where id=item.id; end if; movement_count:=movement_count+1;
    end loop;
  end if;
  update public.orders set status=p_next_status, paid_at=case when p_next_status='paid' then coalesce(paid_at,now()) else paid_at end, updated_at=now() where id=o.id;
  insert into public.order_status_events(business_id,order_id,from_status,to_status,actor_id,idempotency_key) values(o.business_id,o.id,o.status,p_next_status,actor,p_idempotency_key) returning id into event_id;
  insert into public.activity_events(business_id,actor_id,action,entity_type,entity_id,detail) values(o.business_id,actor,'Order marked '||replace(p_next_status,'_',' '),'order',o.id,p_detail);
  return jsonb_build_object('idempotent',false,'order_id',o.id,'status_event_id',event_id,'movement_count',movement_count);
end $$;
revoke all on function public.transition_order_status(uuid,text,text,text) from public;
grant execute on function public.transition_order_status(uuid,text,text,text) to authenticated;
