create table if not exists public.order_import_reviews (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, marketplace text not null, external_order_id text not null, external_listing_id text, external_sku text, item_title text not null, quantity integer not null check(quantity > 0), unit_price numeric not null check(unit_price >= 0), likely_variant_ids uuid[] not null default '{}', match_confidence numeric not null default 0, state text not null default 'open' check(state in ('open','linked','ignored','non_inventory','cancelled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.saved_order_views (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, user_id uuid not null references public.profiles(id), name text not null, filters jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,user_id,name));
alter table public.order_import_reviews enable row level security; alter table public.saved_order_views enable row level security;
create policy "order import review read" on public.order_import_reviews for select using(public.is_business_member(business_id)); create policy "order import review write" on public.order_import_reviews for all using(public.has_business_role(business_id,array['owner','admin','operations'])) with check(public.has_business_role(business_id,array['owner','admin','operations']));
create policy "saved order view read" on public.saved_order_views for select using(public.is_business_member(business_id)); create policy "saved order view write" on public.saved_order_views for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create index if not exists order_import_reviews_business_state_idx on public.order_import_reviews(business_id,state,created_at desc);

create or replace function public.create_order_transactional(p_order jsonb, p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare business uuid := (p_order->>'business_id')::uuid; actor uuid := auth.uid(); customer_id uuid; order_id uuid; line jsonb; variant public.product_variants%rowtype; external_id text := nullif(p_order->>'external_order_id',''); marketplace_name text := coalesce(nullif(p_order->>'marketplace',''),'Manual');
begin
  if business is null or not public.has_business_role(business,array['owner','admin','operations']) then raise exception 'Unauthorized order creation' using errcode='42501'; end if;
  if p_idempotency_key is not null and exists(select 1 from public.orders where business_id=business and idempotency_key=p_idempotency_key) then return jsonb_build_object('idempotent',true,'order_id',(select id from public.orders where business_id=business and idempotency_key=p_idempotency_key)); end if;
  if external_id is not null and exists(select 1 from public.orders where business_id=business and marketplace=marketplace_name and external_order_id=external_id) then raise exception 'Duplicate external order ID for marketplace'; end if;
  if coalesce(p_order#>>'{customer,name}','')='' or jsonb_array_length(coalesce(p_order->'items','[]'::jsonb))=0 then raise exception 'Customer and at least one item are required'; end if;
  select id into customer_id from public.customers where business_id=business and lower(email)=lower(nullif(p_order#>>'{customer,email}','')) limit 1;
  if customer_id is null then insert into public.customers(business_id,name,email) values(business,p_order#>>'{customer,name}',nullif(p_order#>>'{customer,email}','')) returning id into customer_id; end if;
  insert into public.orders(business_id,customer_id,marketplace,external_order_id,status,ordered_at,paid_at,shipping_charged,shipping_cost,marketplace_fees,payment_fees,tax_collected,notes,idempotency_key,shipping_address,billing_address,tags) values(business,customer_id,marketplace_name,external_id,'pending_payment',coalesce((p_order->>'ordered_at')::timestamptz,now()),nullif(p_order->>'paid_at','')::timestamptz,coalesce((p_order->>'shipping_charged')::numeric,0),coalesce((p_order->>'shipping_cost')::numeric,0),coalesce((p_order->>'marketplace_fee')::numeric,0),coalesce((p_order->>'payment_fee')::numeric,0),coalesce((p_order->>'tax_collected')::numeric,0),nullif(p_order->>'notes',''),p_idempotency_key,p_order->'shipping_address',p_order->'billing_address',coalesce(array(select jsonb_array_elements_text(coalesce(p_order->'tags','[]'::jsonb))),'{}')) returning id into order_id;
  for line in select * from jsonb_array_elements(p_order->'items') loop select * into variant from public.product_variants where id=(line->>'variant_id')::uuid and business_id=business and active=true; if not found then raise exception 'Order item variant is missing or inactive'; end if; if coalesce((line->>'quantity')::integer,0)<=0 or coalesce((line->>'unit_price')::numeric,-1)<0 then raise exception 'Invalid order item quantity or price'; end if; insert into public.order_items(business_id,order_id,product_id,variant_id,listing_id,title,quantity,unit_price,unit_cost,discount_allocation,tax_allocation,marketplace_fee_allocation,payment_fee_allocation,fulfillment_state,return_state,refund_state) values(business,order_id,variant.product_id,variant.id,nullif(line->>'listing_id','')::uuid,coalesce(nullif(line->>'title',''),variant.title),(line->>'quantity')::integer,coalesce((line->>'unit_price')::numeric,0),coalesce((line->>'unit_cost')::numeric,variant.landed_unit_cost),coalesce((line->>'discount')::numeric,0),coalesce((line->>'tax')::numeric,0),coalesce((line->>'marketplace_fee')::numeric,0),coalesce((line->>'payment_fee')::numeric,0),'unfulfilled','none','none'); end loop;
  insert into public.order_status_events(business_id,order_id,to_status,actor_id,idempotency_key) values(business,order_id,'pending_payment',actor,coalesce(p_idempotency_key,gen_random_uuid()::text)); insert into public.activity_events(business_id,actor_id,action,entity_type,entity_id,detail) values(business,actor,'Order created','order',order_id,'Manual or imported order created.'); insert into public.notifications(business_id,severity,title,detail,href) values(business,'warning','Unpaid order','New order requires payment confirmation.','/orders'); return jsonb_build_object('idempotent',false,'order_id',order_id);
end $$;
revoke all on function public.create_order_transactional(jsonb,text) from public; grant execute on function public.create_order_transactional(jsonb,text) to authenticated;
