-- Transactional financial and return mutations. Exceptions inside these functions
-- roll back the order, ledger, line item, inventory, timeline, and audit writes.
alter table public.customers add column if not exists lifetime_contribution_profit numeric not null default 0, add column if not exists refund_count integer not null default 0, add column if not exists return_count integer not null default 0;
alter table public.return_items add column if not exists received_quantity integer not null default 0 check(received_quantity >= 0), add column if not exists status text not null default 'requested', add column if not exists notes text;

create or replace function public.create_order_refund_transactional(p_order_id uuid, p_amount numeric, p_reason text, p_order_item_id uuid default null, p_quantity integer default null, p_shipping_amount numeric default 0, p_fee_adjustment numeric default 0, p_external_ref text default null, p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.orders%rowtype; item public.order_items%rowtype; actor uuid:=auth.uid(); gross numeric; refunded numeric; refund_id uuid; event_id uuid;
begin
  select * into o from public.orders where id=p_order_id for update; if not found then raise exception 'Order not found'; end if; if not public.has_business_role(o.business_id,array['owner','admin','operations','finance']) then raise exception 'Unauthorized refund mutation' using errcode='42501'; end if;
  if p_idempotency_key is not null and exists(select 1 from public.refunds where business_id=o.business_id and idempotency_key=p_idempotency_key) then return jsonb_build_object('idempotent',true,'refund_id',(select id from public.refunds where business_id=o.business_id and idempotency_key=p_idempotency_key)); end if;
  if p_amount<=0 then raise exception 'Refund amount must be positive'; end if; select coalesce(sum(unit_price*quantity-discount_allocation),0)+o.shipping_charged into gross from public.order_items where order_id=o.id; select coalesce(sum(amount),0) into refunded from public.refunds where order_id=o.id;
  if refunded+p_amount>gross then raise exception 'Refund exceeds refundable order amount'; end if;
  if p_order_item_id is not null then select * into item from public.order_items where id=p_order_item_id and order_id=o.id for update; if not found or p_quantity is null or p_quantity<=0 or item.refunded_quantity+p_quantity>item.quantity-item.cancelled_quantity then raise exception 'Invalid line refund quantity'; end if; update public.order_items set refunded_quantity=refunded_quantity+p_quantity,refund_state=case when refunded_quantity+p_quantity>=quantity then 'refunded' else 'partial' end,updated_at=now() where id=item.id; end if;
  insert into public.refunds(business_id,order_id,order_item_id,amount,reason,external_ref,shipping_amount,fee_adjustment,refunded_at,idempotency_key) values(o.business_id,o.id,p_order_item_id,p_amount,p_reason,p_external_ref,p_shipping_amount,p_fee_adjustment,now(),p_idempotency_key) returning id into refund_id;
  insert into public.transactions(business_id,order_id,category,amount,status,occurred_at,description) values(o.business_id,o.id,'refund',-p_amount,'cleared',now(),'Refund: '||p_reason);
  update public.customers set refund_count=refund_count+1 where id=o.customer_id; update public.orders set status=case when refunded+p_amount>=gross then 'refunded' else 'partially_refunded' end,updated_at=now() where id=o.id;
  insert into public.order_status_events(business_id,order_id,from_status,to_status,actor_id,idempotency_key) values(o.business_id,o.id,o.status,case when refunded+p_amount>=gross then 'refunded' else 'partially_refunded' end,actor,coalesce(p_idempotency_key,gen_random_uuid()::text)) returning id into event_id;
  insert into public.activity_events(business_id,actor_id,action,entity_type,entity_id,detail) values(o.business_id,actor,'Order refund created','order',o.id,p_reason); insert into public.notifications(business_id,severity,title,detail,href) values(o.business_id,'info','Refund recorded',p_reason,'/orders');
  return jsonb_build_object('idempotent',false,'refund_id',refund_id,'status_event_id',event_id);
end $$;
revoke all on function public.create_order_refund_transactional(uuid,numeric,text,uuid,integer,numeric,numeric,text,text) from public; grant execute on function public.create_order_refund_transactional(uuid,numeric,text,uuid,integer,numeric,numeric,text,text) to authenticated;

create or replace function public.receive_order_return_transactional(p_return_id uuid, p_dispositions jsonb, p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.returns%rowtype; ri record; item public.order_items%rowtype; b public.inventory_balances%rowtype; actor uuid:=auth.uid(); d jsonb; quantity integer; disposition text;
begin
 select * into r from public.returns where id=p_return_id for update; if not found then raise exception 'Return not found'; end if; if not public.has_business_role(r.business_id,array['owner','admin','operations','fulfillment']) then raise exception 'Unauthorized return mutation' using errcode='42501'; end if;
 for ri in select * from public.return_items where return_id=r.id order by id loop select * into item from public.order_items where id=ri.order_item_id for update; select * into b from public.inventory_balances where business_id=r.business_id and variant_id=item.variant_id order by id limit 1 for update; if not found then raise exception 'Inventory balance not found for return item'; end if; d:=p_dispositions->ri.order_item_id::text; quantity:=coalesce((d->>'quantity')::integer,ri.quantity); disposition:=coalesce(d->>'disposition','quarantine'); if quantity<=0 or quantity>ri.quantity-ri.received_quantity then raise exception 'Invalid return receipt quantity'; end if; update public.inventory_balances set on_hand=on_hand+quantity,damaged=damaged+case when disposition='damaged' then quantity else 0 end,quarantined=quarantined+case when disposition='quarantine' then quantity else 0 end,updated_at=now() where id=b.id; update public.return_items set received_quantity=received_quantity+quantity,status='received',notes=disposition,updated_at=now() where id=ri.id; update public.order_items set returned_quantity=returned_quantity+quantity,return_state='received',updated_at=now() where id=item.id; insert into public.stock_movements(business_id,variant_id,location_id,quantity_delta,movement_type,reference_type,reference_id,reason,actor_id) values(r.business_id,item.variant_id,b.location_id,quantity,'customer_return','return',r.id,disposition,actor); end loop;
 update public.returns set status='received',received_at=now(),updated_at=now() where id=r.id; update public.customers set return_count=return_count+1 where id=(select customer_id from public.orders where id=r.order_id); insert into public.activity_events(business_id,actor_id,action,entity_type,entity_id,detail) values(r.business_id,actor,'Return received','return',r.id,'Return items received and inspected.'); insert into public.notifications(business_id,severity,title,detail,href) values(r.business_id,'info','Return received','Review refund eligibility.','/orders'); return jsonb_build_object('idempotent',false,'return_id',r.id);
end $$;
revoke all on function public.receive_order_return_transactional(uuid,jsonb,text) from public; grant execute on function public.receive_order_return_transactional(uuid,jsonb,text) to authenticated;
